### ISSUE TITLE
[Request] Upkeep 1.15.2

### ISSUE THREAD

**Issue by Fisheiyy** [Goldorion/MCreatorFabricGenerator#100]
**Describe the feature**
keep updating if not updating just bug fixing 1.15.2 version of the fabric generator
**Describe why you want the feature**
1.15.2 mods are still quite relevant
**Additional context**
1.14.4 would be nice too those mods are a thing they are just rarer, also i would help with this but i dont know how to generator and videos would help i would gladly contribute to helping you two since its just two of you

**Comment by Goldorion** [comment]
I'm currently alone to develop it (except when external contributors open a pull request), so I will always stay in the latest Minecraft version supported by Fabric (except snapshots) for the moment.
