### ISSUE TITLE
[Bug] MapColor causes a build error

### ISSUE THREAD

**Issue by Fisheiyy** [Goldorion/MCreatorFabricGenerator#101]
**Describe the bug**
while opening/compiling workspace it says it cannot find a symbol

**Log**
Share mcreator.log in a paste website such as [Hastebin](https://hastebin.com/).

**Affected version(s)** Release/Snapshot X.X.X+foo
MCreator EAP 2021.1 12313
**To Reproduce**
1. Go to workspace
2. Click on build and run
3. Scroll down to regenerate code and build
4. See error in console

**Expected behavior**
no error and compilation

**Screenshots**
![image](https://user-images.githubusercontent.com/54205282/113443739-2b9e6b00-93b8-11eb-8905-5279dae7151e.png)

**Additional context**
workspace

**Comment by Goldorion** [comment]
Which mod elements cause the problem?

**Comment by Fisheiyy** [comment]
it seems to be unhappy about the color on map of a block?  also i compiled and am using the generator with the latest patch so i could atleast get one of my mods ported

**Comment by Fisheiyy** [comment]
okay for some reason changing the color on map to default fixed that but now it comes up with this
![image](https://user-images.githubusercontent.com/54205282/113464454-68875380-93f2-11eb-8eeb-d263f04421d0.png)

**Comment by Goldorion** [comment]
Which version are you using? Please fill **ALL** fields asked.

**Comment by Fisheiyy** [comment]
> Which version are you using? Please fill **ALL** fields asked.

i compiled with the latest commits because it fixed my other issue and i didnt want to wait until a release happened

**Comment by Fisheiyy** [comment]
ty

**Comment by Goldorion** [comment]
No problem :)

**Comment by Fisheiyy** [comment]
oh us bad news, it didnt fix this 
![image](https://user-images.githubusercontent.com/54205282/113498896-ab225c00-94d6-11eb-9bed-e1f1f049d1f8.png)
i just compiled the generator and tested atleast half of it is fixed?

**Comment by Goldorion** [comment]
Are they blocks or plants? If they are custom blocks, try to regenerate the code.

**Comment by Fisheiyy** [comment]
i just did that didnt work thats what i have been doing to constantly find the error
they are blocks

**Comment by Goldorion** [comment]
> 
> 
> i just did that didnt work thats what i have been doing to constantly find the error
> they are blocks

Regenerate the code because the errors should be fixed.

**Comment by Fisheiyy** [comment]
i have been regenerating the code

**Comment by Goldorion** [comment]
> 
> 
> i have been regenerating the code

They are not blocks. They are plant mod elements. I forgot to apply the fix to them.

**Comment by Goldorion** [comment]
Everything works fine for me, so wait for the next update. I will try to make a patch soon.

**Comment by Fisheiyy** [comment]
your commit changes it from material to materialcolor that other screenshot is it complaining about the material it doesnt understand what earth is? 
![image](https://user-images.githubusercontent.com/54205282/113499034-1fa9ca80-94d8-11eb-9a27-b30836011d1d.png)

**Comment by Goldorion** [comment]
> 
> 
> your commit changes it from material to materialcolor that other screenshot is it complaining about the material it doesnt understand what earth is?
> ![image](https://user-images.githubusercontent.com/54205282/113499034-1fa9ca80-94d8-11eb-9a27-b30836011d1d.png)

Ok, you are talking about the material, not the map color. I confirm that the mapping file is not updated.

**Comment by Fisheiyy** [comment]
okay i will try again as soon as the next commit which hopefully fixes all the problems but this is only one of my 2 mods i am still attempting to port to fabric so more errors will most likely come up since my biggest mod has over 50 elements and over 4000 downloads.

**Comment by Goldorion** [comment]
It should be good now.

**Comment by Fisheiyy** [comment]
trying now

**Comment by Fisheiyy** [comment]
it regenerated and isnt screaming at me gonna export the mod, upload and move to the next one now, expect another ticket soon :)
