### ISSUE TITLE
[Bug] Multiple Bugs

### ISSUE THREAD

**Issue by Fisheiyy** [Goldorion/MCreatorFabricGenerator#102]
**Describe the bug**

**Log**
Share mcreator.log in a paste website such as [Hastebin](https://hastebin.com/).

**Affected version(s)** Release/Snapshot X.X.X+foo
MCreator EAP 2021.1 12313, Generator with latest commits (compiled bc no release)
**To Reproduce**
Regenerate code

**Expected behavior**
no error? tf u mean

**Screenshots**
![image](https://user-images.githubusercontent.com/54205282/113499568-ad87b480-94dc-11eb-993e-22355f7dfaa7.png)
![image](https://user-images.githubusercontent.com/54205282/113499572-afea0e80-94dc-11eb-9b28-6571ac4efa78.png)
![image](https://user-images.githubusercontent.com/54205282/113499578-ba0c0d00-94dc-11eb-83ac-993efc7cad7c.png)

**Additional context**
[)

**Comment by Fisheiyy** [comment]
im guessing the one where it says it doesnt know e is because e represents the entity as in the dropped item but im not sure

**Comment by Goldorion** [comment]
At `To Reproduce`, you are supposed to explain how to reproduce the bug. What is the mod element we are talking about, which parameters we have to change and which values we have to use, etc.

**Comment by Fisheiyy** [comment]
> At `To Reproduce`, you are supposed to explain how to reproduce the bug. What is the mod element we are talking about, which parameters we have to change and which values we have to use, etc.

all you have to do is load the workspace and regenerate/build it and you will get the errors it seems its unhappy with some procedures made for allowing fortune to work on custom ores, also seems its angry with a block or 3...

**Comment by Goldorion** [comment]
> 
> 
> > At `To Reproduce`, you are supposed to explain how to reproduce the bug. What is the mod element we are talking about, which parameters we have to change and which values we have to use, etc.
> 
> all you have to do is load the workspace and regenerate/build it and you will get the errors it seems its unhappy with some procedures made for allowing fortune to work on custom ores, also seems its angry with a block or 3...

I meant how to reproduce it on another workspace.

**Comment by Fisheiyy** [comment]
> > > At `To Reproduce`, you are supposed to explain how to reproduce the bug. What is the mod element we are talking about, which parameters we have to change and which values we have to use, etc.
> > 
> > 
> > all you have to do is load the workspace and regenerate/build it and you will get the errors it seems its unhappy with some procedures made for allowing fortune to work on custom ores, also seems its angry with a block or 3...
> 
> I meant how to reproduce it on another workspace.

oh, shit idk if im honest its a few different mod elements the workspace is linked under additional context fyi

**Comment by Fisheiyy** [comment]
well im gonna go to sleep and pick this back up in the morning just wanted to get it open and inform you so if anything you can overlook the screenshots and trying using the workspace to figure it

**Comment by Goldorion** [comment]
Everything has been fixed.

**Comment by Fisheiyy** [comment]
going to download and try

**Comment by Fisheiyy** [comment]
it works, thx
