### ISSUE TITLE
[Bug] "error: cannot find symbol" when creating stairs.

### ISSUE THREAD

**Issue by TheZaxter** [Goldorion/MCreatorFabricGenerator#108]
**Describe the bug**
Whenever I try to compile workspace with any stairs block, it gives me the error "error: cannot find symbol".

**Log**
https://pastebin.com/2enFgbTx

**Affected version(s)** Release/Snapshot X.X.X+foo
Release 1.16.5

**To Reproduce**
1. Create Custom Stairs
2. Click on Save mod element or click Build Workspace
3. See error

**Expected behavior**
To actually Build the Workspace.

**Comment by Goldorion** [comment]
The stair block base has not been implemented yet.

**Comment by Oslypsis** [comment]
Is there a workaround to get custom stairs? Maybe make the model in blockbench and create a custom bounding box?

**Comment by Micasddsa** [comment]
If you are talking about custom stairs as in regular just custom texture stairs than that has been fixed now.
if you are talking about custom stairs as in custom models than idk.

**Comment by Oslypsis** [comment]
> If you are talking about custom stairs as in regular just custom texture stairs than that has been fixed now. if you are talking about custom stairs as in custom models than idk.

Hi, thanks for responding. I went to make a wood pack today and the stairs wouldn't compile. It said it was missing a symbol. I'm using MCreator version 2022.3.48217 and the Fabric Generator version 0.60.0

Is my version just out of date or maybe I somehow did something wrong? I just clicked on the button and followed the prompts. It immediately couldn't compile upon generating, so I realized I had to save all the files one by one, but the stairs wouldn't cooperate. Thanks for any info you have on this.

**Comment by Micasddsa** [comment]
Yea if you want patched stairs download this.
[fabric-generator-dev.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/10129005/fabric-generator-dev.zip)
It's a development build with the new fixes. make sure to delete the old version of the plugin.

**Comment by Oslypsis** [comment]
> Yea if you want patched stairs download this. [fabric-generator-dev.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/10129005/fabric-generator-dev.zip) It's a development build with the new fixes. make sure to delete the old version of the plugin.

Thank you!! It worked! Now I just have to figure out how to make my leaves decay when there's no log anymore...
