### ISSUE TITLE
Add "Does item stay in crafting grid" item parameter support

### ISSUE THREAD

**Issue by NeptunesOrca** [Goldorion/MCreatorFabricGenerator#111]
Using v.1.0.2 in MCreator.

When I check the "Does item stay in crafting grid when when crafted?" checkbox, the item is still consumed during tests.

**Comment by Goldorion** [comment]
The parameter has not been implemented yet.

**Comment by Goldorion** [comment]
Added with 8c6133eba381b4e858a63c87e39191ca7c584ef8
