### ISSUE TITLE
[Bug] Keybind not calling procedure on key press.

### ISSUE THREAD

**Issue by Shroototem** [Goldorion/MCreatorFabricGenerator#115]
Setting a keybind to run a command does not work.

MCreator 2021.2 EAP (23417)

![image](https://user-images.githubusercontent.com/47718633/122685261-4f639700-d1d8-11eb-964f-43d397f470cc.png)
![image](https://user-images.githubusercontent.com/47718633/122685265-58546880-d1d8-11eb-8017-b316b89eb28b.png)

This gives no errors.

Expected: 
\<Player321\> 1

**Comment by Shroototem** [comment]
I was executing from the world and not the player/entity...

**Comment by Shroototem** [comment]
I set the procedure to use the entity but it's still not working. I should really have tested this stuff... Sorry for the closing and opening of the report.

**Comment by Goldorion** [comment]
Please follow the bug report template.

**Comment by Shroototem** [comment]
I'm sorry but I'm not quite sure where to get the MCreator log file.

**Comment by Goldorion** [comment]
Users/user/.mcreator/logs/mcreator.log
