### ISSUE TITLE
Update to MCreator 2021.2 - Second snapshot

### ISSUE THREAD

**Issue by ultimateimmersion** [Goldorion/MCreatorFabricGenerator#116]
I'm trying to build Fabric 1.16.5 workspace from 2021.1 in 2021.2 EAP (23417) and it returns a ton of errors that I think should not happen since I'm using IDs just to load models with no fancy functions and no procedures. This same workspace worked perfectly in 2021.1 and in 2021.1 EAP versions before.

Any idea why this is happening?

This is the console log: https://pastebin.com/hCdYfaLC

**Comment by Goldorion** [comment]
Logs have to be on pastebin.

**Comment by Goldorion** [comment]
Re-importing the project fixes most of the problems. However, the procedure that returns a variable doesn't work due to the new variable system. A second snapshot should be released in the following days, so I'll work on updating the generator to this new snapshot, so as soon as it's released, I will release a patch fixing this problem.

**Comment by ultimateimmersion** [comment]
I see, sorry about that.


What do you mean re-importing?

I've tried clearing the workspace cache and regenerating the code completely and also installing the latest Fabric plugin version (probably not any different from the snapshot one). None of that worked and returned same errors.

I have some of the procedures in that were ported from my Forge mod but all of them are completely bypassed meaning the nodes are not connected with the output one. Not sure if that causes any issues but it didn't in other builder versions.

**Comment by Goldorion** [comment]
> 
> 
> I see, sorry about that.
> 
> What do you mean re-importing?
> 
> I've tried clearing the workspace cache and regenerating the code completely and also installing the latest Fabric plugin version (probably not any different from the snapshot one). None of that worked and returned same errors.
> 
> I have some of the procedures in that were ported from my Forge mod but all of them are completely bypassed meaning the nodes are not connected with the output one. Not sure if that causes any issues but it didn't in other builder versions.

Click on Build & Run -> Reload Gradle project. Then, wait until everything is completed. You shouldn't have errors after that (except for elements using custom variables). It worked with my test workspace, so it should also work with your workspace.

**Comment by Zockerhopper** [comment]
> > I see, sorry about that.
> > What do you mean re-importing?
> > I've tried clearing the workspace cache and regenerating the code completely and also installing the latest Fabric plugin version (probably not any different from the snapshot one). None of that worked and returned same errors.
> > I have some of the procedures in that were ported from my Forge mod but all of them are completely bypassed meaning the nodes are not connected with the output one. Not sure if that causes any issues but it didn't in other builder versions.
> 
> Click on Build & Run -> Reload Gradle project. Then, wait until everything is completed. You shouldn't have errors after that (except for elements using custom variables). It worked with my test workspace, so it should also work with your workspace.

I have the same Problem but sadly when it returns the error I cannot press Build & Run and I only have 4 options, none of which allow me to press Build & Run at the Top. So how do you expect me to press Build & Run?

**Comment by ultimateimmersion** [comment]
Ok a little update. I tried Reload Gradle project which doesn't return any errors but exporting it does the same log I sent above.

I also tried running a test play which returns the same errors.

The only things I'm using with each block are:

- JSON model
- DUSWNE rotation
- CUTOUT_MIPPED type
- Bounding box coordinates
- Block name
- Block material
- Custom tab in the menu
- Footstep sound
- Sometimes collision disabled

Very basic things.

**Comment by Goldorion** [comment]
I need your workspace to test.

**Comment by ultimateimmersion** [comment]
> 
> 
> I need your workspace to test.

Can you give me your email or a way to DM you? I just tested the new 2021.2 snapshot, same errors.

**Comment by Fisheiyy** [comment]
> > I need your workspace to test.
> 
> Can you give me your email or a way to DM you? I just tested the new 2021.2 snapshot, same errors.

you can just zip and drop your workspace here, no one is gonna go through the effort of stealing your mod, i have dropped my mods workspace here before but if your that insecure about it just wait until gold replies then you can remove its link from your comment

**Comment by ultimateimmersion** [comment]
Here's my latest test workspace. I tested with 2021.2 second snapshot and it doesn't work: https://drive.google.com/file/d/1T4kOoumkjo-hTXDui1DhvRDcEUKwx5vq/view?usp=sharing

**Comment by Goldorion** [comment]
Update: I found the real cause. It's a problem with the Gradle cache. So in order to use the plugin with MCreator 2021.1, you simply have to delete the Gradle cache folder. Thank you for your understanding and sorry for the inconvenience.

**Comment by ultimateimmersion** [comment]
Are you talking about manual cache revomal or the function in mcreator, because I've tried the one in mcr 2021.1 numerous times and it didn't work. Just tried it again in the latest snapshot 2021.2 b26215 multiple times and I got same errors.
