### ISSUE TITLE
[Bug] error: cannot find symbol

### ISSUE THREAD

**Issue by Fisheiyy** [Goldorion/MCreatorFabricGenerator#119]
**Describe the bug**
error: cannot find symbol

**Log**
https://pastebin.com/RtJqkXe8

**Affected version(s)** Release/Snapshot X.X.X+foo
Fabric Generator 1.1 Release, MCreator 2021.2 Snapshot 2

**To Reproduce**
1. Click Re-generate code & Re-build
2. Get Error

**Expected behavior**
Compile my workspace 

**Additional context**
It is giving the error on the Armor sets that I have.

**Describe the bug**
error: cannot find symbol

**Log**
https://pastebin.com/WsixbCn1

**Affected version(s)** Release/Snapshot X.X.X+foo
Fabric Generator 1.1 Release, MCreator 2021.2 Snapshot 2

**To Reproduce**
1. Click Re-generate code & Re-build
2. Get Error

**Expected behavior**
Compile my workspace 

**Additional context**
It is giving the error on the Armor sets that I have.

P.S (I know you want my workspace to test [here ya go Gold]())

**Comment by Fisheiyy** [comment]
i tried clearing gradle cache and it still didnt fix it, i am using version 1.1 of the generator https://pastebin.com/WsixbCn1

**Comment by Goldorion** [comment]
Clear Gradle caches and use MCreator 2021.1. The generator doesn't support the new variable system yet.

**Comment by Fisheiyy** [comment]
ok

**Comment by Fisheiyy** [comment]
> Clear Gradle caches and use MCreator 2021.1. The generator doesn't support the new variable system yet.

that didnt fix it https://pastebin.com/nCLiHVCm
