### ISSUE TITLE
[Bug] Workspace setup failed

### ISSUE THREAD

**Issue by KintsugiKitten** [Goldorion/MCreatorFabricGenerator#121]
Whenever I attempt to run MCreator with the Fabric Generator plugin, the workspace fails to set up.

https://pastebin.com/23KsJiPV

I'm using version 1.1, file named generator-fabric-1.16.5.

1. Go to 'New workspace' or 'Open workspace'
2. Click on desired workspace
3. Wait

**Expected behavior**
The gradle would set up and I would be able to create a mod.

**Screenshots**
![Screenshot 2021-06-29 131643](https://user-images.githubusercontent.com/82187693/123847557-55dec680-d8dc-11eb-8b10-dae5ed392c39.png)

**Additional context**
I have attempted to find a fix and none have worked.

**Comment by Goldorion** [comment]
https://github.com/Goldorion/Fabric-Generator-MCreator/issues/116#issuecomment-870192786
