### ISSUE TITLE
[Bug] Tried deleting cache, still not opening workspace

### ISSUE THREAD

**Issue by melodicGemstone** [Goldorion/MCreatorFabricGenerator#122]
**Describe the bug**
I've been having troubles with workplace setup. I've tried to delete the cache as many people have recommended [C:\Users\USER\.mcreator\gradle\caches] but every time I've gotten the error shown in the pastebin below.

**Log**
https://pastebin.com/wt0eGcFZ

**Affected version(s)** 1.16.5 - 1.1

**To Reproduce**
1. Attempt to open a workspace on MCreator 2021.1 using the 1.16.5 - 1.1 release on this github
2. See error

**Expected behavior**
I expected the workspace to open and to be able to make my mod as intended

**Comment by Goldorion** [comment]
Try to delete the Gradle folder, otherwise, you'll have to wait for the next version. I tested with this new version, it worked, so I can't change anything. It's not on my side.
