### ISSUE TITLE
[Request] Add 1.18 Experimental Snapshot Support from 1.17.1.

### ISSUE THREAD

**Issue by BurnutsGaming** [Goldorion/MCreatorFabricGenerator#134]
**Describe the feature**
I noticed that Fabric is available in 1.18 Experimental Snapshot 2 and I have to help make a generator

**Describe why you want the feature**
Port to 1.18 Experimental Snapshot. Somebody might want to make for 1.18 Experimental Snapshot easily with MCreator.

**Additional context**
Before I make a Pull Request for that add 1.18 branch in your repository from your 1.17.1 branch not the 1.16.5 branch or it will not merge automatically.

**Comment by Goldorion** [comment]
I can’t even bave a 1.17.1 version,. Oh and, I will **NEVER** put as much work in something as experimental as an experimental snapshot, no matter what users want.
