### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [Goldorion/MCreatorFabricGenerator#136]
It's not showing up on the menu as a clickable
![image](https://user-images.githubusercontent.com/58344347/128955827-3e72ccf6-eb08-490d-9ac5-328cb2fc79e8.png)

**Comment by Goldorion** [comment]
Use a supported version

**Comment by BubblePlayzTHEREAL** [comment]
Where do I get a supported version?

**Comment by smmmadden** [comment]
click on the Code tab in this space.  All the details you need are there. :-)
