### ISSUE TITLE
[Bug] Not possible to generate plants at the end

### ISSUE THREAD

**Issue by captetch** [Goldorion/MCreatorFabricGenerator#139]
**Describe the bug**![Screenshot_4](https://user-images.githubusercontent.com/43005752/130369658-25ddec85-5788-440c-9098-ec2aa9f3a6df.png)Basically, when creating a new plant, and putting it to generate at the end, it will result in an error that says "The variable THE_END does not exist"

**Log**
https://pastebin.com/kuxVWr7R

**Affected version(s)** Release/Snapshot 1.16.5-1.4

**To Reproduce**
1. Create a new plant element
2. Put to generate on the end
3. See error

**Expected behavior**
An error message popping up saying: "The variable THE_END does not exist"

**Screenshots**
![Screenshot_5](https://user-images.githubusercontent.com/43005752/130369659-9412ba4d-a5f3-4796-8379-2fc991ba5fe6.png)
![Screenshot_4](https://user-images.githubusercontent.com/43005752/130369658-25ddec85-5788-440c-9098-ec2aa9f3a6df.png)

**Additional context**
I was trying to create a biome on the end, thanks to the new update, but when I went to create some plants, I reprimanded myself with this error.

**Comment by Goldorion** [comment]
Can you try to replace THE_END by THEEND? I think it's the problem. If it doesn't work, I will need to search the variable name.

**Comment by captetch** [comment]
actually, I've been doing some testing, and you should rename THE_END to END, even so, it would be great if this error were fixed.
