### ISSUE TITLE
[Bug] Lots of entity bugs

### ISSUE THREAD

**Issue by Dukeasas** [Goldorion/MCreatorFabricGenerator#141]
**Describe the bug**
If an entity has a boss bar, the code is unable to compile
If an entity has any pieces of equipment, the code is unable to compile
If an entity has any item drop on death, the code is unable to compile

**Log**
Attach Images
![BossBar](https://user-images.githubusercontent.com/32406472/131230993-7306707d-9f5f-44d6-93e4-c0b2ea861848.PNG)
![Wearanything](https://user-images.githubusercontent.com/32406472/131230994-cf1dfeb1-28f8-4697-aca9-2d87928c87f8.PNG)
![DropAnythingOnDeath](https://user-images.githubusercontent.com/32406472/131230999-914135a7-6793-4b2e-80c2-3f9754878a93.PNG)

**Affected version(s)** Release/Snapshot X.X.X+foo
Fabric Generator 1.4 - 1.16.5 - MCreator 2021.2

**To Reproduce**
1. Create an entity with biped model
2. enable boss bar, or equip any weapons, or make any default drop
3. click save

**Expected behavior**
No error

**Screenshots**
If applicable, add screenshots to help explain your problem

**Additional context**

**Comment by Goldorion** [comment]
One bug by issue
