### ISSUE TITLE
[Bug] Bugged Raytracing Procedures

### ISSUE THREAD

**Issue by captetch** [Goldorion/MCreatorFabricGenerator#143]
**Describe the bug**
When creating a new procedure using raytracing blocks, several errors occur in the build

**Log**
https://pastebin.com/9DPPx67R

**Affected version(s)** Fabric Generator 1.16.5-1.4.1

**To Reproduce**
1. Create a new procedure
2. add raytrace procedure blocks
3. See error
![Screenshot_1](https://user-images.githubusercontent.com/43005752/131268781-8a7f1a2b-2711-404c-852d-b64e0035de14.png)

**Expected behavior**
Various errors involving these procedures

**Screenshots**
If applicable, add screenshots to help explain your problem
![Screenshot_2](https://user-images.githubusercontent.com/43005752/131268759-8c982716-3f40-4b1e-9f97-37716b8ca9b6.png)

**Additional context**
I was trying to create a custom effect for my mod so I ran into the error

**Comment by Goldorion** [comment]
Thank you for the bug report. It will be fixed in the next update.
