### ISSUE TITLE
[Request] Same file names as Forge

### ISSUE THREAD

**Issue by ultimateimmersion** [Goldorion/MCreatorFabricGenerator#144]
Would it be possible to use same file name generations as Forge MCR instance does? 

It was working seamlessly before and it was really easy for some of us resource pack creators to use same resource pack on both loaders since the file names were totally unified. That way users could also use same map on both loaders, but latest Fabric plugin version sometimes uses underscores "_" in the **blockstate**, **model/block** and **model/item** names which forces us to create two different packs.

Could you please check if there's any difference between the two in file name generation?

Thank you!

**Comment by Goldorion** [comment]
Can you give me an example, please? I'm not sure to understand which files you are talking of.

**Comment by ultimateimmersion** [comment]
It happens to about 40% of my IDs and it has to do with the actual workspace ID I think. Still figuring out the actual cause but here's one example. 

Block instance in workspace: https://pasteboard.co/KiiygQ8.png

In Fabric generator **now**: https://pasteboard.co/KiiARbR.png

In Fabric generator **before**: https://pasteboard.co/KiiAEaW.png

Exact same name is generated for blockstates in both cases before and after.


_Note that this exact workspace was working seamlessly with Forge before when extracting blockstates and models folder from the mod to resource pack. I did not change any IDs in the workspace or anywhere._

**Comment by ultimateimmersion** [comment]
This one is a bit strange. It has a name without underscores in blockstates as it should (no screenshots attached), but has added underscores in models/block.

Block instance in workspace: https://pasteboard.co/KiiFEgB.png

In Fabric generator now: https://pasteboard.co/KiiG0GC.png

In Fabric generator before: https://pasteboard.co/KiiFUIC.png

**Comment by ultimateimmersion** [comment]
Digging deeper I figured my exports contain duplicates of old names without and new with underscores. Same thing happens in blockstates and models/item. But Fabric mod only uses new name with underscores and old ones are ignored as I have old ones in the resource pack which was working prior and are working in Forge. And yes I did wipe out the gradle cache completely multiple times.

![image](https://user-images.githubusercontent.com/67540502/131368214-07e006d8-d062-4f01-b2b2-5ebac3d0ef4c.png)

**Comment by ultimateimmersion** [comment]
Checking Forge now as I figured this change applied globally to whole gradle system it seems. It's creating the same thing in my Forge instance. I believe this can create a huge mess with users that used MCR prior and the change happened recently (within a week or so)

**Comment by Goldorion** [comment]
> It's creating the same thing in my Forge instance.

Do I need to fix something?

**Comment by ultimateimmersion** [comment]
You can close this. This change was applied to the gradle itself, so we had to change all IDs to work with the updated version.
