### ISSUE TITLE
[Bug] Error when trying to create mob default drop for entity

### ISSUE THREAD

**Issue by Dukeasas** [Goldorion/MCreatorFabricGenerator#147]
**Describe the bug**
Error when trying to create mob default drop for entity

**Log**
Attached Images
![image](https://user-images.githubusercontent.com/32406472/131953912-451ebaf3-a374-428d-8e45-67a2b2b9c4ec.png)

**Affected version(s)** Release/Snapshot X.X.X+foo

1.4.1 - 1.16.5 - MCreator 2021.2

**To Reproduce**
1. Create an entity with biped model
2. Add something to the mob default drop in the behaviour tab
3. click save mod element

**Expected behavior**
No error

**Screenshots**
If applicable, add screenshots to help explain your problem

**Additional context**

**Comment by Goldorion** [comment]
Can you give me your mcreator.log when you have this error, please?

**Comment by Dukeasas** [comment]
Attached Log
[mcreator.log](https://github.com/Goldorion/Fabric-Generator-MCreator/files/7107514/mcreator.log)

**Comment by Goldorion** [comment]
Fixed with 4f10498eef6401c638b0c9618682137d9599ef93
