### ISSUE TITLE
[Bug] Ranged items do not compile

### ISSUE THREAD

**Issue by Stoutscientist** [Goldorion/MCreatorFabricGenerator#148]
**Describe the bug**
Every time I try to make a ranged item MCreator will say there is a error compiling.

**Log**
Not sure where to find that

**Affected version(s)** I'm using MCreator 2021.2 and fabric generator 1.16.5-1.4.1_0

**To Reproduce**
1. Go to 'Make a new workspace using the generator in 2021.2'
2. Click on 'Ranged item and then set it up in any way'
3. Scroll down to 'Save'
4. See error (It won't compile)

**Expected behavior**
For it to compile.

**Screenshots**
https://imgur.com/a/qdkK0Ow
That weird name is just my example ranged item name

**Additional context**
I'm making my forge mod fabric and I was copying over the same ranged item properties and photo from my forge mod and when I hit save MCreator said there was a error compiling. If you want to see the message I got click the imgur link in the screenshots section.

**Comment by Goldorion** [comment]
Please provide more details about the problem. You are too general.

**Comment by Stoutscientist** [comment]
I'm not trying to sound rude btw. It is general. whenever a ranged item is made it won't compile. I don't know what else to say

**Comment by Stoutscientist** [comment]
> Please provide more details about the problem. You are too general.

I added a little bit more context (just now)

**Comment by Stoutscientist** [comment]
> Please provide more details about the problem. You are too general.

Oh I also meant to say I think it could possibly be that bullet model is not supported

**Comment by Goldorion** [comment]
Fixed with 4f10498eef6401c638b0c9618682137d9599ef93
