### ISSUE TITLE
Ranged items are still not compiling but I found the root cause

### ISSUE THREAD

**Issue by Stoutscientist** [Goldorion/MCreatorFabricGenerator#149]
**Describe the bug**
Whenever I make a ranged item and then add a bullet event it will not compile.

**Log**
Not sure where that is

**Affected version(s)** MCreator 2021.2 and the newest plugin version at this time (1.4.2)

**To Reproduce**
1. Make a new ranged item
2. Add a bullet event
3. And then it will not compile

**Expected behavior**
I thought the bullet event was going to compile

**Screenshots**
https://i.imgur.com/tfMrrfb.png

**Additional context**
If I add a bullet event my ranged item will stop compiling.

Thank you!

**Comment by Goldorion** [comment]
I just tested with the same trigger you showed on your screenshot and I don't have a compilation error.

**Comment by Stoutscientist** [comment]
I'm so confused how can I fix it

**Comment by Goldorion** [comment]
Try to regenerate the code. If it does not work, the problem is inside your procedure.

**Comment by Stoutscientist** [comment]
I figured out that immediate source entity is causing it to not compile

**Comment by Stoutscientist** [comment]
But I need to use it

**Comment by Stoutscientist** [comment]
So the mod will compile if I use immediate source entity until I add it to while bullet flying tick... Strange

**Comment by Stoutscientist** [comment]
> Try to regenerate the code. If it does not work, the problem is inside your procedure.

Would you like me to make a new bug report since I found the root cause?
Thanks for bearing with me I know I am being annoying.
