### ISSUE TITLE
[Request] Display armors on biped model in entity

### ISSUE THREAD

**Issue by Dukeasas** [Goldorion/MCreatorFabricGenerator#150]
**Describe the feature**
Not sure if it is a bug or a missing feature, But currently the armors that wear by the biped model entity are invisible (Including weapons) and drop 100% when the entity dies.

**Describe why you want the feature**
It will be nice to have the biped model entity to display what it is wearing and wielding, and when the entity dies the armors only have a small chance to drop like the vanilla games. This will allow us to create a much better human entity for mods.

**Additional context**
Not much else to say here, just thank you and I am looking forward to the next update!

**Comment by Goldorion** [comment]
Fixed with 43922ef

**Comment by Dukeasas** [comment]
This was not fixed in the latest 1.5 version

**Comment by Goldorion** [comment]
I fixed it, but I put the code when the Chicken model is selected. 😅

**Comment by Dukeasas** [comment]
lol I saw that, thanks man

**Comment by Dukeasas** [comment]
Hi! Sorry to bother you, I know you might want to wait for a few more bugs before making another release. But the mod I am making can't really continue without this bug fix. Is there a way for you to release it? Thanks

**Comment by Goldorion** [comment]
Fixed in 7af0261edaa3f0df561bac8054aa8069d65e0bf8

**Comment by Goldorion** [comment]
> 
> 
> Hi! Sorry to bother you, I know you might want to wait for a few more bugs before making another release. But the mod I am making can't really continue without this bug fix. Is there a way for you to release it? Thanks

I just released a patch fixing this bug (adding this feature? anyways you know what I mean xD).
