### ISSUE TITLE
[Bug] Immediate source entity in procedure added to any bullet procedure template in a ranged item causes it to not compile

### ISSUE THREAD

**Issue by Stoutscientist** [Goldorion/MCreatorFabricGenerator#152]
**Describe the bug**
Whenever I use Immediate source entity in ranged item bullet tick it will stop compiling

**Log**
Idk where that iss
**Affected version(s)** MCreator 2021.2 and Fabric gen 1.4.2

**To Reproduce**
1. Make a new ranged item
2. Make a new procedure that has to do with immediate source entity and add it to while bullet flying tick
3. Save it

**Expected behavior**
For my ranged item/procedure to compile

**Screenshots**
(also im using force immediate source entity to ride event/target entity

**Additional context**
nothin

Also thanks for bearing with me because I know I'm being really annoying

**Comment by Goldorion** [comment]
7af0261edaa3f0df561bac8054aa8069d65e0bf8 didn't fix this issue. It fixed #150

**Comment by Kyberilium08** [comment]
I have the same problem! Anyone?
