### ISSUE TITLE
[Bug] when i use when liveing entity hit with tool i get a build erorr

### ISSUE THREAD

**Issue by ghost** [Goldorion/MCreatorFabricGenerator#156]
sorry for my bad english
the erorr:

 
Executing Gradle task: build 
Build info: MCreator 2021.2.36710, fabric-1.16.5, 64-bit, 15341 MB, Windows 10, JVM 11.0.11, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk 
> Configure project : 
Fabric Loom: 0.7.34 
> Task :compileJava FAILED 
C:\Users\username\MCreatorWorkspaces\simplex_mod\src\main\java\net\mcreator\simplexmod\item\FireSwordTool.java:56: error: cannot find symbol 
         int x = (int) target.getPosX(); 
                             ^ 
  symbol:   method getPosX() 
  location: variable target of type LivingEntity 
C:\Users\AQ\MCreatorWorkspaces\simplex_mod\src\main\java\net\mcreator\simplexmod\item\FireSwordTool.java:57: error: cannot find symbol 
         int y = (int) target.getPosY(); 
                             ^ 
  symbol:   method getPosY() 
  location: variable target of type LivingEntity 
C:\Users\AQ\MCreatorWorkspaces\simplex_mod\src\main\java\net\mcreator\simplexmod\item\FireSwordTool.java:58: error: cannot find symbol 
         int z = (int) target.getPosZ(); 
                             ^ 
  symbol:   method getPosZ() 
  location: variable target of type LivingEntity 
C:\Users\AQ\MCreatorWorkspaces\simplex_mod\src\main\java\net\mcreator\simplexmod\item\FireSwordTool.java:62: error: cannot find symbol 
            $_dependencies.put("entity", entity); 
                                         ^ 
  symbol: variable entity 
4 errors 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 5s 
1 actionable task: 1 executed 
BUILD FAILED 
Task completed in 15 seconds

**Comment by Goldorion** [comment]
Please follow the bug report template.
