### ISSUE TITLE
[Bug] Gradle won't build when entity is made

### ISSUE THREAD

**Issue by TheMagicalSC** [Goldorion/MCreatorFabricGenerator#159]
**Describe the bug**
Whenever I make an entity with the plugin, the workspace doesn't build. I've checked the build log, and it says it's something to do with the entity's drops.

**Log**
When entity has a drop item, this shows.
https://hastebin.com/utuvokujom.yaml
When entity has no drops, this one shows.
https://hastebin.com/pevawevagi.yaml

**Affected version(s)**
2021.2 Mcreator, generator-fabric-1.5.1

**To Reproduce**
1. Make an entity.

**Expected behavior**
To be able to make an entity.

**Screenshots**
If applicable, add screenshots to help explain your problem

**Additional context**
There is none

**Comment by Goldorion** [comment]
I tried to add a drop to a custom entity with a custom item, a custom block, a vanilla item and a vanilla block and all of them worked fine.
