### ISSUE TITLE
when exporting the mod, says you need to install any version of Fabric.

### ISSUE THREAD

**Issue by notiamb1** [Goldorion/MCreatorFabricGenerator#162]
**Describe the bug**
when exporting the mod, and launching ffabric 1.16.5, it says i need to install any versiojn of fabric.

**Log**
(i cant find log file)

**Affected version(s)** Release/Snapshot X.X.X+foo
release

**To Reproduce**
1. Export the project in Mcreator
2. Place jar ifle in mods folder
3. launch fabric 1.16.5
4. eerrror

**Expected behavior**
expected for it to lauch

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/90900969/137073296-c69f4817-d9c3-4cea-92ac-5e0655831c9a.png)

**Additional context**
it wil only work when launching thrugh mcreator

**Comment by Goldorion** [comment]
Do you have the Fabric API installed?
