### ISSUE TITLE
[Request] Adding translucency

### ISSUE THREAD

**Issue by ultimateimmersion** [Goldorion/MCreatorFabricGenerator#163]
Would love to see translucency being added to this plugin. Any eta on this?

**Comment by Goldorion** [comment]
What do you mean by "translucency"?

**Comment by ultimateimmersion** [comment]
There are 4 types of blocks in Minecraft and also in Forge instance of mcr: solid, cutout, cutout_mipped and translucent - which is also recognized by shaders to render glass like materials. For now translucency in this plugin results an error upon compile. Can this be added?

**Comment by Goldorion** [comment]
> There are 4 types of blocks in Minecraft and also in Forge instance of mcr: solid, cutout, cutout_mipped and translucent - which is also recognized by shaders to render glass like materials. For now translucency in this plugin results an error upon compile. Can this be added?

So it's should be a bug report.

**Comment by ultimateimmersion** [comment]
Well I don't know what's going on in the back end, why the error is occurring. Is it a missing or bugged feature. Do I need to make another bug report or is this acknowledged now?
