### ISSUE TITLE
[Bug] Foods do not exist at all.

### ISSUE THREAD

**Issue by Duckloveshack** [Goldorion/MCreatorFabricGenerator#164]
**Describe the bug**
When making a food item, it is not present in Minecraft
Doesn't exist as an ID
Not present in the creative inventory at all.
In the SRC files, it is not present

**Log**
https://hastebin.com/etaroyekax.sql

**Affected version(s)** 
Release 2021.2 + Fabric Generator 1.5.1

**To Reproduce**
1. Make a new workspace
2. Make a new food element
3. Run client
4. Try to give yourself the item with /give

**Expected behavior**
The food item should exist in game and should work as intended.

**Additional context**
I made an example workspace to show off the bug.
[exampleworkspace.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/7403240/exampleworkspace.zip)

**Comment by Duckloveshack** [comment]
Another thing I want to add is that Gradle says there's no source when building and testing upon saving the food element

**Comment by Goldorion** [comment]
> Another thing I want to add is that Gradle says there's no source when building and testing upon saving the food element

MCreator doesn't generate the food element because there is a FreeMarker error into the template, so Gradle is also not happy.
