### ISSUE TITLE
Bug with harvest custom ore

### ISSUE THREAD

**Issue by ModMan2021** [Goldorion/MCreatorFabricGenerator#165]
So I made a custom pickaxe, with the harvest level of 4, it can mine all the vanilla ores, except the custom one that I made (vanilla pickaxe can harvest this ore, which is the weird part) 
I have no clue what causes this bug

**Comment by Goldorion** [comment]
https://fabricmc.net/wiki/tutorial:blocks#configuring_block_drops
It will be fixed when I will be automatically generated when I will update to MC 1.17.1 with MCreator 2021.3

**Comment by ModMan2021** [comment]
So there's no hope for 1.16.5? Rip man

**Comment by Goldorion** [comment]
> 
> 
> So there's no hope for 1.16.5? Rip man

I don't have the feature I need to implement this change. Klemen only added it a few days ago. maybe in the future, I will work again on the past versions, but for the moment, I'm only working on the latest version (possible).

**Comment by ModMan2021** [comment]
I fixed it, with help from someone, I just did it by adding  pickaxes.json under data/fabric/tags/items and then
{
  "replace": false,
  "values": [
    "modid:item_pickaxe",
  ]
}

**Comment by Goldorion** [comment]
I already did this before, but it caused some problems, so I removed it. But your thing is good. I simply need a special condition for block templates to be able to implement this properly.
