### ISSUE TITLE
[Bug] MCreator says "can't compile properly" when a script is added to the event "When food eaten" in a food item

### ISSUE THREAD

**Issue by Micasddsa** [Goldorion/MCreatorFabricGenerator#166]
**Describe the bug**
When compiling a mod when a script is added to the event "When food eaten" in a food item, MCreator Reports that it can't compile properly

**Log**
https://hastebin.com/ocomucevek.yaml
(Includes Both Build Logs and mcreator.log)

**Affected version(s)**
Release 2021.2 + Fabric Generator

**To Reproduce**
1. Make a food item
2. go to triggers
3. make a script for the event "When food eaten" (can contain anything)
4. save & compile
5. should tell you that it does not compile properly

**Expected behavior**
Food should save and compile just fine without any errors

**Screenshots**
https://cdn.discordapp.com/attachments/847896533143388175/902356268436578314/compileerror.png
https://cdn.discordapp.com/attachments/847896533143388175/902356647853297664/scriptadded.png
(Shouldn't really help but i included it because it might help)

**Comment by Goldorion** [comment]
Thank you for the report. A patch should come in the upcoming hours, so I can fix a few more bugs.

**Comment by Goldorion** [comment]
Several build errors were still present in the generator, so I released a patch to kill them.
* [Bugfix] Fix Get fuel power of, Is blockat solid, replace block, get/set logic/text block NBT Tag of block, get enchantment level of itemstack, get smelting result, place structure, run function, set global spawn, set time, spawn item entity, get biome at, get dimension id procedure blocks
* [Bugfix] Fix music disc build error
* [Bugfix #166] Fix the On food eaten food trigger
https://mcreator.net/plugin/64512/mcreator-fabric-generator

**Comment by Micasddsa** [comment]
The problem is still here.

Build Logs and mcreator.log
https://cdn.discordapp.com/attachments/847896533143388175/902716902189707334/ERRORREPORT.txt

I have cleared the Gradle folder, cleaned build files, reload project, and regenerated the code. i still run into this issue.

**Comment by Goldorion** [comment]
> 
> 
> The problem is still here.
> 
> Build Logs and mcreator.log https://cdn.discordapp.com/attachments/847896533143388175/902716902189707334/ERRORREPORT.txt
> 
> I have cleared the Gradle folder, cleaned build files, reload project, and regenerated the code. i still run into this issue.

It's impossible to have the same issue with this trigger. However, other triggers have this issue.

**Comment by Micasddsa** [comment]
After investigating the issue and creating a new workspace, it does not say it has any problemes anymore.

but now i have a new issue where foods don't show up AT ALL. no item id, dosen't show up in creative menu, nothing. extracting the jar, it has the files but i don't think it actually generated the data itself so it can be in the game. (idk much about files in a fabric mod but i think this is generally how it goes.)

**Comment by Goldorion** [comment]
> 
> 
> After investigating the issue and creating a new workspace, it does not say it has any problemes anymore.
> 
> but now i have a new issue where foods don't show up AT ALL. no item id, dosen't show up in creative meun, nothing. extracting the jar, it has the files but i don't think it actually generated the data itself so it can be in the game. (idk much about files in a fabric mod but i think this is generally how it goes.)

If you have another problem, please open another issue.
