### ISSUE TITLE
[Bug] Food doesn't show up in Minecraft / Food isn't included in the main mod class

### ISSUE THREAD

**Issue by Duckloveshack** [Goldorion/MCreatorFabricGenerator#168]
**Describe the bug**
When making a Food element, it doesn't show up, but the plugin still generates the source code for the element.
No food element is included in the main class ([modname]Mod)

**Log**
https://www.toptal.com/developers/hastebin/ayizucuqip.sql

**Affected version(s)** 
MCreator 2021.2 + Fabric Generator 1.5.3

**To Reproduce**
1. Create a new workspace
2. Make a new Food element
3. Run Client
4. Try to give yourself the food item using /give

**Expected behavior**
The food should show up in Minecraft

**Additional context**
I made an example workspace to show off the bug
[exampleworkspace_v2.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/7431860/exampleworkspace_v2.zip)

**Comment by Duckloveshack** [comment]
I have identified that the main class ([modname]Mod) doesn't include the food items for whatever reason

**Comment by Goldorion** [comment]
I can confirm the bug. Food elements are not generated in the main class. However, I won't make future patches for the 1.16.5 version of the generator. I already started working on the 1.17.1 version.
