### ISSUE TITLE
[Bug] Tool triggers cause build errors

### ISSUE THREAD

**Issue by NameLord** [Goldorion/MCreatorFabricGenerator#169]
I don't know if its a bug or it is not implemented but when i im trying to put the procedure in my sword doesn't work. same as giving achivment when i craft something same.

**Comment by NameLord** [comment]
Like if you put a Procedure in a trigger element it shows this.
Procedure in Trigger
![image](https://user-images.githubusercontent.com/27507408/139252558-d8cd8177-928d-4334-88d5-6d10fdac375c.png)

Error:
![image](https://user-images.githubusercontent.com/27507408/139252583-e6865995-606e-4ef4-9402-3884e0ea9738.png)

Build Log: https://hashb.in/#FAAmFEA8FMGMFcAuBLAdgcxAcQE4EMATAG2hETwGcBrALhACN5kiCwAhJlkNAMwHs6AWQDCOaHkR8cIAEwAGGQEYAdDOUBmAGwB2RXIA0IHnno5ksALQrFm5QFZDmgCwX6yRIYAci9QE4QgmyGAOpoBHwA7hQg2oYAUgBqgiCKKnLKqfEAgglZAPoAEgDyguB0wjQAOgCqFNA4FJUAcljQUujQlQAi0NSSAA6VWUREIABizL2VYyZmsIJ4VPWCfASNAFYEVGAAfCDCfKg8yOjwYiD9OHzrcIggdMAzpuYgADJ8fAC2dOnaGk67EAAFUo2xosC+/UmcTwADc8GAKjU6g1mq12p0RGIJFJglIqBR+nhYFNPqt4EQ8A0IlICJUKDhYJVPng0JV1nC8JVUNBEMzYNjJDhmeTKdTaZV3NBPpUAJIkgDKNJwBCBHyIyg58Jomk8dHqVxwdFgeFQqD4d2OqFYFAAnp96HxRqAQK63a60HdICAALwgAAUnoAlGQqR1EMpwwAFPgUAAa/qDAG4wO60+mMxmAHqpkB2h1Ouiuz68gAWqxA0djCZDLqIfBNKEOdHhZhMJFDOHDID4PDItv6pFeyFhaHQ4FQKEQtsRVVq9UaLTaXcxonEQrxOAJRJJjTJBApVIoyrpDKZLLZWq5PL5nwF66kIoPYuPEqlMvl0CVtLVTs1nJ1Xx9RwQ1jVNc1LTCPN7UdZ1M24ScQBnP1A0nENyBXCMqwoABNRMUxdeCiMzHMXXzWCixAEtEHLVhsLw2tXXrRtkGbEBW2QdtSAw7te37Qc3hHMcJynGdgCRedUSXDFKixB8cE3bdiVJUUjxPelGWZVlUHZTluV5flBUffdD3FFVJUQaU5UVE9fw1K8aG0ORgNAkATTNC0jCg8inVzDNPRAAAvX0A2DTtw0jXkYwoAAtfC/OIxK3VI10fKISjqNoysotjOLGJAZiJFY1AWypTj6A7HjeR7PtpwE4dRwwET3DEiSUUXdEV1ktccQU/FCWUvdVLM09NIvHSr3029716p9TNfcz32sr9bPVf9tW0JwXKkMCPMg61oILODiIAEjyAhoEHa1oFQWBkF6ZR+iQf0ACIbtEl7DHelrkwSpL/qIlLDoo9iyq4kBvunMAAQNKRomAPYQWoe4IU+KESBheFxiyWVXnALowDGHHXmqAAlMoQA4ZhWGMSZWAidxSxAU0IcgEl+ibVBlDAAAqEBglLCQQAid7hauDAHigOAkGKoxWRIGmpFDZGAHJwUhaFORV7mEf2DXKU5uW6ZTOpuNLUhUfR+oIZApW+CQJ7LSVi7yGYCgdb5oEcFtB5SfgVBhcZkALAsChyFgKhEHwEkew52XJGyu4aNIMPiW2KPlO5v2A4Zmjg4sXg+B7aQQ4uxhMD4OPDjIIvuzJc56wrh2kCz/3A7zkOKHcmvE6MClRjQCgTlLRB3d57Bqvr0hzaIfpmbuEfEH6CgaAAelXmf+kjfBiGgZR2nYapcYJoncfxhCQHUeHFGZ2BOfB8hqDoG/oBgBBLNYYA2CP14T+J8/gBI22JbEgH8L7yDzHAQ4awwBAA=

**Comment by NameLord** [comment]
Thank you for re-opening the issue this was duplicate since he didn't provide the logs.
[Issue#156](https://github.com/Goldorion/Fabric-Generator-MCreator/issues/156)

**Comment by Goldorion** [comment]
I won't make future patches for the 1.16.5 version of the generator as I already started working on the 1.17.1 version. So, I won't fix this bug.
