### ISSUE TITLE
[Bug] Armor Build Error?

### ISSUE THREAD

**Issue by NameLord** [Goldorion/MCreatorFabricGenerator#170]
**Describe the bug**
Creating Multiple Creative Tabs gives build error

**Log**
https://www.toptal.com/developers/hastebin/womupetipe.yaml

**Affected version(s)** 
Release MCreator 2021.2

**To Reproduce**
1. Create the first creative tab
2. After that create anotherr one named something elste
3. See error

**Expected behavior**
To create another creative tab

**Screenshots**
![image](https://user-images.githubusercontent.com/27507408/139518030-c3d1f997-cf6e-476e-beba-e3e7ef512997.png)

**Comment by Goldorion** [comment]
Can you provide your workspace, please? I checked the log file you gave and it doesn't seem to be a creative that causes the build error.

**Comment by NameLord** [comment]
Whats your Discord username because i want the project private so i don't want to publish to public.
Mine is: NGeorge#5042

**Comment by Goldorion** [comment]
> 
> 
> Whats your Discord username because i want the project private so i don't want to publish to public. Mine is: NGeorge#5042

Make a minimal reproducible workspace instead

**Comment by Goldorion** [comment]
I won't make future patches for the 1.16.5 version of the generator as I already started working on the 1.17.1 version. So, I won't fix this bug.
