### ISSUE TITLE
When creating procedure error [Bug] Title

### ISSUE THREAD

**Issue by christianfirecup** [Goldorion/MCreatorFabricGenerator#172]
**Describe the bug**
the procedure errors don't let Minecraft Minecraft build doesn't no the method getItem inside the item.java

**Log**
Share mcreator.log in a paste website such as [Hastebin](https://hastebin.com/).
https://pastebin.com/iqb63dH8
https://pastebin.com/BCZGQc4y line 63

**Affected version(s)** Release/Snapshot X.X.X+foo
1.16.5 newest version of fabric generator

**To Reproduce**
1. Go to 'procedure'
2. create your procedure
3. connect procedure to item
4. Save and build 
5. See an error

**Expected behavior**
build properly

**Comment by NameLord** [comment]
This is a duplicate see this [Issue#169](https://github.com/Goldorion/Fabric-Generator-MCreator/issues/169)
