### ISSUE TITLE
I tried to make an end biome and it didn't spawn. no errors. but when it was in the nether it worked perfectely fine.

### ISSUE THREAD

**Issue by minecraftmaker12** [Goldorion/MCreatorFabricGenerator#177]
can you try to find out why?

**Comment by minecraftmaker13** [comment]
how is this invalid? alt account btw

**Comment by smmmadden** [comment]
I wouldn't expect a response as he doesn't provide enough feedback or an opportunity to provide the extra details, so the bugs simply get closed as invalid.  That said, reading the description you provided none of the required details like Minecraft version, mod versions, mcreator versions or even the latest logs were provided, so it's like looking for a needle in a haystack.  When reporting issues, don't assume the developer knows what setup you have, it is up to you to provide everything needed so it can be investigated and/or fixed.
