### ISSUE TITLE
[Bug] can't acces workspace 

### ISSUE THREAD

**Issue by CristalGaming** [Goldorion/MCreatorFabricGenerator#180]
**The bug and what happened**
so after installing the mod I tried to transfer my mod's workspace to 1.17.1 but after a did that i it gived me an error and can't acces anyting except the log. i can't even change it back to 1.16.5.
...so i also tried to create a workspace on that version but it give me the same error. 

**Log**
https://www.toptal.com/developers/hastebin/votexulega.yaml

Version: 1.6-beta-1 for minecraft 1.17.1

![image](https://user-images.githubusercontent.com/88732817/157055207-3d6b7d1d-57f4-4998-9b48-1ed343e8093f.png)

**Comment by Atten007** [comment]
Can reproduce in Fabric-Generator-Mcreator 1.17.1 v.0.6.0 beta 2, my System on which Mcreator runs is macOS Big Sur 11.6.1.

**Comment by Goldorion** [comment]
```
If you already opened a workspace, follow these steps:
    1. Close your workspace and go inside your workspace's folder
    2. Open in Notepad or another text editor the `.mcreator` file
    3. Search `currentGenerator`, inside `workspaceSettings` and replace `fabric-1.17.1` by `fabric-1.16.5` (Install it!)
    4. Save, close, re-open your workspace, and re-select Fabric 1.17.1```

**Comment by Goldorion** [comment]
It seems some people still have the problem, so I'm re-opening it. If you are one of them, please give me your workspace, so I can test myself.

**Comment by Frost-ZX** [comment]
It seems that the file `path to the workspace/src/main/resources/mod_id.accesswidener` is still not created automatically.
However, the error can be fixed by manually creating this file.

**Comment by Goldorion** [comment]
> It seems that the file `path to the workspace/src/main/resources/mod_id.accesswidener` is still not created automatically. However, the error can be fixed by manually creating this file.

The file is inside the generator. There is simply a problem with MCreator not adding the file to the workspace. This is why I need a workspace.

**Comment by Goldorion** [comment]
I'm reclosing it as someone could confirm that doing the steps I explained works fine. Everyone still having this problem needs to do them again.

**Comment by ghost** [comment]
> ```
> If you already opened a workspace, follow these steps:
>     1. Close your workspace and go inside your workspace's folder
>     2. Open in Notepad or another text editor the `.mcreator` file
>     3. Search `currentGenerator`, inside `workspaceSettings` and replace `fabric-1.17.1` by `fabric-1.16.5` (Install it!)
>     4. Save, close, re-open your workspace, and re-select Fabric 1.17.1```
> ```

Thank you!

**Comment by Rikurob** [comment]
Yeah this works, if you run it and get this error, and then follow these steps, run it as 1.16.5 first, then change it back to 1.17.1 and run it again the build is successful.

**Comment by Rikurob** [comment]
Actually It ran but I can't make anything without the build failing
![1234](https://user-images.githubusercontent.com/72680686/159851457-bb798f69-c7f1-4abe-a626-fcdccf2c2624.PNG)
Let me know if you want access to my workspace

**Comment by Rikurob** [comment]
Regenerate Code and Rebuild to fix this
