### ISSUE TITLE
[Bug] Setup Fail

### ISSUE THREAD

**Issue by Mystery-Kid** [Goldorion/MCreatorFabricGenerator#183]
After following your setup fix guide, I seem to still receive this issue:

Executing Gradle task: tasks
Build info: MCreator 2021.3.54000, fabric-1.17.1, 64-bit, 16315 MB, Windows 10, JVM 16.0.2, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk
 
> Configure project :
Fabric Loom: 0.10.66
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'valent'.
> Failed to provide loom:mappings:layered+hash.2192 : java.lang.RuntimeException: Could not find access widener file @ C:\Users\Myste\MCreatorWorkspaces\valent\src\main\resources\valent.accesswidener
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 5s
 
BUILD FAILED
Task completed in 5 seconds

**Comment by Goldorion** [comment]
FOllow them when after you got the error. I can assure you it fixes the problem.

**Comment by Mystery-Kid** [comment]
That is what I did, yet I still receive this error.

**Comment by Goldorion** [comment]
No, you did not. If you do steps correctly it works. I just tried again and it worked.

**Comment by Mystery-Kid** [comment]
Okay, I will retry and see if I made a mistake along the way.

**Comment by Mystery-Kid** [comment]
Yeah, I found out it was because of the ".txt" That was completely my fault.
