### ISSUE TITLE
[Bug] Advancements are granting when I put anything in my inventory

### ISSUE THREAD

**Issue by hydrangea72** [Goldorion/MCreatorFabricGenerator#187]
**Describe the bug**
So, I have 2 advancements called Biocube and Facepalm. To complete Biocube, you need to collect a blue star (flower). To complete the Facepalm achievement, you need to collect Palm Wood. But, upon collection of anything, even something like seeds or obsidian, it will grant me both advancements.

This is on 2021.3 with the latest fabric generator version

**To Reproduce**
Step 1: Make an advancement that triggers with a player obtaining an item/block.
Step 2: Load minecraft
Step 3: Put any block or item in your inventory
Step 4: Bug occurs

**Expected behavior**
Advancement works as normal, only triggering with the chosen block types.

**Additional context**
There is another achievement in my mod, that requires a player to visit a biome. That achievement works completely fine.

**Comment by Goldorion** [comment]
Please provide a minimal reproducible workspace.
