### ISSUE TITLE
[Request] Global Trigger Support for 1.17.1

### ISSUE THREAD

**Issue by hydrangea72** [Goldorion/MCreatorFabricGenerator#189]
**Describe the feature**
 I'm always frustrated when i can't make an advancement (the procedure is so that if you collect every type of flower added by my mod and in minecraft itself, you get the advancement)

**Describe why you want the feature**
I would like at least the "On player tick update" as that is the one I am using for the advancement.

**Comment by Goldorion** [comment]
Global triggers are based on the Forge's event systems. Fabric doesn't contain a lot of events currently. I added all possible events.

**Comment by AngelOfCreation** [comment]
> Global triggers are based on the Forge's event systems. Fabric doesn't contain a lot of events currently. I added all possible events.

Can't you just code your own events? If Fabric doesn't currently have a player tick event, why not make one yourself?

**Comment by Goldorion** [comment]
It's not that easy
