### ISSUE TITLE
[Bug] if I add a block to my mod, it makes an error

### ISSUE THREAD

**Issue by Axotay** [Goldorion/MCreatorFabricGenerator#191]
**Describe the bug**
I made a fabric mod in mcreator, and I added a block (there was nothing else in the mod except a creative tab), but the build failed ;w;

**Log**
https://pastebin.com/V4eAweAx

**Affected version(s)** fabric workspace version 0.37.1 - Minecraft version 1.16.5

**To Reproduce**
1. Create a fabric workspace with version 0.37.1, in minecraft 1.16.5.
2. Make a block (i named my block "carved oak planks").

**Expected behavior**
The block should not make an error happen

**Screenshots**
![image](https://user-images.githubusercontent.com/99088776/164046882-3c50aca5-ad70-46bb-8d19-9680ac0e0070.png)

**Additional context**
I made a creative tab before I made the block, so maybe that was why it broke, but idk, I removed the creative tab and it still didnt work :p

This is the workspace, idk if this is the right place to put it, idk where else it should go.
[oxygen_fabric.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/8514758/oxygen_fabric.zip)

**Comment by Goldorion** [comment]
Fabric 1.16.5 is not supported anymore. Please update to the latest version.
