### ISSUE TITLE
Asking 1.18.2???

### ISSUE THREAD

**Issue by ShadowEpix1** [Goldorion/MCreatorFabricGenerator#194]
This plugin is great! There are a few suggestions I can make:

1. Add 1.18.2 support. Not many people play fabric 1.17.1, and fabric always prioritizes the latest Minecraft version!
2. The mod creation part is great, but it would be nice to implement more procedures. It would be great if procedures could make its way into the “Partial Support (Almost Fully Supported)” area!
3. It would be nice if you could toggle fabric api. I know its essential for a good fabric mod, but for more simple things like recipes and advancements, I feel like an option for that would be nice.

Thank you to all the contributors who made this plugin. It is great to be able to create fabric mods in MCreator!

**Comment by Goldorion** [comment]
1. I am not Fabric and I am far from being as fast. I am alone to do everything, so it takes much more time.
2. Procedure blocks are almost all implemented. Only energy and fluid-related blocks are not implemented. Only triggers and global variables are missing. (Triggers need more support from Fabric)
3. `Data packs`
4. You did everything wrong with this ticket.
