### ISSUE TITLE
[Request] Support wait block in procedure creator

### ISSUE THREAD

**Issue by Slagof** [Goldorion/MCreatorFabricGenerator#195]
**Describe the feature**
Suport for the "Wait" procedure block.

**Describe why you want the feature**
For now i think Mcreator doesn't have any alternative for this, maybe making some world time based procedure, but its very complicated

**Additional context**
![Screenshot 2022-04-28 212040](https://user-images.githubusercontent.com/70154066/165871691-1f5eef65-9a51-4080-9cd1-3718d4ff3955.png)

**Comment by Goldorion** [comment]
It is currently impossible.
