### ISSUE TITLE
plugin doesn't load on Mcreator 2020.3

### ISSUE THREAD

**Issue by Nathan22211** [Goldorion/MCreatorFabricGenerator#2]
![2020-05-02](https://user-images.githubusercontent.com/35241068/80872015-edaf3900-8c74-11ea-8b93-836ec2e1fc65.png)
as you can see, the plugin is not showing up in the forge generator list

**Comment by Goldorion** [comment]
I know. It doesn't load with the new snapshot because Klemen has changed thing in the plugin format to allow my plugin inside a separte workspace type. I already fixed the problem, and I'm trying to fix majors bugs I have before update.

**Comment by smmmadden** [comment]
So what is the solution for this in 2020.3?  I've installed the plugin, fabric, fabric-api and I never see fabric as the generator listed in versions or have any options in a new workspace to select fabric.

**Comment by Goldorion** [comment]
I didn't update the plugin for the pre-release and the release, so it's normal that you can have some problems. I only need to fix a bug, and I will update the plugin.

**Comment by AshuraKuro** [comment]
Has this been fixed yet? Cause I'm having a similar issue, but instead of not seeing it in the generator selector, the plugin just isn't loading at all...
