### ISSUE TITLE
[Bug] Creating a custom entity with fabric generator

### ISSUE THREAD

**Issue by Hugo0272** [Goldorion/MCreatorFabricGenerator#201]
**Describe the bug**

When i was making my mod i decided to create an entity but when i added the model it gave me an error when i was trying to compile the mod

**Log**

https://www.toptal.com/developers/hastebin/wezukevotu.yaml

**Affected version(s)**  Mcreator 2022.1 

**To Reproduce**

1. Create a living entity
2. Add custom model
3. See error

**Expected behavior**
Normal entity that just moves around 

**Screenshots**

![entity create menu](https://user-images.githubusercontent.com/103284511/168109060-c6cf560e-cb87-445d-83c3-e03c593868ca.png)

![error](https://user-images.githubusercontent.com/103284511/168109504-8009f517-4c58-4435-bf1f-179d17c18ed0.png)

**Comment by Goldorion** [comment]
No workspace, no help.
