### ISSUE TITLE
[Request] Upgrade to 1.19

### ISSUE THREAD

**Issue by MrDexstor** [Goldorion/MCreatorFabricGenerator#206]
**Describe the feature**
I would like to be able to create Fabric mods for game version 1.19

**Describe why you want the feature**
Version 1.17 is already out of date and would like to get support for 1.19

**Comment by Goldorion** [comment]
I also don't talk Russian, so next time -> English.

**Comment by MrDexstor** [comment]
> I also don't talk Russian, so next time -> English.

I changed my request to English

**Comment by Goldorion** [comment]
Yes, but it's not a feature request. I'll do it when I will want. If you want it faster, just open PRs to update parts of the generator and I will gladly accept them.
