### ISSUE TITLE
[Bug] Error comes up about missing armor textures but I have all of the texture filled in

### ISSUE THREAD

**Issue by PossibleReference** [Goldorion/MCreatorFabricGenerator#208]
**Describe the bug**
Error comes up about my armor textures missing but I have all of the textures filled in

**Log**

**Affected version(s)** Release 1.6

**To Reproduce**
1. Go to 'Armor'
2. Click on 'Properties'
3. Fill in the armor texture

**Expected behavior**
For the armor to create normally

**Screenshots**
![image](https://user-images.githubusercontent.com/108957552/180717382-a82b579a-e6a4-4204-b492-c1afb011275f.png)
![image](https://user-images.githubusercontent.com/108957552/180717424-42ec4eba-5282-43db-9257-b980a8a2bc78.png)

**Additional context**
Armor is a big thing for extra ores

**Comment by Goldorion** [comment]
Please provide a minimal reproducible workspace and the mcreator.log file after this bug happened.

**Comment by PossibleReference** [comment]
Where do I find the mcreator.log file?

**Comment by Goldorion** [comment]
users/yours/.mcreator/logs

**Comment by PossibleReference** [comment]
[mcreator.log](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9205795/mcreator.log)
I will check what happens with the new version

**Comment by PhantomTimed** [comment]
https://github.com/Goldorion/Fabric-Generator-MCreator/issues/209
1.19.1 generator will not load

**Comment by Goldorion** [comment]
I was not able to reproduce it with the latest version.

**Comment by PossibleReference** [comment]
Got the latest snapshot working but the bug is still not fixed

**Comment by Goldorion** [comment]
You report a bug. I am not able to reproduce it and you do not help me. How can I fix the bug? So, you help me and you give me more info or you do not help me ans the bug is not fixed.

**Comment by PossibleReference** [comment]
Fixed, armor texture did not have a name
