### ISSUE TITLE
[Bug] 1.19.1 generator won't load

### ISSUE THREAD

**Issue by PossibleReference** [Goldorion/MCreatorFabricGenerator#209]
**Describe the bug**
The new beta generator for 1.19.1 will not load

**Log**
[Share mcreator.log in a paste website such as [Hastebin](https://hastebin.com/).
](https://www.toptal.com/developers/hastebin/ketulutupo.sql)
**Affected version(s)** Snapshot 1.7-beta1

**To Reproduce**
1. Simply just attempt to load the plugin

**Expected behavior**
The generator should load and work as intended

**Screenshots**
If applicable, add screenshots to help explain your problem

**Additional context**
Attempting to load a workspace will say the generator is missing, and I also do not have the old generator loaded!

**Comment by Goldorion** [comment]
You are not usi g the last snapshot

**Comment by PossibleReference** [comment]
Redownloaded the generator however it still does not load

**Comment by PossibleReference** [comment]
Fixed the issue

**Comment by ZacharyBachary** [comment]
how did you fix the issue

**Comment by PossibleReference** [comment]
Load it in the latest MCreator snapshot
