### ISSUE TITLE
Cannot load in to MCreator 2022.1.20510

### ISSUE THREAD

**Issue by thunderclaw09** [Goldorion/MCreatorFabricGenerator#213]
Whenever I click on "load plugin" and select it, nothing happens. I cannot create a workspace, as it still insists that I don't have a plugin for fabric installed. 

After I select the zip file, the "Apply" button remains greyed out. 

I checked the ".mcreator/plugins" folder in my user file (I'm running windows 10.) It appears there as a zip file but I still can't load it in. 

Please help, thank you.

**Comment by Goldorion** [comment]
This is normal. You nedd the second snapshot.

**Comment by thunderclaw09** [comment]
> This is normal. You nedd the second snapshot.

Could you please explain what you mean by that? I don't understand what kind of snapshot; I'm new to this. Sorry and thanks!

**Comment by Goldorion** [comment]
Use the second last 2022.2 snapshot.

**Comment by thunderclaw09** [comment]
> Use the second last 2022.2 snapshot.

Thanks so much! 

EDIT: I tried three versions, only 2022.2.31711 works. I'm putting it here for reference.

**Comment by Goldorion** [comment]
> EDIT: I tried three versions, only 2022.2.31711 works. I'm putting it here for reference.

This is the only one because I decided it would be this version minimally (to support the newest features).
