### ISSUE TITLE
[Bug] Biome Blocks are unselectable

### ISSUE THREAD

**Issue by PossibleReference** [Goldorion/MCreatorFabricGenerator#215]
**Describe the bug**
Biome Blocks while creating a custom biome are not able to be set

**Log**
Will send when needed as the bug is easy to recreate

**Affected version(s)** Snapshot 1.7-beta-3

**To Reproduce**
1. Load a workspace
2. Create a new biome
3. See that biome blocks are unselectable

**Expected behavior**
The underground block etc. to be selectable

**Screenshots**
![image](https://user-images.githubusercontent.com/108957552/181903223-3fcc5e7a-9e57-4d04-9ae4-e2352a3c858e.png)

**Additional context**

**Comment by Goldorion** [comment]
Describe the problem: You don’t read changelogs.
