### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by henwygaming** [Goldorion/MCreatorFabricGenerator#218]
### Issue description

Whenever I load the plugin in doesn't change anything in either the 'manage plugins' tab and it doesn't give me the option for fabric when creating a new workspace. I might be doing something wrong though, if so let me know.

### How to reproduce this issue?

I opened the preferences tab, went to the 'manage plugins' tab, loaded the generator, however after I loaded it, nothing appeared in 'manage plugins' or when creating a new workspace.

### Operating system

Windows

### Details

mcreator version: 2022.1
generator version: generator-fabric-1.19.1-1.7-beta-4

### Issue tracker rule checks (please read carefully)

- [x] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
You're blind, so put your glasses and read the page again.
