### ISSUE TITLE
[Request] See Minecraft's code

### ISSUE THREAD

**Issue by Paxnar** [Goldorion/MCreatorFabricGenerator#220]
**Describe the feature**
The ability to see Minecraft's code files, like MobRenderer

**Describe why you want the feature**
It would be easier to understand what methods are needed to be used

**Comment by Goldorion** [comment]
This is already possible. Also, this would be a MCreator bug.

**Comment by Paxnar** [comment]
Can you explain how to see it then?

**Comment by Goldorion** [comment]
It's the same way as you do with Forge, except the name is a bit different. The library should be under all the Fabric API libraries.

**Comment by Paxnar** [comment]
I was only able to find the minecraft-project library, but it's full of .class files that I am not able to open or read

**Comment by Goldorion** [comment]
> I was only able to find the minecraft-project library, but it's full of .class files that I am not able to open or read

This is the correct library. I can't do anything to allow the .class files to be inside the code editor. This is an MCreator thing. However, you can decompile the code using this Gradle task `genSourcesWithCfr` if you have an editor such as Intellij.

I will add this task to execute when MCreator setups the Gradle project to automatically decompile the code.
