### ISSUE TITLE
[Request] Support for 1.19.2

### ISSUE THREAD

**Issue by PossibleReference** [Goldorion/MCreatorFabricGenerator#224]
**Describe the feature**
1.19.2 has just released and I want the fabric generator to update to it, seeing as it updated to 1.19.1 when it first released

**Describe why you want the feature**
It will make mods work really well as some clients such as Feather Client support fabric mods for 1.19.1 but I use feather client and they completely removed 1.19.1 and replaced it with 1.19.2

**Additional context**
Example screenshot
![image](https://user-images.githubusercontent.com/108957552/183152818-7bd13c14-05ea-4601-b1fc-93fa2db22bc5.png)

**Comment by Goldorion** [comment]
Are you serious? It was released like less than a few hours ago... and my life is not the Fabric generator. I know this version exists.

**Comment by PossibleReference** [comment]
?
![image](https://user-images.githubusercontent.com/108957552/183159122-1a523065-3059-4b6e-84fa-2e92d04289f5.png)

**Comment by Paxnar** [comment]
> ? ![image](https://user-images.githubusercontent.com/108957552/183159122-1a523065-3059-4b6e-84fa-2e92d04289f5.png)

have patience

**Comment by PossibleReference** [comment]
he said it released a few hours ago?

**Comment by Paxnar** [comment]
Minecraft 1.19.2 was released a few hours ago, not the generator

**Comment by PossibleReference** [comment]
ah ok
