### ISSUE TITLE
Build error every time I build

### ISSUE THREAD

**Issue by PossibleReference** [Goldorion/MCreatorFabricGenerator#225]
### Issue description

Everytime I build my mod, there is a build error in the fabric.mod.json file which I am able to fix if it did not regenerate every time the project gets built

### How to reproduce this issue?

I am not currently able to reproduce the bug in a different workspace, I will instead attach my workspace with the bug

Screenshot of the error

![image](https://user-images.githubusercontent.com/108957552/183236879-fdd356ea-c006-462a-a457-69dcaa4fdc92.png)

### Operating system

Windows

### Details

MCreator version: 2022.2

### Example workspace

[build-error-workspace.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9274485/build-error-workspace.zip)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
You can't reproduce the issue, I can't test.

**Comment by PossibleReference** [comment]
I think i've gotten the issue down.
Any block that naturally generates gives this build error.
