### ISSUE TITLE
[Request] Wearable Items

### ISSUE THREAD

**Issue by Paxnar** [Goldorion/MCreatorFabricGenerator#226]
**Describe the feature**
Make items and blocks have an option to be wearable

**Describe why you want the feature**
It would be cool to make items similar to skulls, heads and pumpkins

**Additional context**
This can be done using `FabricItemSettings.equipmentSlot(EquipmentSlotProvider)` when registering an item

**Comment by Goldorion** [comment]
This is not the core.
