### ISSUE TITLE
[Bug] Naturally generating blocks causes a build error

### ISSUE THREAD

**Issue by PossibleReference** [Goldorion/MCreatorFabricGenerator#227]
### Issue description

This is a repost of https://github.com/Goldorion/Fabric-Generator-MCreator/issues/225 but I have figured out the cause of the issue.
Any block that naturally generates will cause a build error

### How to reproduce this issue?

Step 1: Make a block
Step 2: Go to Generation and choose a dimension
Step 3: Wait for it to build

### Operating system

Windows

### Details

MCreator version: 2022.2

### Example workspace

[generationbuilderror.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9275761/generationbuilderror.zip)

### Logs

Easily reproducable so I might include the log later

### Issue tracker rule checks (please read carefully)

- [x] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [x] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Paxnar** [comment]
you should provide log

**Comment by Goldorion** [comment]
It is surely the same problem as #229, which has been fixed in a recent commit. The fix will be provided with the next beta.
