### ISSUE TITLE
error: cannot find symbol  -  1.19.1-Fabric-Generator

### ISSUE THREAD

**Issue by Fisheiyy** [Goldorion/MCreatorFabricGenerator#229]
### Issue description

I cannot compile my mod with the latest version of the 1.19.1 generator beta, it gives me "error: cannot find symbol"

### How to reproduce this issue?

Regenerate code and build or try to Refactor workspace, both error out and fail.

### Operating system

Windows

### Details

MCreator Version: MCreator 2022.2.31711 EAP (31711) (latest snapshot)
Generator Version: fabric-1.19.1 (latest beta)

### Example workspace

https://mega.nz/file/fA9RmRpA#_zmVW6an-p0HEzPKd4pXkzQ8xx-EhUNkJQxEFnlYle4

### Logs

https://anotepad.com/notes/wpyjdnmb

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PossibleReference** [comment]
This is possibly due to the fact that you have a naturally generating block or have a biome, try making the block not naturally generate and remove all biomes. This relates to my bug: https://github.com/Goldorion/Fabric-Generator-MCreator/issues/227

**Comment by Fisheiyy** [comment]
> This is possibly due to the fact that you have a naturally generating block or have a biome, try making the block not naturally generate and remove all biomes. This relates to my bug: #227

yep naturally generating ores, no biomes though
