### ISSUE TITLE
Stair block base makes the game not loading

### ISSUE THREAD

**Issue by Goldorion** [Goldorion/MCreatorFabricGenerator#232]
### Issue description

When using the stair block base, the game will not load.

### How to reproduce this issue?

Stair block base

### Operating system

Windows

### Details

Master

### Logs

https://pastebin.com/1fbJuRiQ

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Night4-dev** [comment]
Having the same issue. hope it gets fixed soon
:)

**Comment by Goldorion** [comment]
> Having the same issue. hope it gets fixed soon :)

I'm trying to find the exact cause, so I can fix it.

**Comment by Night4-dev** [comment]
it says something about air in the console. maybe its the bounding boxes?

**Comment by Goldorion** [comment]
Yep, I noticed this. I try to figure out the fix.

**Comment by PossibleReference** [comment]
Also having this issue, we just have to be patient.

**Comment by Night4-dev** [comment]
found it yet?

**Comment by Goldorion** [comment]
Nope

**Comment by Night4-dev** [comment]
1 question. is it only you working on the bugs or?

**Comment by Goldorion** [comment]
the project

**Comment by Night4-dev** [comment]
How's it going?

**Comment by Goldorion** [comment]
Not fixed yet

**Comment by Night4-dev** [comment]
oooooofff

**Comment by mikeyward** [comment]
Just adding another +1. Pulling stairs out of my mod for now.
Is there anything we can do to help figure it out?

**Comment by Goldorion** [comment]
> Just adding another +1. Pulling stairs out of my mod for now. Is there anything we can do to help figure it out?

Honestly, I simply didn't know why it doesn't work using the current way, so if you are able to find a fix, it will help me.

**Comment by RedFoxLightning** [comment]
I'm honestly just kind of amused because I expected my entire project to be littered with errors when I changed it to fabric and the only thing that threw an error was the glass stairs lol

**Comment by Goldorion** [comment]
> I'm honestly just kind of amused because I expected my entire project to be littered with errors when I changed it to fabric and the only thing that threw an error was the glass stairs lol

I fixed a lot of issues since the beginning. However, this one doesn't want to be resolved xD

**Comment by mikeyward** [comment]
In all honesty, I'm ecstatic with your work, and super thankful that you've done this. The Tempered Glass mod I made with MCreator is something I've been wanting for ages, and this generator made it possible!

**Comment by Micasddsa** [comment]
I'm actually trying to find a workaround for this using custom models, hopefully.
So far it didn't work. Tried to use the Vanilla stair JSON model but you couldn't go up the stairs, collision like a full block.
I'll keep trying to see if I can find a workaround.
(You're free to tell me if it's not possible. Would save me time because I'm just learning models and stuff.)

**Comment by Micasddsa** [comment]
Ok, tried it out.
Would probably need a lot of commitment for this workaround. idk how connected stars would even work.
Guess like i'm in the waiting room for a fix.

**Comment by Night4-dev** [comment]
imagine the bug is an . in the code XD

**Comment by Micasddsa** [comment]
now with that, we only got feature requests. mostly forge features. hope they somehow get added!
I will go bug hunting now.

**Comment by mikeyward** [comment]
Huzzah! Great work, and thank you~!
