### ISSUE TITLE
Items disappearing from GUI when being shift-clicked. 

### ISSUE THREAD

**Issue by purejosh** [Goldorion/MCreatorFabricGenerator#236]
### Issue description

Shift clicking the result slot causes the result items to disappear AND causes any matching items in my inventory to disappear, whereas just grabbing them manually is fine. Using the 1.19.1 Fabric plugin made by Goldorion. 

### How to reproduce this issue?

I posted a video of the issue, showing it. If you need the procedure, I can send it. 
https://user-images.githubusercontent.com/70633949/183943357-7678c35d-ec7e-4f2d-b02a-2b9923f1b134.mp4

### Operating system

Windows

### Details

MCreator EAP 2022.2 b31711
generator-fabric-1.19.1

### Example workspace

[take_me_to_japan.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9301444/take_me_to_japan.zip)

I don't know if this is enough for you, but lmk if you need more. 

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by purejosh** [comment]
This also happens when you shift click items from your inventory while you have a GUI open... 

Really kind of a game breaking issue.

**Comment by purejosh** [comment]
Are there any updates on this? This is pretty major bug.

**Comment by PossibleReference** [comment]
I'm not sure he noticed it...

**Comment by Goldorion** [comment]
I’m not sure you know what is development and working on a FREE project, for FUN, on your FREE time, without getting ANYTHING back and so, for several years.
So I am sorry if I don’t do exactly everything you want when you want my king, but I did not find a solution yet and I wanted to release a beta to fix the other bugs already fixed...

You do not even pay one cent to use this project I work hours and days on it, so next time, learn the patience.

**Comment by purejosh** [comment]
Woah woah woah... I never meant to rush you, and I do run a server with barely any monetization. I understand what doing things in your free time is all about. I spend more time developing my server than I do at my career job. I didn't expect any immediate updates, especially for the amount of bugs I've reported. My intent was to know if you've ack'd this, or if you need more info or help. If you can't get to it now, it is what it is. 

And for what it's worth, I would easily and happily support you for this project. Fabric is the forgotten child of the modding world and I personally think that this project single handedly could help change that. Open a buymeacoffee and I'll prove my appreciation and respect for you.

**Comment by Goldorion** [comment]
@purejosh I was not talking to you. Everything you did was fine and totally understandable. In fact, I would want more people like you that report me bugs with a good issue report.
 I was talking to PhantomTimed that wrote a message a bit rude.

**Comment by purejosh** [comment]
Ohh, okay. That's good. I agree that their comment was not beneficial here. 

Thank you for everything! Also, I know that there's an "mcreator" focused donation, but I really do encourage you to open a buymeacoffee for yourself, for this plugin. I would love to support this project directly.

**Comment by PossibleReference** [comment]
> @purejosh I was not talking to you. Everything you did was fine and totally understandable. In fact, I would want more people like you that report me bugs with a good issue report. I was talking to PhantomTimed that wrote a message a bit rude.

I didn't mean to be rude, I was just getting a little impatient and yes, I do understand that you work for nothing in return and our free time is annoying. There is only 1 person helping me with my mod made with this, and it still is very hard. I like this project and how hard you work on it for us. Mistakes happen all the time.

**Comment by PossibleReference** [comment]
> Woah woah woah... I never meant to rush you, and I do run a server with barely any monetization. I understand what doing things in your free time is all about. I spend more time developing my server than I do at my career job. I didn't expect any immediate updates, especially for the amount of bugs I've reported. My intent was to know if you've ack'd this, or if you need more info or help. If you can't get to it now, it is what it is.
> 
> And for what it's worth, I would easily and happily support you for this project. Fabric is the forgotten child of the modding world and I personally think that this project single handedly could help change that. Open a buymeacoffee and I'll prove my appreciation and respect for you.

He also already has a similar thing at: https://ko-fi.com/goldorion

**Comment by purejosh** [comment]
Thank you SO MUCH! 😄

**Comment by Goldorion** [comment]
> Thank you SO MUCH! 😄

It required some work to find the fix, but here it is :D
