### ISSUE TITLE
Plugin not recognized by Mcreator

### ISSUE THREAD

**Issue by apkqiu** [Goldorion/MCreatorFabricGenerator#239]
### Issue description

_I'm from China and I got English using Google Translate, so there may be grammatical errors or wrong usage of words. Please understand._

I downloaded and installed the plugin, but in the "New Workspace" dialog the "Minecraft Fabric Mods" button is greyed out, and when clicked it shows a dialog similar to "There are currently no plugins for this generator type installed"

Below is Chinese: 
我下载并安装了这个插件，但是在“新建工作区”对话框里“Minecraft Fabric 模组”按钮是灰色的，点击后显示类似于“目前没有安装此生成器类型的插件”对话框。

### How to reproduce this issue?

I have done the following

1. Open Mcreator
2. Open Preferences
3. Under "Manage Plugins" click "Load Plugins..."
4. Restart Mcreator
5. Click on "New Workspace"

After performing the above operations, it is found that in the "New Workspace", the "Minecraft Fabric Mod" button is grayed out

Below is Chinese: 

1. 打开 Mcreator
2. 打开偏好设置
3. 在“管理插件”页面中点击“加载插件…”
4. 重启 Mcreator
5. 点击“新建工作区”

执行完以上操作后发现：在“新建工作区”内，“Minecraft Fabric 模组”按钮是灰色的

### Operating system

Windows

### Details

Windows 10 Family Chinese, Version 21H2 (19044.1620) 

Mcreator 2022.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
2022.2...
(and I don't talk Chinese)
