### ISSUE TITLE
Global trigger "Player uses item" is using Forge code and you cannot use it in procedures due it not compiling

### ISSUE THREAD

**Issue by EugeneHordei** [Goldorion/MCreatorFabricGenerator#240]
### Issue description

Using it on Forge doesn't come with any problems and it is working fine without any compiling errors. The error code is
C/blahblahblah/ error: cannot find symbol 
         return InteractionResult.pass(player.getItemInHand(hand)); 
                                              ^ 
  symbol:   method pass(ItemStack) 
  location: class InteractionResult 
1 error 
> Task :compileJava FAILED

### How to reproduce this issue?

1. Create a procedure
2. Select "Player uses item" as a global trigger"
3. Try to save it

### Operating system

Windows

### Details

MCreator version: 2022.2 31711
Generator: Fabric 1.19.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
This trigger is not supported by the generator currently.
