### ISSUE TITLE
Adding world type causes build error

### ISSUE THREAD

**Issue by SoYeahImAGamer** [Goldorion/MCreatorFabricGenerator#242]
### Issue description

Adding a world type to structure spawning or block / plant generation causes a build error

### How to reproduce this issue?

step 1: create structure
step 2: select the dimension for the structure to spawn in
step 3: save element
step 4: build error
pretty much the same thing with any mod element that you'd select a dimension to spawn in

### Operating system

Windows

### Details

MCreator Version: 2022.2
Fabric Generator 1.17-beta-5-1.19.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
It has already been reported and it will be fixed in the next beta.
