### ISSUE TITLE
creating a structure withe the fabric generator plugin version 1.19.1 breaks the code

### ISSUE THREAD

**Issue by TheClansTwo** [Goldorion/MCreatorFabricGenerator#244]
### Issue description

here is the log

Executing Gradle task: build 
Build info: MCreator 2022.2.34517, fabric-1.19.1, 64-bit, 16265 MB, Windows 11, JVM 17.0.3, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2022-08-21-02:40:34 
  
> Configure project : 
Fabric Loom: 0.12.56 
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> Task :compileJava FAILED 
[C:\Users\tomma\MCreatorWorkspaces\gasperitoss_betternether\src\main\java\net\mcreator\gasperitossbetternether\init\GasperitossBetternetherModFeatures.java:26](file:///C:/Users/tomma/MCreatorWorkspaces/gasperitoss_betternether/src/main/java/net/mcreator/gasperitossbetternether/init/GasperitossBetternetherModFeatures.java:26): error: cannot find symbol 
      Registry.register(Registry.FEATURE, new ResourceLocation(Fabric119Mod.MODID, registryName), feature); 
                                                               ^ 
  symbol:   variable Fabric119Mod 
  location: class GasperitossBetternetherModFeatures 
[C:\Users\tomma\MCreatorWorkspaces\gasperitoss_betternether\src\main\java\net\mcreator\gasperitossbetternether\init\GasperitossBetternetherModFeatures.java:28](file:///C:/Users/tomma/MCreatorWorkspaces/gasperitoss_betternether/src/main/java/net/mcreator/gasperitossbetternether/init/GasperitossBetternetherModFeatures.java:28): error: cannot find symbol 
            ResourceKey.create(Registry.PLACED_FEATURE_REGISTRY, new ResourceLocation(Fabric119Mod.MODID, registryName))); 
                                                                                      ^ 
  symbol:   variable Fabric119Mod 
  location: class GasperitossBetternetherModFeatures 
[C:\Users\tomma\MCreatorWorkspaces\gasperitoss_betternether\src\main\java\net\mcreator\gasperitossbetternether\world\features\ArenaFeature.java:45](file:///C:/Users/tomma/MCreatorWorkspaces/gasperitoss_betternether/src/main/java/net/mcreator/gasperitossbetternether/world/features/ArenaFeature.java:45): error: cannot find symbol 
         .includeByKey(ResourceKey.elementKey(Registry.BIOME_REGISTRY).apply(new ResourceLocation("crimson_forest"))); 
                                  ^ 
  symbol:   method elementKey(ResourceKey<Registry<Biome>>) 
  location: class ResourceKey 
3 errors 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 3s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 5 seconds

### How to reproduce this issue?

Step 1: create a structure
Step 2: save mod element
Step 3: done

### Operating system

Windows

### Details

Mcreator 2022.2
Fabric Generator 1.19.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
It has already been reported and it will be fixed in the next beta.
