### ISSUE TITLE
structure biome restriction causing errors

### ISSUE THREAD

**Issue by Lazality** [Goldorion/MCreatorFabricGenerator#245]
### Issue description

When creating a structure, adding a biome restriction will cause it to fail and not compile.

I am unaware as to why this is happening. Hoping it will be fixed. No rush of course! :D

Update: So it seems this happens with most elements when adding a biome restriction.

### How to reproduce this issue?

Step 1. Make a structure
Step 2. Add a biome restriction

![image](https://user-images.githubusercontent.com/111811209/186027525-2a3051a7-67f6-4d9c-948a-7a5b8d65c33a.png)
This is what should happen

### Operating system

Windows

### Details

MCreator version 2022.2
Fabric Generator 1.7-beta-6

### Logs

Build info: MCreator 2022.2.33511, fabric-1.19.2, 64-bit, 16331 MB, Windows 10, JVM 17.0.3, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2022-08-22-18:11:46
 
> Configure project :
Fabric Loom: 0.12.56
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix.
> Task :compileJava
C:\Users\Xalit\MCreatorWorkspaces\ark_mod_two\src\main\java\net\mcreator\brokenarktwo\world\features\ArkTreeBigFeature.java:45: error: cannot find symbol   .includeByKey(ResourceKey.elementKey(Registry.BIOME_REGISTRY).apply(new ResourceLocation("broken_ark_two:ark_woods")));
     ^
 symbol: method elementKey(ResourceKey<Registry<Biome>>)
 location: class ResourceKey
1 error
> Task :compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 4s
1 actionable task: 1 executed
 
BUILD FAILED
Task completed in 1 minute and 15 seconds

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Hir0shiyt** [comment]
This is just the same that's happening to me
