### ISSUE TITLE
Tool Glowing Effect causes Compilation Error

### ISSUE THREAD

**Issue by jozzo402** [Goldorion/MCreatorFabricGenerator#246]
### Issue description

Adding the enchanted glow effect to a tool causes the tool to error out when compiled. Removing the glow effect will allow it to compile again.

![image](https://user-images.githubusercontent.com/11382131/186231792-dc7a4cd1-0387-4c4d-b443-b72910d7ffa2.png)

This only happens with Tools, adding a glowing effect the same way to Items or Ranged Items causes no issues.

I have tried clearing the gradle cache, updating MCreator to latest, and updating this plugin to latest but the problem still happens regardless.

### How to reproduce this issue?

Step 1. Make a new Tool or edit an old one
Step 2. Tick the "Enable glowing effect" box on the first page (Visual tab)
Step 3. Save the Tool

### Operating system

Windows

### Details

MCreator 2022.1 & 2022.2
generator-fabric-1.19.1 & generator-fabric-1.19.2 - 1.7-beta 6

### Logs

```
> Task :compileJava FAILED 
(<<path\to\workspace>>\item\SwordZephyrItem.java:12): error: a type with the same simple name is already defined by the single-type-import of Environment 
import net.fabricmc.api.Environment; 
^ 
(<<path\to\workspace>>\item\SwordZephyrItem.java:45): error: reference to Environment is ambiguous 
   @Environment(EnvType.CLIENT) 
    ^ 
  both enum net.minecraft.util.profiling.jfr.Environment in net.minecraft.util.profiling.jfr and class net.fabricmc.api.Environment in net.fabricmc.api match
```

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PossibleReference** [comment]
You are able to manually delete those lines and it'll work as expected.
