### ISSUE TITLE
Block Update Tick Rate Error

### ISSUE THREAD

**Issue by CristalGaming** [Goldorion/MCreatorFabricGenerator#247]
### Issue description

the bug occurs for the block elements and i think the problems is with update tick rate. the update tick rate was set to 1. i tried to set one of the blocks that get an error update tick rate from 1 to 0 but it didn't work.

### How to reproduce this issue?

so i created a copy of my forge workspace and i open it. both workspace was on the mcreator 2022.2 pre-release version. i wanted to test if i could make a fabric version of the mod at least with a part of the features . so i converted it into a fabric version and i removed any unsupported feature (like global variables, dimensions, etc... ) but after i delete any unsupported feature i get this error. i give up and i deleted the copy.

 i waited until the 1.7-beta-6 version of fabric when support for 1.17.2 appeared so i decided to try the same thing (i created a copy, deleted the unsupported stuff etc.). the workspace is on the release 2022.2. but still it give me the same error. so i decided to report this bug here.

### Operating system

Windows

### Details

MCreator 2022.2.34517 
fabric-1.19.2, 64-bit 
RAM: 7985 MB 
OS: Windows 10
JVM 17.0.3

  

### Example workspace

The Workspace is too big to upload. is has 1100+ elements.  i would like to upload it but the Workspece is almost 16x bigger than the limit.

### Logs

https://pastebin.com/qi25mC4b

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Please use Pastebin or another website for logs (or insert it as a file)

**Comment by CristalGaming** [comment]
done @Goldorion

**Comment by CristalGaming** [comment]
@Goldorion still didn't work even after 1.7 beta-7.

[puzzle jump fabric error.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9432245/puzzle.jump.fabric.error.zip)

_(i managed to put the workspace here... i just had to export without the run dir... i feel stupid now)_

**Comment by Goldorion** [comment]
Provide a minimal reproducible workspace

**Comment by CristalGaming** [comment]
ok this is weird... i tried to recreate the bug in a workspace but the GUI to gives me error but it doesn't in the workspace. i tried to delete the non relevant element and to keep the blocks with error but after i deleted a big part of the elements the test workspace don't say anymore that the blocks are the problem but it says that is the GUI is the problem. i kinda want to give up 🙃.

**Comment by CristalGaming** [comment]
@Goldorion I couldn't reproduce the workspace other than making a copy of the workspace and deleting elements. now it only have 43 elements. _(i can make it smaller if you want)_

[puzzle jump fabric error.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9437592/puzzle.jump.fabric.error.zip)

there are other problems too like the gui and the NBT tags but for now i want at least the block to work.
