### ISSUE TITLE
New project creation failed

### ISSUE THREAD

**Issue by EGSP** [Goldorion/MCreatorFabricGenerator#248]
### Issue description

When using the fabric generator with version 1.19.2, the new project is not initialised. When using the current forge generator, for 1.18, everything works. 

### How to reproduce this issue?

Create new project with MCreator 2022.2 and Fabric generator 1.7 beta 6

### Operating system

Windows

### Details

MCreator version: 2022.2.34517
Fabric Generator: 1.7 beta 6

### Logs

https://gist.github.com/EGSP/2f31d19c095e2c8bb85ff55818a6e52b
[message (2).txt](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9417696/message.2.txt)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Santes13** [comment]
I have exactly the same problem. It's really annoying that I can't start making mods. :(((((((((((((((((((((((((((((((

**Comment by dgeicops** [comment]
I've been having this problem for a few days

**Comment by Goldorion** [comment]
I will need more info about the bug because I just tried and it worked fine for me.
Maybe try to restart the project set up when the error occurs.

**Comment by EGSP** [comment]
I have installed MCreator 2022.2 with generator 1.7-beta6 on a work computer with Intellij IDEA installed. Everything ran and built fine. 

So there is probably some step, not specified in the documentation, to install all the necessary tools, environment.

**Comment by Goldorion** [comment]
> I have installed MCreator 2022.2 with generator 1.7-beta6 on a work computer with Intellij IDEA installed. Everything ran and built fine.
> 
> So there is probably some step, not specified in the documentation, to install all the necessary tools, environment.

I always use MCreator with Intellij installed as we are using it for MCreator's development and I also use it for developing in general in java and my plugins, so this is not the issue.

**Comment by EGSP** [comment]
Then we can close this issue
