### ISSUE TITLE
Walls turned to black and purple box when connected to blocks

### ISSUE THREAD

**Issue by Lazality** [Goldorion/MCreatorFabricGenerator#249]
### Issue description

When you connect a wall to some sort of block it turns into the purple and black box,

This is what should happen
![bug](https://user-images.githubusercontent.com/111811209/186497970-fc339454-c38d-4dba-b348-1f702b654a86.png)
.

That box is the wall

### How to reproduce this issue?

Step 1. Make a wall
Step 2. Connect to block

### Operating system

Windows

### Details

MCreator 2022.2
Fabric generator 1.19.2 1.7-beta-6

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I tested to create a custom wall and I added it to the tag and it worked fine.
