### ISSUE TITLE
Archives of older versions

### ISSUE THREAD

**Issue by Blazejou** [Goldorion/MCreatorFabricGenerator#250]
**Describe the feature**
It would be nice to have an option to do fabric mods on older versions like 1.17 or 1.16 im pretty sure im not the only one that want that feature

**Describe why you want the feature**
So i could do a mod for mine and my friend's mnecraft server and also for singleplayer

**Additional context**
yeah so please add it, but im not forcing you

**Comment by Blazejou** [comment]
sorry for sh*tty english but Im not the best at it

**Comment by Goldorion** [comment]
Check the release page.
