### ISSUE TITLE
Game crashes on world load when setting a custom sound for a custom entity

### ISSUE THREAD

**Issue by CoNesTra** [Goldorion/MCreatorFabricGenerator#251]
### Issue description

The game will always crash on world load when adding a custom living sound to an custom entity.

### How to reproduce this issue?

Step 1: Create a new workspace.
Step 2: Import 3 ogg files into a sound.
Step 3: Create a new custom entity.
Step 4: Add the sound into the living sound field.
Step 5: Save and run the game.
Step 6: Create a new world, and the game will crash on load.

### Operating system

Windows

### Details

MCreator 2022.2, Fabric Generator 0.59.0

### Logs

Log:
https://pastebin.com/y8dtaLzL

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by CoNesTra** [comment]
@Goldorion Is there a solution to this problem, or is it planned to be fixed? Just wondering why this was closed.

**Comment by Goldorion** [comment]
Update your plugin version.

By the way, wanting to ping is totally unnecessary (and makes you look totally impatient).

**Comment by CoNesTra** [comment]
Sorry, I tried to ask on here, but the ticket was closed. Thanks!

**Comment by CoNesTra** [comment]
> Update your plugin version.

The plugin is on it's most recent version, 1.7-beta-7.

**Comment by Goldorion** [comment]
> > Update your plugin version.
> 
> The plugin is on it's most recent version, 1.7-beta-7.

You didn't specify it, so I thought you were still using an old version.

**Comment by CoNesTra** [comment]
> You didn't specify it, so I thought you were still using an old version.

My bad, I should have in the first place. I'll remember to do so in the future.

**Comment by Goldorion** [comment]
I just tested and it worked fine.
