### ISSUE TITLE
Compiling issue with Resource Location

### ISSUE THREAD

**Issue by hydrangea72** [Goldorion/MCreatorFabricGenerator#255]
### Issue description

Any feature (such as a flower, ore, structure, etc) will not compile when MC is loaded. The following issue is as follows:
![Screen Shot 2022-08-31 at 7 20 48 PM](https://user-images.githubusercontent.com/63913368/187801855-3c93ac46-2555-4f73-bdaf-4dffc247f37c.png)

### How to reproduce this issue?

Step 1: Make a new element that generates a feature, set it to spawn in any specific biome.
Step 2: Error

### Operating system

macOS

### Details

Latest Fabric gen

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Update your plugin to the latest version. It has already been fixed.

**Comment by hydrangea72** [comment]
Ah, sorry.
