### ISSUE TITLE
[Request] Add support for Entity Attacked

### ISSUE THREAD

**Issue by Someone68** [Goldorion/MCreatorFabricGenerator#257]
**Describe the feature**
The feature Entity Attacked for the procedure blocks. People could make lifesteal enchantments and stuff.

**Describe why you want the feature**
I really wanted to make a lifesteal enchantment, but I always remember: Entity Attacked is not supported. Please add support for it as more people could make better enchantments.

**Additional context**
nothing

**Comment by PrahladhGaming** [comment]
noonno

**Comment by NerdyPuzzle** [comment]
#308
