### ISSUE TITLE
[REQUEST] Support for 1.16

### ISSUE THREAD

**Issue by BoogieMonster1O1** [Goldorion/MCreatorFabricGenerator#26]
**Describe the feature**
1.16 is coming nearer and nearer and it's time we update MCreatorFabricGenerator to it

**Describe why you want the feature**
No alternative solutions exist.

**Additional context**
It's best to wait until 1.16.1 or a server friendly release comes out.

**Comment by BoogieMonster1O1** [comment]
Set to be done for 0.7.0

**Comment by CrispyChips6660** [comment]
why did you close and reopen it XD

**Comment by BoogieMonster1O1** [comment]
Done, but not done!
