### ISSUE TITLE
Enabling Melee Damage on a Ranged Item causes the Ranged Item not to compile.

### ISSUE THREAD

**Issue by Micasddsa** [Goldorion/MCreatorFabricGenerator#261]
### Issue description

The Title Says it all.
It says something about not finding a Symbol "Multimap"
Assuming from the java code. It contains the Attack Damage and Attack Speed values. Deleting the entire method causes no stats to appear, so it's probably an issue with the generator misinterpreting something about the Melee Damage Toggle.
(Example Workspace provided for testing.)

### How to reproduce this issue?

Step 1: Make a ranged item.
Step 2: Enable Melee Damage
Step 3: Add any item as ammo.
Step 4: Compile.

### Operating system

Windows

### Details

MCreator Version: 2022.2.33511 
Generator Version: fabric-1.19.2 beta 6

### Example workspace

[rangedweapontest.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9501618/rangedweapontest.zip)

### Logs

```
Executing Gradle task: build 
Build info: MCreator 2022.2.33511, fabric-1.19.2, 64-bit, 16332 MB, Windows 10, JVM 17.0.3, JAVA_HOME: C:\Program Files\Pylo\MCreator2022.2\jdk, started on: 2022-09-06-17:06:58 
  
> Configure project : 
Fabric Loom: 0.12.56 
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> Task :compileJava 
C:\Users\Micasddsa\MCreatorWorkspaces\rangedweapontest\src\main\java\net\mcreator\rangedweapontest\item\RangedMeleeItem.java:47: error: cannot find symbol 
   public Multimap<Attribute, AttributeModifier> getDefaultAttributeModifiers(EquipmentSlot slot) { 
          ^ 
  symbol:   class Multimap 
  location: class RangedMeleeItem 
1 error 
> Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 9s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 14 seconds
```

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
It's a missing import. Add the following import with the others `import com.google.common.collect.Multimap;`. I will fix it in the next patch.

**Comment by Goldorion** [comment]
This bug has been fixed in the latest version. Please update the version of the plugin you use.

**Comment by Micasddsa** [comment]
huh, beta 7 and 8 aren't on the releases page here...
glad my issue was still valid, I guess.

**Comment by Goldorion** [comment]
Check on the plugin page of MCreator.

**Comment by Micasddsa** [comment]
yea I did. it works now.
