### ISSUE TITLE
When making food item, if it has a "Eating item result" mod will not compile

### ISSUE THREAD

**Issue by Lazality** [Goldorion/MCreatorFabricGenerator#263]
### Issue description

As the title says, if you make a food item and add an eating item result, your mod will not compile.

As i was testing for a custom potion item using food properties.

### How to reproduce this issue?

1. Make food item
2. Add eating item result
3. Save

### Operating system

Windows

### Details

MCreator 2022.2
Fabric Gen 1.7-beta-7

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I re-saved the mod element and it fixed the problem.
