### ISSUE TITLE
Not possible to use replace block on Fabric 1.19.2-beta8

### ISSUE THREAD

**Issue by purejosh** [Goldorion/MCreatorFabricGenerator#265]
### Issue description

Essentially, I'm trying to create a bonemeal procedure. This procedure causes a flash of the block to change, and reverts back. I've been told this is because it's running on the client and not the server, but using the "is not is provided world remote" simply breaks the procedure entirely. 
![image](https://user-images.githubusercontent.com/70633949/190522326-ae449928-50f8-4cb0-98b7-22cf931c5eaa.png)
https://user-images.githubusercontent.com/70633949/190522577-1bdc7042-23bd-4a7c-90c1-23be877155a6.mp4

So, I decided to cut the fluff and see if it's something with my procedure. I made the following: 
![image](https://user-images.githubusercontent.com/70633949/190522825-2bac7814-5873-4edb-8d51-3688b948a268.png)
and the result is: 
https://user-images.githubusercontent.com/70633949/190522855-390b0ae2-17c7-45d8-9624-405ca2513ae1.mp4

Fearing that this is just something that's buggy with the Fabric generator, I asked someone who uses this on Forge to make the same procedure, and it worked for them. 

I've tried both of the following procedure blocks, in many formats, and there have been no good results: 
![image](https://user-images.githubusercontent.com/70633949/190523054-ed4576f1-96c6-40da-838a-b2642e165b61.png)

If I'm doing it wrong, so be it, I'll just need to learn how to do it right. But I'm pretty convinced there could be a bug with this. 

### How to reproduce this issue?

I put all my details above. Oops. 

### Operating system

Windows

### Details

MCreator 2202.2
Fabric Generator 1.7-beta-8

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
You need to use the `(not) is provided world remote (client-side)`. This way, the server and the client always have the same number. Currently, you don't check it, meaning the client will generate a random number, but the server will also generate another random number.
When you just use the Replace block with a trigger, you can notice it works fine.

**Comment by purejosh** [comment]
The following: 
![image](https://user-images.githubusercontent.com/70633949/190861428-90b9fbfc-fa97-44e6-988a-d8566f406e78.png)
...does work, however it replaces the block under the player, not the block that I've right clicked. 

This setup: 
![image](https://user-images.githubusercontent.com/70633949/190861505-7a76486a-703f-41e2-afe8-17bc899e6151.png)
![image](https://user-images.githubusercontent.com/70633949/190861521-ab1ee44b-47a0-458d-bf64-6f0342029b76.png)
...causes this to happen:
https://user-images.githubusercontent.com/70633949/190861561-484f0ae7-02b3-4088-ac2d-068150caa98f.mp4

And this setup:
![image](https://user-images.githubusercontent.com/70633949/190861651-8569ca86-3e15-4c33-87a8-bffa11b5ae6c.png)
...results in no actions, visual or otherwise, in the world. 

I'm not sure what else I could be doing wrong, but I feel like with the combinations I've tried so far, something should have worked. At this point, I'm simply unable to get a simple block replace to work correctly, but I will remember the point you've made about random being generated on client and server.

**Comment by purejosh** [comment]
I'll be available any time, if you want to do a session over Discord, as well. If you have the time for that, of course.

**Comment by Goldorion** [comment]
> ...does work, however it replaces the block under the player, not the block that I've right clicked.
You need to use the provided dependencies as the x, y and z are the player's coordinates.

**Comment by Goldorion** [comment]
> And this setup:
![image](https://user-images.githubusercontent.com/38427877/190861896-61ddae31-5ec9-468f-a276-3d6680ea54da.png)
...results in no actions, visual or otherwise, in the world.

You don't need to check for the client side here.

**Comment by purejosh** [comment]
> > ...does work, however it replaces the block under the player, not the block that I've right clicked.

> You need to use the provided dependencies as the x, y and z are the player's coordinates.

I'm sorry to ask, but is there a guide on that? And again, I appreciate your assistance on this. It's been driving me insane.

**Comment by Goldorion** [comment]
> > > ...does work, however it replaces the block under the player, not the block that I've right clicked.
> 
> > You need to use the provided dependencies as the x, y and z are the player's coordinates.
> 
> I'm sorry to ask, but is there a guide on that? And again, I appreciate your assistance on this. It's been driving me insane.

Yes, the hundreds of NWT's tutorials

**Comment by purejosh** [comment]
I've tried this very procedure in both fabric and forge. 
![image](https://user-images.githubusercontent.com/70633949/190865746-860cc2b7-dc00-4c66-956a-e9bbf31d2191.png)

In forge, it works normally. I can bone meal it from anywhere, and it'll grow where expected. 
In fabric, I'm required to stand on it so the checks can pass for that block at x y z. 

Every NWT tutorial I've tried is on Forge. So, using his tutorials won't help, if there's a discrepancy between these versions. And I've tried many. 

I'm providing a copy of my project, so you can test on your end. 
crops > GreenTea > ProcedureGreenTeaBoneMeal0
[take_me_to_japan_fabric.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9592103/take_me_to_japan_fabric.zip)
