### ISSUE TITLE
Gui based Procedures all fail

### ISSUE THREAD

**Issue by CasterMx13** [Goldorion/MCreatorFabricGenerator#266]
### Issue description

When attempting to make a procedure that opens a gui it does not compile. 
Searched for ages about this issue and couldn't find anything.
I've tried rebuilding my workspace from scratch, and I've also deleted my gradle cache folder but the issue persists.

(First time writing an issue on github, sorry if this isn't descriptive enough. I'm also pretty new to this)

### How to reproduce this issue?

Create Gui

Create new procedure, build as follows:

Event trigger
v
Open Screen for -Event/target entity- pass location x -x- y -y- z -z- Gui: -Any Gui-

Press Save mod element

Get Error

### Operating system

Windows

### Details

Mcreator Version 2022.2
Generator type: Fabric 1.19.2 - 0.59.0

### Example workspace

[GuiProcedureError.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9603119/GuiProcedureError.zip)

### Logs

Executing Gradle task: build 
Build info: MCreator 2022.2.34517, fabric-1.19.2, 64-bit, 32689 MB, Windows 10, JVM 17.0.3, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2022-09-19-19:39:52 
  
> Configure project : 
Fabric Loom: 0.12.56 
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> Task :compileJava FAILED 
[C:\Users\Caster\MCreatorWorkspaces\guifailexample\src\main\java\net\mcreator\guifailexample\procedures\GuiErrorProcedure.java:57](file:///C:/Users/Caster/MCreatorWorkspaces/guifailexample/src/main/java/net/mcreator/guifailexample/procedures/GuiErrorProcedure.java:57): error: cannot find symbol 
            NetworkHooks.openGui((ServerPlayer) _ent, new MenuProvider() { 
            ^ 
  symbol:   variable NetworkHooks 
  location: class GuiErrorProcedure 
1 error 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 2s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 8 seconds

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by purejosh** [comment]
I have a working GUI based procedure on a block. Let me download your project and change some things.
