### ISSUE TITLE
Setting "Drop amount:" to 0 causes build to fail

### ISSUE THREAD

**Issue by purejosh** [Goldorion/MCreatorFabricGenerator#267]
### Issue description

If I set the "Drop amount:" to 0 on a block, it fails to compile. 

### How to reproduce this issue?

If I set the following on a crop block, including the "Drop amount:" to 0: 
![image](https://user-images.githubusercontent.com/70633949/191418987-6d11b15e-6c0f-439b-8c82-f1e56464cd19.png)

I receive the following error: 
```
Executing Gradle task: build 
Build info: MCreator 2022.2.34517, fabric-1.19.2, 64-bit, 32697 MB, Windows 10, JVM 17.0.3, JAVA_HOME: C:\Users\purejosh\.mcreator\MCreator20222\jdk, started on: 2022-09-20-23:07:50 
  
> Configure project : 
Fabric Loom: 0.12.56 
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> Task :compileJava FAILED 
/sweetberryfoods/block/BlueberryBushStage0Block.java:22): error: cannot find symbol 
         .noCollission().speedFactor(0.4f).jumpFactor(0.6f).noOcclusion().isRedstoneConductor((bs, br, bp) -> false).noDrops(); 
                                                                                                                    ^ 
  symbol:   method noDrops() 
  location: class Properties 
1 error 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 1s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 2 seconds
```

### Operating system

Windows

### Details

MCreator 2022.2.34517, fabric-1.19.2 generator 1.7-beta-8

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by purejosh** [comment]
Thank you!!

**Comment by Goldorion** [comment]
> Thank you!!

You're welcome. I didn't have much time lately, but I finally had free time today.
