### ISSUE TITLE
Procedure for obtaining and storing an entity's nbt data

### ISSUE THREAD

**Issue by CasterMx13** [Goldorion/MCreatorFabricGenerator#270]
**Describe the feature**
What I'm after is a procedure block that obtains an entity's nbt data and stores it; ex. A zombie wearing a helmet with x health remaining.

**Describe why you want the feature**
Multiple mod ideas of mine require knowing an entity's nbt data to function properly.

**Additional context**
It would just be super helpful, I feel like it would be rough to implement though. I've searched around for about an hour and couldn't find any built-in solutions.

**Comment by Goldorion** [comment]
It's a Forge feature (sadly)

**Comment by CasterMx13** [comment]
Ahh, that means it's impossible for fabric? Damn. Thanks for the reply \m/
