### ISSUE TITLE
Structures won't work at all

### ISSUE THREAD

**Issue by Hir0shiyt** [Goldorion/MCreatorFabricGenerator#271]
### Issue description

I'll just resume the issue
When you make a structure, everything is good until you add restriction for biomes, here's the log:
`Executing Gradle task: runClient
Build info: MCreator 2022.2.34517, fabric-1.19.2, 64-bit, 7885 MB, Windows 11, JVM 17.0.3, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2022-09-22-17:55:12
 
> Configure project :
Fabric Loom: 1.0.7
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix.
> Task :compileJava FAILED
C:\Users\Hiros\MCreatorWorkspaces\tcands_ii_fabric\src\main\java\net\mcreator\tcandsiifabric\TcandsIiFabricMod.java:35: error: cannot find symbol  TcandsIiFabricModBrewingRecipes.load();
  ^
 symbol: variable TcandsIiFabricModBrewingRecipes
 location: class TcandsIiFabricMod
1 error
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 2s
1 actionable task: 1 executed
 
BUILD FAILED
Task completed in 4 seconds`

### How to reproduce this issue?

1. Create a structure
2. Put biome restriction and save the thing
3. There is the issue

### Operating system

Windows

### Details

Mcreator 2022.2
Fabric 1.19.2 - 0.60.0
Latest Version of the plugin for Mcreator

### Example workspace

[Shareable_workspace.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9629881/Shareable_workspace.zip)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
it is not related to structures. Try to regenerate the code. I got the same error, but I never found the cause (due to brewing stand recipes).

**Comment by Hir0shiyt** [comment]
first of all, i've tried and it just wont work, it regens and then the message appears back again
second of all what info do you need?
