### ISSUE TITLE
[Bug] Is this bug? | Compilation error

### ISSUE THREAD

**Issue by SembleGit** [Goldorion/MCreatorFabricGenerator#272]
### Issue description

When I make a recipe and start compiling for testing, an error pops up and I can't compile.

### How to reproduce this issue?

Step 1:Creating any recipe
Step 2:Compile for testing
Step 3:Compilation Error

### Operating system

Windows

### Details

Executing Gradle task: build 
Build info: MCreator 2022.2.34517, fabric-1.19.2, 64-bit, 8134 MB, Windows 10, JVM 17.0.3, JAVA_HOME: F:\MCreator\jdk, started on: 2022-09-24-02:49:55 
  
  
BUILD FAILED 
Task completed in 4 seconds 
  
> Configure project : 
Fabric Loom: 1.0.7 
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> Task :compileJava FAILED 
[F:\workspace\src\main\java\net\mcreator\dimensioncrusher\DimensionCrusherMod.java:32](file:///F:/workspace/src/main/java/net/mcreator/dimensioncrusher/DimensionCrusherMod.java:32): error: cannot find symbol 
      DimensionCrusherModBrewingRecipes.load(); 
      ^ 
  symbol:   variable DimensionCrusherModBrewingRecipes 
  location: class DimensionCrusherMod 
1 error 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 2s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 3 seconds

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Micasddsa** [comment]
yea that happened to me. you can actually fix this by locking your base mod files and deleting the brewing stand recipe load line in the file. if you want, You can have them locked forever but if you make a procedure then you will have to unlock, regen, and relock the base mod files. you can lock base mod files in the workspace options.

The obvious downside would be that you can't use Brewing stand Recipes if you remove the line. I think.

if you don't want to do the process I outlined. then you can wait for an update that fixes this.

(Edit: To answer the title, yes, it is a bug.)
