### ISSUE TITLE
 error importing 3D models

### ISSUE THREAD

**Issue by MuzanRgc** [Goldorion/MCreatorFabricGenerator#276]
### Issue description

Hello, I am making a mod and if I import a 3d model I have no problem but if I try to put a second model the one I already had is replaced and I have to put it from the workspace folder and it works fine for me but if I try to add a third mob It gives me an error and I have to delete the model along with its texture and regenerate the code so that the error stops appearing, is there a solution for this?
![Captura de pantalla 2022-10-04 161806](https://user-images.githubusercontent.com/115044129/193934199-427aa55e-b713-4c1d-83d5-193388eac25c.png)

### How to reproduce this issue?

Step 1 - Import a 3d model of a mob 
Step 2 - Set up the mob
Step 3: when compiling it will give an error

### Operating system

Windows

### Details

MCreator 2022.2.34517, fabric-1.19.2, 64-bit

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Micasddsa** [comment]
Wow, Coincidentally, I am working on a mod that uses custom models too! Anyways.
I have a couple of questions.
What TYPE of model? I only used Java and JSON models so I know both can compile and work, idk about anything else.
What program did you use to make the model? This helps to see if you can do something in the program to fix the model if it's the model that's bad.

Also, Please provide the Build Logs and the models used. This is needed to see what is broken. Without these, nobody can recreate the issue.
If you want, you can provide the workspace so the problem can be 100% replicated but if you don't want to it's not needed. (i think.)

**Comment by MuzanRgc** [comment]
> Guau, casualmente, ¡estoy trabajando en un mod que también usa modelos personalizados! De todos modos. Tengo un par de preguntas. ¿Qué TIPO de modelo? Solo usé modelos Java y JSON, así que sé que ambos pueden compilar y funcionar, no sé nada más. Que programa usaste para hacer el modelo? Esto ayuda a ver si puede hacer algo en el programa para arreglar el modelo si es el modelo el que está mal.
> 
> Además, proporcione los registros de compilación y los modelos utilizados. Esto es necesario para ver lo que está roto. Sin estos, nadie puede recrear el problema. Si lo desea, puede proporcionar el espacio de trabajo para que el problema se pueda replicar al 100%, pero si no lo desea, no es necesario. (creo.)

For now I'm only using Java models and I'm making them in blockbench, I'll pass you the 3 models I'm using with their corresponding textures and the console log when trying to compile the mod and it would leave the workspace but I already tried and it doesn't work because the file is very heavy.
[3D models.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9719369/3D.models.zip)

Executing Gradle task: runClient
Build info: MCreator 2022.2.34517, fabric-1.19.2, 64-bit, 16251 MB, Windows 11, JVM 17.0.3, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2022-10-05-17:23:17
 
> Configure project :
Fabric Loom: 1.0.11
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix.
> Task :compileJava FAILED
C:\Users\irvin\MCreatorWorkspaces\Mobs+\src\main\java\net\mcreator\satan\client\model\model_custom_scp.java:22: error: class custom_model is public, should be declared in a file named custom_model.java public class custom_model<T extends Entity> extends EntityModel<T> {
  ^
C:\Users\irvin\MCreatorWorkspaces\Mobs+\src\main\java\net\mcreator\satan\client\renderer\ScpRenderer.java:8: error: cannot find symbol import net.mcreator.satan.client.model.model_custom_scp;
      ^
 symbol: class model_custom_scp
 location: package net.mcreator.satan.client.model
C:\Users\irvin\MCreatorWorkspaces\Mobs+\src\main\java\net\mcreator\satan\client\renderer\ScpRenderer.java:10: error: cannot find symbol public class ScpRenderer extends MobRenderer<ScpEntity, model_custom_scp<ScpEntity>> {
        ^
 symbol: class model_custom_scp
C:\Users\irvin\MCreatorWorkspaces\Mobs+\src\main\java\net\mcreator\satan\init\SatanModModels.java:7: error: cannot find symbol import net.mcreator.satan.client.model.model_custom_scp;
      ^
 symbol: class model_custom_scp
 location: package net.mcreator.satan.client.model
C:\Users\irvin\MCreatorWorkspaces\Mobs+\src\main\java\net\mcreator\satan\client\renderer\ScpRenderer.java:12: error: cannot find symbol  super(context, new model_custom_scp(context.bakeLayer(model_custom_scp.LAYER_LOCATION)), 0.5f);
    ^
 symbol: class model_custom_scp
 location: class ScpRenderer
C:\Users\irvin\MCreatorWorkspaces\Mobs+\src\main\java\net\mcreator\satan\client\renderer\ScpRenderer.java:12: error: cannot find symbol  super(context, new model_custom_scp(context.bakeLayer(model_custom_scp.LAYER_LOCATION)), 0.5f);
        ^
 symbol: variable model_custom_scp
 location: class ScpRenderer
C:\Users\irvin\MCreatorWorkspaces\Mobs+\src\main\java\net\mcreator\satan\init\SatanModModels.java:18: error: cannot find symbol  EntityModelLayerRegistry.registerModelLayer(model_custom_scp.LAYER_LOCATION, model_custom_scp::createBodyLayer);
       ^
 symbol: variable model_custom_scp
 location: class SatanModModels
C:\Users\irvin\MCreatorWorkspaces\Mobs+\src\main\java\net\mcreator\satan\init\SatanModModels.java:18: error: cannot find symbol  EntityModelLayerRegistry.registerModelLayer(model_custom_scp.LAYER_LOCATION, model_custom_scp::createBodyLayer);
            ^
 symbol: variable model_custom_scp
 location: class SatanModModels
8 errors
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
1 actionable task: 1 executed
 
BUILD FAILED
Task completed in 3 seconds

**Comment by MajAlva** [comment]
Have you made sure that your other models have different identifiers? You need to go to project settings and change it from Custom model to something else.

**Comment by MajAlva** [comment]
In blockbench

**Comment by MuzanRgc** [comment]
> en banco de bloques

if they have different identifiers

**Comment by Goldorion** [comment]
I just tested and it worked fine. Can you provide me a minimal reproducible workspace?

**Comment by MuzanRgc** [comment]
> I just tested and it worked fine. Can you provide me a minimal reproducible workspace?

[mod.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9740182/mod.zip)

**Comment by Goldorion** [comment]
Absolutely no error. Download the latest version.
