### ISSUE TITLE
cannot start a new workspace

### ISSUE THREAD

**Issue by ColeXXlX** [Goldorion/MCreatorFabricGenerator#277]
### Issue description

even tho i have the zip file in the plugins file i cannot start a new workspace with fabric

### How to reproduce this issue?

I followed all step for installing

### Operating system

Windows

### Details

MCreator version: 2022.2

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by ColeXXlX** [comment]
i even tried unzipping the file and put it in the plugins file folder

**Comment by Goldorion** [comment]
Snapshot

**Comment by ColeXXlX** [comment]
thanks!
