### ISSUE TITLE
place feature command in procedures not working

### ISSUE THREAD

**Issue by ColeXXlX** [Goldorion/MCreatorFabricGenerator#278]
### Issue description

im using execute command block 
command im using: execute in the_end run place feature minecraft:end_gateway_return 1024 66 0

### How to reproduce this issue?

1.ive tried xyz blocks have both the location and empty
2.tried using / in the beginning of command

### Operating system

Windows

### Details

MCreator Version: 2022.3

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I can't do something.
