### ISSUE TITLE
GUIs wont work in the newest version

### ISSUE THREAD

**Issue by PaxtonPenguin** [Goldorion/MCreatorFabricGenerator#279]
### Issue description

When ever you make a gui, and mcreator saves, an error occures

### How to reproduce this issue?

Step 1: Create GUI
Step 2: Error

### Operating system

Linux

### Details

2022.2
fabric 1.19.2

### Example workspace

did'nt save so no example project

### Logs

https://pastebin.com/F3YwfKhG

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I was not able to reproduce the issue. Make sure to use the latest version. Without more information, I can not help more.
