### ISSUE TITLE
Brewing stand and potion recipes not working

### ISSUE THREAD

**Issue by purejosh** [Goldorion/MCreatorFabricGenerator#285]
### Issue description

Brewing stands will not accept items that aren't vanilla accepted, and will not create a new potion using a custom recipe. 

Also, creating a potion type which includes all 4 items seems to work fine, but assigning it into the brewing stand as a result causes a build error. Unfortunately, it's not showing me the build error, it just says that I need to refactor my workspace, which does not work. 

### How to reproduce this issue?

Create a potion set. 
Create a recipe for the brewing stand using any item that's not usually a brewing ingredient, and assign a custom potion as the result item. 
Observe that there are build errors. 
Change result item to a vanilla potion. 
Observe that using the brewing stand will not work with the item that's not usually a brewing ingredient. 

### Operating system

Windows

### Details

MCreator 2022.3.41417
Fabric Generator 1.7-beta-11

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
With Fabric, only potions are accepted as an inpit (bottom) and as the result. The ingredient (top) can only be an item/block item.

**Comment by purejosh** [comment]
By your own definition, this is not working as intended. I'll provide more info, since it appears that I'm not explaining things in an understandable way.

Narrowing it down to one singular issue, I cannot set the result potion to be a potion made in MCreator. It **can** be set as an existing, vanilla potion. But a custom made potion (complete with potion/splash/lingering/arrow) will cause the following error: 
![image](https://user-images.githubusercontent.com/70633949/197236844-ef876b88-c0dd-4343-88c0-a92996245d82.png)

Here's the potion set I was talking about: 
![image](https://user-images.githubusercontent.com/70633949/197236893-c5167748-5a7f-43dc-a720-6ff5c0daf192.png)

And here's the recipe for the brewing stand: 
![image](https://user-images.githubusercontent.com/70633949/197236954-0b1996eb-5ecb-426d-a8db-d6c12f4542d4.png)

If I set the result item to a potion of leaping, which is vanilla, it works fine. If I set it to a custom potion that was made in MCreator, it fails. I've tested this in Forge, by changing the generator to Forge 1.19.2, and it compiles. This issue is exclusive to the Fabric Generator. 

[FrogLegs-share.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9840635/FrogLegs-share.zip)

**Comment by purejosh** [comment]
I found this in the console, I should've provided this sooner. 

```
> Task :compileJava FAILED 
[C:\Users\purejosh\MCreatorWorkspaces\froglegs\fabric\src\main\java\net\purejosh\froglegs\init\FroglegsModBrewingRecipes.java:11](file:///C:/Users/purejosh/MCreatorWorkspaces/froglegs/fabric/src/main/java/net/purejosh/froglegs/init/FroglegsModBrewingRecipes.java:11): error: cannot find symbol 
      PotionBrewing.addMix(Potions.AWKWARD, FroglegsModItems.FROG_LEG, FroglegsModPotions.FROG_LEAPING.get()); 
                                                                                                      ^ 
  symbol:   method get() 
  location: variable FROG_LEAPING of type Potion 
1 error 
FAILURE: Build failed with an exception.
```

```
package net.purejosh.froglegs.init;

import net.minecraft.world.item.alchemy.Potions;
import net.minecraft.world.item.alchemy.PotionBrewing;

public class FroglegsModBrewingRecipes {
	public static void load() {
		PotionBrewing.addMix(Potions.AWKWARD, FroglegsModItems.FROG_LEG, FroglegsModPotions.FROG_LEAPING.get());
	}
}
```

**Comment by Goldorion** [comment]
> I found this in the console, I should've provided this sooner

Thanks, I forgot once again to remove a Forge getter that isn't needed with Fabric (.get())

**Comment by purejosh** [comment]
Thank you!

**Comment by Goldorion** [comment]
Sorry for the time it took. I didn't have much free time recently :)

**Comment by purejosh** [comment]
It's okay, it wasn't very critical. I appreciate it anyway!
