### ISSUE TITLE
Making Stairs cause compilation error

### ISSUE THREAD

**Issue by PSGitHubUser1** [Goldorion/MCreatorFabricGenerator#286]
### Issue description

When I was making the stairs, MCreator fails to compile it.

### How to reproduce this issue?

Step 1: Create a new block
Step 2: Select the Stairs option
Step 3: Save block

### Operating system

Windows

### Details

MCreator version: **Snapshot/Pre-release 2022.3 (build 44708)**

Generator type: **Fabric 1.19.x**

Also the duplicate of #232 but he closed the issue. He should fix that... 
![image](https://user-images.githubusercontent.com/90406016/198963833-78440dec-6470-4c22-bac0-61994cdd470b.png)
![image](https://user-images.githubusercontent.com/90406016/198964088-5b51ce40-267e-4296-8369-a218a9d8c840.png)
The second picture may help the Goldorion.. so that he can confirm that from where the problem is generating. 

The "." aka 'Dot' is causing build error. I tried **almost** every other symbols (also which do not work in Java) what I do now? 

### Example workspace

[BambooVariants.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9896282/BambooVariants.zip)

### Issue tracker rule checks (please read carefully)

- [x] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Duplicated of https://github.com/Goldorion/Fabric-Generator-MCreator/issues/232

**Comment by PSGitHubUser1** [comment]
> Duplicated of #232

Please fix this...
