### ISSUE TITLE
terrablender makes the game unable to launch

### ISSUE THREAD

**Issue by TheRidiculousR** [Goldorion/MCreatorFabricGenerator#290]
### Issue description

with the current release versions of Mcreator 2022.3 and fabric generator 0.60.0, turning on terraBlender in External APIs makes the game unable to launch.
the build will be successful, but running the client will crash pretty much right away before the title screen even shows.

attached is an empty workspace with no elements, which has terrablend enabled.
[terrablend crash example.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9982754/terrablend.crash.example.zip)

### How to reproduce this issue?

step 1: using Mcreator 2022.3 and fabric generator 0.60.0, create a new mod for minecraft fabric 1.19.2.

step 2: go to the Workspace settings, and under External APIs, enable TerraBlender Fabric.

step 3: run client

### Operating system

Windows

### Details

Mcreator version: 2022.3
generator: Minecraft Fabric for 1.19.2 - 0.60.0

### Example workspace

[terrablend crash example.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/9982754/terrablend.crash.example.zip)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by TheRidiculousR** [comment]
strangely, grabbing the most recent release of the fabric generator from github instead of Mcreator.net removes the API as an option.
biomes now function but with less features.

**Comment by Micasddsa** [comment]
> strangely, grabbing the most recent release of the fabric generator from github instead of Mcreator.net removes the API as an option. biomes now function but with less features.

Github releases are old and are not updated anymore. MCreator.net is where the updated builds are.

**Comment by TheRidiculousR** [comment]
the current mcreator release does still crash with terrablend though

**Comment by TheRidiculousR** [comment]
i also find it very strange that the github releases are not being kept up-to-date, if for whatever reason someone may need an older version of a plugin which isn't listed on mcreator, there is no way to get it now

**Comment by TheRidiculousR** [comment]
i noticed the crash was related to a nether rule being created with no nether biome existing, when i added a nether biome, it didnt crash anymore

**Comment by Goldorion** [comment]
You need to add `terrablender` to the mod's dependencies, so a file can be generated. I will change how it works as it seems, not everyone uses the dependencies field.
