### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Grey-Wind** [Goldorion/MCreatorFabricGenerator#291]
### Issue description

1.16.5, 1.17.1 and 1.18.2 fabric build always fail in china
I try 20 hours and never complete
but in jetbrains idea, it can run successfully, after run, i open the mcreator, it run failed again
idk why, i think you can try to fix it

### How to reproduce this issue?

1.16.5, 1.17.1 and 1.18.2 fabric build always fail in china
I try 20 hours and never complete
but in jetbrains idea, it can run successfully, after run, i open the mcreator, it run failed again
idk why, i think you can try to fix it

### Operating system

Windows

### Details

Mcreator:2021.3/2022.1/2022.2/2022.3
windows 10 21H2;Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz 1.80 GHz;12.0 GB

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I can't do something for that as it's a China soecific problem.

**Comment by Grey-Wind** [comment]
can you use the chinese maven url,such as aliyun

**Comment by Grey-Wind** [comment]
i think it maybe work
