### ISSUE TITLE
[Request] Fabric 1.18.2 re-support

### ISSUE THREAD

**Issue by RFNMC** [Goldorion/MCreatorFabricGenerator#312]
**Describe the feature**
Hope to re-support the fabric generator for Minecraft 1.18.2

**Describe why you want the feature**
It's known that 1.18.2 has more mods than 1.19.2
My server uses a lot of 1.18.2 mods that 1.19.2 does not support.

**Additional context**
I downloaded 1.18.2 fabric generator modified by NerdyPuzzle, but it has so many problems and bugs that I can't finish my work on it.

**Comment by Goldorion** [comment]
Nope. I updated to 1.19.2 and I won't downgrade until I have a team to support and help me. It would require way too much time to maintain 2 generators.

**Comment by lbplay29** [comment]
I want to commit death upon myself
