### ISSUE TITLE
Not able to export mod with Update 1.7

### ISSUE THREAD

**Issue by PSGitHubUser1** [Goldorion/MCreatorFabricGenerator#313]
### Issue description

I made a mod but I try to export it shows this. 

![image](https://user-images.githubusercontent.com/90406016/204750420-b6c5bb05-60fa-46f8-a2e0-1b8159f71035.png)

### How to reproduce this issue?

Step 1: Make a mod
Step 2: Export it
Step 3: Error shows

### Operating system

Windows

### Details

MCreator version: 2022.3 (latest, 1.19.2)
Fabric Generator: update 1.7 [not beta]

### Example workspace

PortDiscs Mod on curseforge.

### Logs

Executing Gradle task: build
Build info: MCreator 2022.3.48217, fabric-1.19.2, 64-bit, 8048 MB, Windows 11, JVM 17.0.3, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2022-11-30-14:22:29
 
> Configure project :
Fabric Loom: 1.0.12
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix.
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :prepareRemapJar
> Task :sourcesJar UP-TO-DATE
> Task :remapJar UP-TO-DATE
> Task :remapSourcesJar UP-TO-DATE
> Task :assemble UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :validateAccessWidener NO-SOURCE
> Task :check UP-TO-DATE
> Task :build UP-TO-DATE
 
BUILD SUCCESSFUL in 8s
7 actionable tasks: 1 executed, 6 up-to-date
Task completed in 9 seconds

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Micasddsa** [comment]
Please use the latest version on the MCreator plugin page.

**Comment by Goldorion** [comment]
Kleiders confirmed me it was a problem, so it was my test workspace. Reopening it until the fix is merged.

**Comment by NerdyPuzzle** [comment]
#315
