### ISSUE TITLE
Structures are not spawning where they are set to spawn

### ISSUE THREAD

**Issue by PSGitHubUser1** [Goldorion/MCreatorFabricGenerator#321]
### Issue description

#313 This was also posted by me.

The structures are not spawning in that biomes which they are set to. 

![2022-12-03_11 33 58](https://user-images.githubusercontent.com/90406016/205427405-7ffb2bed-030c-4d2a-a0ba-a9d1ed9c7655.png)

### How to reproduce this issue?

Step 1: Just make a structure 
Step 2: Export mod
Step 3: Run game
Step 4: And you'll your structures everywhere where they should not spawn.

### Operating system

Windows

### Details

MCreator: 2022.3 (latest)
Fabric Generator: 1.7.1 (latest)

### Example workspace

my workspace is a example.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by NerdyPuzzle** [comment]
Tested and can confirm this issue is invalid. The structures spawn in the ocean for you because you set the ground reference type to first motion blocking block instead of first block.

**Comment by PSGitHubUser1** [comment]
> Tested and can confirm this issue is invalid. The structures spawn in the ocean for you because you set the ground reference type to first motion blocking block instead of first block.


What happens with these two options?

**Comment by NerdyPuzzle** [comment]
One will spawn structures in oceans, the other won't.
