### ISSUE TITLE
"Get text inside textfield ()" build fail

### ISSUE THREAD

**Issue by zsvan** [Goldorion/MCreatorFabricGenerator#328]
### Issue description

```
> Task :compileJava FAILED 
C:\Users\sucki\MCreatorWorkspaces\fabrictestenv\src\main\java\net\mcreator\fabrictestenv\network\HandheldWikiGuiButtonMessage.java:36: error: cannot find symbol 
                  .execute(com.google.common.collect.ImmutableMap.<String, Object>builder().put("guistate", guistate).build()); 
                                                                                                            ^ 
  symbol:   variable guistate 
  location: class HandheldWikiGuiButtonMessage 
1 error 
FAILURE: Build failed with an exception.
```

![image](https://user-images.githubusercontent.com/17712352/205703073-fcd9673d-7ece-4637-8582-fa1e41be85c6.png)

### How to reproduce this issue?

Make GUI element - add text field - add procedure that uses said text field - test.

### Operating system

Windows

### Details

Currently using fabric generator 1.19.2, version 1.7, on newest release of mcreator 2022.3.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by NerdyPuzzle** [comment]
Weird, I do not seem to have this issue.

**Comment by zsvan** [comment]
> Weird, I do not seem to have this issue.

[guistateerror.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/10167870/guistateerror.zip)

also, using [HTTP Utilities plugin with added fabric generator ](https://github.com/suckinsyn/mcreator-http-utility)
