### ISSUE TITLE
Creating custom biome error

### ISSUE THREAD

**Issue by CasterMx13** [Goldorion/MCreatorFabricGenerator#329]
### Issue description

When creating a custom biome without a "generate biome in overworld/nether" option enabled it causes an illegal start of expression error.
Goal was to make a biome specific to a custom dimension, so generating it in the overworld/nether as well conflicts with that.

### How to reproduce this issue?

Create workspace, enable Terrablender, create biome, uncheck generate biome in overworld/nether, save, error.

### Operating system

Windows

### Details

Latest versions; Mcreator 2022.3, fabric plugin 1.7.1, 0.60.0

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by NerdyPuzzle** [comment]
You cannot generate the biomes in custom dimensions, terrablender only generates biomes in the overworld and nether.

**Comment by CasterMx13** [comment]
> You cannot generate the biomes in custom dimensions, terrablender only generates biomes in the overworld and nether.

Ahh, was unaware of that. In that case can

**Comment by CasterMx13** [comment]
I have no idea how I closed that^ Was trying to comment requesting the feature, or at least a tooltip somewhere saying that.
My bad on the close/open bits, I really need to figure out github a bit more. lol

**Comment by NerdyPuzzle** [comment]
I do not think a tooltip is possible as they are part of mcreator's code.

**Comment by Goldorion** [comment]
> You cannot generate the biomes in custom dimensions, terrablender only generates biomes in the overworld and nether.

Custom biomes inside custom dimensions sjould he possible. If it's not, this means there is a bug somewhere.

**Comment by Goldorion** [comment]
> I do not think a tooltip is possible as they are part of mcreator's code.

Changing a mod element's tooltip? You just need to override the mcreator-localization plugin (with a higher plugin's weight). I'm already doing it for some.

**Comment by NerdyPuzzle** [comment]
But that would replace the regular tooltips, would it not?

**Comment by Goldorion** [comment]
> But that would replace the regular tooltips, would it not?

Just the ones you changed (each tooltip is its own file, meaning you can change a specific tooltip).

**Comment by FastEverLast** [comment]
I have it too it says 
![Screenshot 2022-12-08 at 18 36 42](https://user-images.githubusercontent.com/120122875/206516839-8e320282-1004-4580-baec-b7ac036b043c.png)

**Comment by NerdyPuzzle** [comment]
name, , 10 💀

**Comment by FastEverLast** [comment]
what should I change?

**Comment by FastEverLast** [comment]
(I didnt code it Mcreator did)

**Comment by NerdyPuzzle** [comment]
For now remove one of the , from the code shown in the console. Tell me if there are any errors after that.

**Comment by FastEverLast** [comment]
I did that but now it gives an error about terrablender..........

**Comment by Goldorion** [comment]
Fixed with https://github.com/Goldorion/Fabric-Generator-MCreator/commit/009938e4c2b44e02874832685a80d7d7e436030b
