### ISSUE TITLE
Error when converting a forge workspace to fabric

### ISSUE THREAD

**Issue by CristalGaming** [Goldorion/MCreatorFabricGenerator#330]
### Issue description

The bug occurs when you convert a forge workspace mod to fabric. It doesn't shows the error when you create a new workspace I'm not sure if it's because the plugin or mcreator.

### How to reproduce this issue?

1) i've made a copy of my workpace
2) I convert the mod from forge to fabric
3) i've got the "Main mod file compilation errors"
4) i've tried to regenerate the code and to clean the entire gradle folder but it didn't work.
5) i tried to make a new workspace to see if i get the same error.
6) this time i don't get any error

### Operating system

Windows

### Details

Plugin Version: 1.7.1

### Logs

```
Executing Gradle task: build 
Build info: MCreator 2022.3.48217, fabric-1.19.2, 64-bit, 7985 MB, Windows 10, JVM 17.0.3, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2022-12-06-19:31:45 
  
> Configure project : 
Fabric Loom: 1.0.12 
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> Task :compileJava FAILED 
[E:\System Apps\MCreator Workspace\Puzzle_code _fabric\src\main\java\net\mcreator\puzzle_code\PuzzleCodeMod.java:55](file:///E:/System%20Apps/MCreator%20Workspace/Puzzle_code%20_fabric/src/main/java/net/mcreator/puzzle_code/PuzzleCodeMod.java:55): error: not a statement 
      {JavaModName}Variables.SyncJoin(); 
       ^ 
[E:\System Apps\MCreator Workspace\Puzzle_code _fabric\src\main\java\net\mcreator\puzzle_code\PuzzleCodeMod.java:55](file:///E:/System%20Apps/MCreator%20Workspace/Puzzle_code%20_fabric/src/main/java/net/mcreator/puzzle_code/PuzzleCodeMod.java:55): error: ';' expected 
      {JavaModName}Variables.SyncJoin(); 
                  ^ 
[E:\System Apps\MCreator Workspace\Puzzle_code _fabric\src\main\java\net\mcreator\puzzle_code\PuzzleCodeMod.java:56](file:///E:/System%20Apps/MCreator%20Workspace/Puzzle_code%20_fabric/src/main/java/net/mcreator/puzzle_code/PuzzleCodeMod.java:56): error: not a statement 
      {JavaModName}Variables.SyncChangeWorld(); 
       ^ 
[E:\System Apps\MCreator Workspace\Puzzle_code _fabric\src\main\java\net\mcreator\puzzle_code\PuzzleCodeMod.java:56](file:///E:/System%20Apps/MCreator%20Workspace/Puzzle_code%20_fabric/src/main/java/net/mcreator/puzzle_code/PuzzleCodeMod.java:56): error: ';' expected 
      {JavaModName}Variables.SyncChangeWorld(); 
                  ^ 
4 errors 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 2s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 1 minute and 31 seconds

```
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by NerdyPuzzle** [comment]
Not an issue with Fabric Generator, Kleiders forgot to add a $ to some global variables in Fabric Essentials, a patch will be published soon.

**Comment by CristalGaming** [comment]
thank you for telling me.

**Comment by NerdyPuzzle** [comment]
The new release of FabricEssentials is out.

**Comment by CristalGaming** [comment]
yay 😃
