### ISSUE TITLE
Text with <BNBT:integer:example> in GUI gives error.

### ISSUE THREAD

**Issue by CristalGaming** [Goldorion/MCreatorFabricGenerator#333]
### Issue description

I think the bug occurs when a GUI has inside a text label that contains something like \<BNBT:integer:tagName\> or \<VAR:customVariable\>.
I send the code with the error of one of the blocks.
### How to reproduce this issue?

1) I Tried to convert a forge mod to fabric.
2) When it finished the worspace gives error and all the errors comes from the GUI mods.

### Operating system

Windows

### Details

Windows 10
MCreator: 2022.3
Fabric: 1.7.1

### Logs

```
Executing Gradle task: build 
Build info: MCreator 2022.3.48217, fabric-1.19.2, 64-bit, 7985 MB, Windows 10, JVM 17.0.3, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2022-12-08-15:50:44 
  
> Configure project : 
Fabric Loom: 1.0.12 
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> Task :compileJava
[E:\System Apps\MCreator Workspace\Puzzle_code _fabric\src\main\java\net\mcreator\puzzle_code\client\gui\SwitchableTermsNumberCodeBlockGUIScreen.java:80](file:///E:/System%20Apps/MCreator%20Workspace/Puzzle_code%20_fabric/src/main/java/net/mcreator/puzzle_code/client/gui/SwitchableTermsNumberCodeBlockGUIScreen.java:80): error: cannot find symbol 
               return BlockEntity.getTileData().getBoolean(tag); 
                                 ^ 
  symbol:   method getTileData() 
  location: variable BlockEntity of type BlockEntity 
[E:\System Apps\MCreator Workspace\Puzzle_code _fabric\src\main\java\net\mcreator\puzzle_code\client\gui\SwitchableTermsNumberCodeBlockGUIScreen.java:88](file:///E:/System%20Apps/MCreator%20Workspace/Puzzle_code%20_fabric/src/main/java/net/mcreator/puzzle_code/client/gui/SwitchableTermsNumberCodeBlockGUIScreen.java:88): error: cannot find symbol 
               return BlockEntity.getTileData().getBoolean(tag); 
                                 ^ 
  symbol:   method getTileData() 
  location: variable BlockEntity of type BlockEntity 
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output 
100 errors 
only showing the first 100 errors, of 149 total; use -Xmaxerrs if you would like to see more 
> Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 29s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 45 second
```
**I removed some text because is just the same error but on different blocks.**

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by CristalGaming** [comment]
why it is invalid?

**Comment by NerdyPuzzle** [comment]
Because block nbts do not exist. Essentials adds them, but I didn't replace the tokens system code as it will be replaced soon in 2022.4 with conditions that return text.

**Comment by CristalGaming** [comment]
thank you for help.
