### ISSUE TITLE
[Feature Request] Add support for Villager trades

### ISSUE THREAD

**Issue by PSGitHubUser1** [Goldorion/MCreatorFabricGenerator#349]
Check out - #348 
-----------------------
I want this feature my mod and its required for my fabric ported mod. Please add Villager trades.

 I opened the MC 1.19.2 game files and checked out 'Villager Trades' and they are simple.
 
 -------------------------------------------------------------
 
_For Fabric Essentials (@NerdyPuzzle)_

You can add Architectury API for Villager Trade support or add this mod in your plugin https://www.curseforge.com/minecraft/mc-mods/custom-villager-trades-fabric/files/4175948

**Comment by PSGitHubUser1** [comment]
@NerdyPuzzle or @kleiders3010 or @Goldorion  Please provide your Discord. I can't just create new bugs to issue you.

It is better to just talk with you on discord. 
 If you ask in terms of privacy, then send me your discord id in personal here (I will be waiting): https://www.curseforge.com/members/infoytechtv/projects 
 
 So that nobody except me can take your id and just send you friend request
 
 Thanks.

**Comment by Micasddsa** [comment]
Do not ask for discord tags. This is the issue tracker. you submit issues here. not on discord. for maintainers, giving someone access to their discord just allows more anoyances, nothing more.

Here are some suggestions.
- If you want to keep your project private, don't use it. simple. use a test workspace to submit bugs and test fixes.
- If you are impatient, just don't make issues. people are doing this for free. if you are impatient about these things, just don't make them and leave the maintainers alone.

(BTW, please use the issue/feature request template. it doesn't help anyone to make a lazy/bad issue/request.)

**Comment by NerdyPuzzle** [comment]
Have some patience. As mentioned above, we do this for free. If an issue is present and we locate it, it will most likely be fixed in the future.

**Comment by PSGitHubUser1** [comment]
No no.. I am talking about your privacy not mine..

I believe on you @NerdyPuzzle @Micasddsa @Goldorion and @kleiders3010 

I don't anyone to just copy the Discord ID and Send Friend Request to these devs. They will be disturbed...
So I said that just send your Discord ID to here:  https://www.curseforge.com/members/infoytechtv/projects

--------------------------
### Imagine

I said you and you sent your Discord ID and Someone (Let someone as G), so G can take your Discord ID and Send you friend request for unnecessary and then all people will start doing this that's why I am saying that send me your Discord ID here: https://www.curseforge.com/members/infoytechtv/projects

Otherwise, G and others can disturb you while coding.. and as result, you will type '1 letter' wrong and the plugin will not work..

I am patiently waiting... If you don't want to send then just tell me (no problem) and sorry if you still not understand.

(Just understand that my objective is not to disturb you or let anyone to disturb 🙂)

**Comment by PSGitHubUser1** [comment]
> Have some patience. As mentioned above, we do this for free. If an issue is present and we locate it, it will most likely be fixed in the future. 

Have you find the bug/problem..?

_I'm just asking, I have patience.._ 🙂 _I can wait more._

Thanks to all of you that you're trying to find the bug for me.

**Comment by PSGitHubUser1** [comment]
Uhh... I am really sorry but I'm losing my patience. Is it done? [Villager Trade Support]

As @Atten007 said [here](https://maven.fabricmc.net/docs/fabric-api-0.25.1+build.416-1.16/index.html?net/fabricmc/fabric/api/object/builder/v1/villager/VillagerProfessionBuilder.html) is the API of Fabric.

**Comment by Goldorion** [comment]
> Uhh... I am really sorry but I'm losing my patience.

It is a great thing because I am losing my patience with you. If you are that impatient, you just have to open a PR. It is a free, open-sourced, hobby and free project. You spend literally nothing on it. I am spending so much time on it that I stopped counting the weeks I worked on it. This is just a hobby for me, like everything related to MCreator and you pay nothing for it. MCreator is neither my life, nor my job, nor the only thing I have and want to do.

Luckily for you, you did not use MCreator a few years ago.

This is the last time I tell you this.

**Comment by PSGitHubUser1** [comment]
What's PR? Sounds good.

**Comment by PSGitHubUser1** [comment]
Thanks Goldorion!! Thanks a lot.. you took a break of 1 month.. (you didn't uploaded new updates of FB Generator for a while), I knew that you have been working behind as I regularly see the GitHub. 

Thanks Goldorion but why and how you added support of 1.20? Because Klemen and their team is giving support of 1.19.4...

**Comment by Goldorion** [comment]
>  you took a break of 1 month

I was quite busy since February and I had my final exams during May, so not a lot of time to work on big updates
