### ISSUE TITLE
''> Task :validateAccessWidener NO-SOURCE'' when setting up workspace

### ISSUE THREAD

**Issue by ninem4re** [Goldorion/MCreatorFabricGenerator#350]
### Issue description

Hi,
I wanted to create my first Fabric mod and just play around with MCreator a bit, but the initial workspace gradle build failed. I have no idea what could be causing this, I tried to fix it on my own, but I couldn't get it to work. I tried repacing the gradle binary with the latest, but I had no idea how to do that, I tried to delete the gradle directory in the .mcreator directory and replacing that but that did absolutely nothing. I also tried just deleting the gradle directory in .mcreator but that also did absolutely nothing.

Thanks in advance to anyone who decides to help!
Have a great day!

Note: Although I've seen a report of the same bug, it was deemed unreproducable and the issue was closed, so I had to make a new issue.

### How to reproduce this issue?

Step 1: Open MCreator and make a new workspace.
Step 2: I entered info about my mod.
Step 3: Wait for Gradle to fail.

### Operating system

Other (Tell us at the Specifications part)

### Details

System: Raspberry Pi OS (Linux - Debian) 64-bit
Screenfetch output: https://gist.github.com/DKXLY/d04c3af22a4419e7c741a011f7950c8d
MCreator version: 2022.3 latest stable, also affects latest 2022.3 snapshot
Generator type: 1.19.2 Fabric
Architecture: aarch64
Java JDK: 17.0.2 with OpenJFX
Gradle: the one that comes with MCreator
I also have a modified mcreator.sh file which is patched for MCreator to actually run:
[mcreator.sh.txt](https://github.com/Goldorion/Fabric-Generator-MCreator/files/10252622/mcreator.sh.txt)
And I have a modified discord-rpc-release-v3.4.0.jar file which includes the .so aarch64 discord-rpc libraries (which I built myself from the archived source on github, I know that it's useless for aarch64 but otherwise, MCreator wouldn't run):
![2022-12-17-202929_1440x900_scrot](https://user-images.githubusercontent.com/77124386/208263180-7407ceb5-e324-4ca3-9e4a-626b43284928.png)

### Logs

https://gist.github.com/DKXLY/ee03ddf52e8fcf430136e803af6002fb

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Try to run again the task. I don't know why, but this problem appears sometimes and simply rerunning the task fixes the problem.

**Comment by ninem4re** [comment]
The issue still persists after multiple re-runs. I also tried to put the offbeata.accesswidener fille into src/main/resources/ folder and that also didnt do anything. I have asked ChatGPT about this issue and it said that it could be an incorrect gradle configuration or a dependency issue. Could that be the problem? If yes, I will happily provide any necessary files.

**Comment by ninem4re** [comment]
Accidentally closed.

**Comment by Goldorion** [comment]
> The issue still persists after multiple re-runs. I also tried to put the offbeata.accesswidener fille into src/main/resources/ folder and that also didnt do anything. I have asked ChatGPT about this issue and it said that it could be an incorrect gradle configuration or a dependency issue. Could that be the problem? If yes, I will happily provide any necessary files.

Without more details, I can't really help because it works perfectly fine on my side. Try to delete your Gradle folder and re-test.

**Comment by ninem4re** [comment]
Are there any specific details you would need to know?

**Comment by QianHuiQwQ** [comment]
我之前也遇到了同样的问题，只要点击编辑区上方的下载源代码即可，它的位置在图片的红色区域
<img width="1920" height="1040" alt="Image" src="https://github.com/user-attachments/assets/757730b7-f143-43f1-b534-0646eedddff7" />
希望能帮到你和其它来到这里的人

**Comment by f0xf1reyt** [comment]
im having this same issue could it be a linux thing, im on ubuntu
