### ISSUE TITLE
Gradle Error

### ISSUE THREAD

**Issue by Sldelev** [Goldorion/MCreatorFabricGenerator#352]
### Issue description

At the moment of creating a workspace on fabric generator, a Gradle Daemon error occurs, which in turn does not allow creating a workspace.

**I attach the error code below:**
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
To see all tasks and more detail, run gradle tasks --all
To see more detail about a task, run gradle help --task <task>
> Task :validateAccessWidener NO-SOURCE
Error: Could not find or load main class worker.org.gradle.process.internal.worker.GradleWorkerMain
Caused by: java.lang.ClassNotFoundException: worker.org.gradle.process.internal.worker.GradleWorkerMain
Could not write standard input to Gradle Worker Daemon 1.
java.io.IOException: Идет закрытие канала
 at java.base/java.io.FileOutputStream.writeBytes(Native Method)
 at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349 at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349)
 at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81 at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
 at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142 at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
 at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68 at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68)
 at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53 at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
 at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64 at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
 at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48 at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.lang.Thread.run(Thread.java:833 at java.base/java.lang.Thread.run(Thread.java:833)
> Task :genSourcesWithCfr FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':genSourcesWithCfr'.
> There was a failure while executing work items
 > A failure occurred while executing net.fabricmc.loom.task.GenerateSourcesTask$DecompileAction
  > Failed to run Gradle Worker Daemon
  > Process 'Gradle Worker Daemon 1' finished with non-zero exit value 1
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 22s
2 actionable tasks: 2 executed
 
BUILD FAILED
Task completed in 23 seconds

### How to reproduce this issue?

Step 1: Create new workspace on  fabric generator
Step 2: waiting gradle build
Step 3: Poof! Gradle Error

### Operating system

Windows

### Details

Mcreator version 2022.3
Fabric generator version 1.8
Minecraft version 1.19.2

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PSGitHubUser1** [comment]
Yes, You're right. I just created a new workspace because @NerdyPuzzle said that never test a new released build on old/worked workspace..

Firstly, I did that mistake again (didn't created the new workspace) and opened it in my worked workspace. Nothing happened to old workspace but then I remembered and created a new one... and this happened (On which you've made this issue)

Try to report that to @NerdyPuzzle or @kleiders3010 because @Goldorion not replies frequently.. (He is busy too.)

-------
Report to https://github.com/NerdyPuzzle/Fabric-Essentials/issues 
Because Nerdy will try to fix that by publishing a new version on https://mcreator.net/plugin/92672/fabric-essentials. As soon as possible.. (It will be temporary then @Goldorion may fix this bug in his new release)

**Comment by kleiders3010** [comment]
We cannot replicate the issue; Make sure of that you are on latest and maybe try adding fabric essentials to your plugins. https://mcreator.net/plugin/92672/fabric-essentials

**Comment by NerdyPuzzle** [comment]
After creating a new workspace with both fabric essentials and without it, I could not reproduce this error. Make sure you do not have multiple versions of either plugin, and that you have the latest version of both from the plugin's page.

**Comment by PSGitHubUser1** [comment]
> We cannot replicate the issue; Make sure of that you are on latest and maybe try adding fabric essentials to your plugins. https://mcreator.net/plugin/92672/fabric-essentials

Yes. I am on latest build.. v1.6.2

**Comment by PSGitHubUser1** [comment]
> After creating a new workspace with both fabric essentials and without it, I could not reproduce this error. Make sure you do not have multiple versions of either plugin, and that you have the latest version of both from the plugin's page.

No... I open the workspace and it started building (it always says "REGENERATE CODE" but nothing happens after "REGENERATING CODE") and when it finished its showing this error:

![image](https://user-images.githubusercontent.com/90406016/208469975-4b7cdc62-73b5-4af2-9118-f99a06dfdd7b.png)

![image](https://user-images.githubusercontent.com/90406016/208470092-218f5dc1-cd55-448f-b6bc-54b08becf523.png)
![image](https://user-images.githubusercontent.com/90406016/208470133-72b76299-c02e-4706-8792-b87709a0008c.png)

**Comment by PSGitHubUser1** [comment]
@Goldorion 

No. Please test it once.. Don't close, its not working as intended.

**Comment by NerdyPuzzle** [comment]
This is because you did not enable fabric essentials' api

**Comment by Goldorion** [comment]
> @Goldorion
> 
> No. Please test it once.. Don't close, its not working as intended.

I tested hundred of times since I released the version... (without Fabric essentials)

**Comment by PSGitHubUser1** [comment]
> > @Goldorion
> > No. Please test it once.. Don't close, its not working as intended.
> 
> I tested hundred of times since I released the version...

wait wait.. see

**Comment by PSGitHubUser1** [comment]
![image](https://user-images.githubusercontent.com/90406016/208471617-b13e95b8-26cb-48b0-b704-b00c31a1b17b.png)
its enabled?

What I do now? Reinstall the plugins?

**Comment by kleiders3010** [comment]
> ![image](https://user-images.githubusercontent.com/90406016/208471617-b13e95b8-26cb-48b0-b704-b00c31a1b17b.png) its enabled?
> 
> What I do now? Reinstall the plugins?

Enable, then save.

**Comment by PSGitHubUser1** [comment]
> > ![image](https://user-images.githubusercontent.com/90406016/208471617-b13e95b8-26cb-48b0-b704-b00c31a1b17b.png) its enabled?
> > What I do now? Reinstall the plugins?
> 
> Enable, then save.

Huh. Already, Last time 1 thing fixed, reinstalling the plugins.
Hope that it will work (coming few mins later)

**Comment by PSGitHubUser1** [comment]
I guess, its working..? wait..

UPDATE: It worked!! Yes. Thanks to all again @Goldorion @kleiders3010 @NerdyPuzzle

**Comment by Goldorion** [comment]
https://user-images.githubusercontent.com/38427877/208472797-5d83bf20-8f03-49ea-a2ec-3b676520a733.mp4

Do you trust me now? I told you it worked and it works. Now, if you are not able to understand what I say or fix basic Gradle issues, it's not my problem. You just need to read a page on the MCreator's Wiki.


Next time, you open an issue. This is a ban from this repository. When I close an issue, this is to see it closed, not opened again. You have a real patience problem. I hope you will change your behaviour soon.

**Comment by PSGitHubUser1** [comment]
> https://user-images.githubusercontent.com/38427877/208472797-5d83bf20-8f03-49ea-a2ec-3b676520a733.mp4
> 
> Do you trust me now? I told you it worked and it works. Now, if you are not able to understand what I say or fix basic Gradle issues, it's not my problem. You just need to read a page on the MCreator's Wiki.
> 
> 
> Next time, you open an issue. This is a ban from this repository. When I close an issue, this is to see it closed, not opened again. You have a real patience problem. I hope you will change your behaviour soon.


I am like this because at my age, you may also behaved like this.. (Sorry, if my English Grammar hurted you)

Age Hint: I just became a teenager. [Under 15]

**Comment by PSGitHubUser1** [comment]
> https://user-images.githubusercontent.com/38427877/208472797-5d83bf20-8f03-49ea-a2ec-3b676520a733.mp4
> 
> Do you trust me now? I told you it worked and it works. Now, if you are not able to understand what I say or fix basic Gradle issues, it's not my problem. You just need to read a page on the MCreator's Wiki.
> 
> 
> Next time, you open an issue. This is a ban from this repository. When I close an issue, this is to see it closed, not opened again. You have a real patience problem. I hope you will change your behaviour soon.


![IMG_20221220_070322.jpg](https://user-images.githubusercontent.com/90406016/208560413-1da864af-0e32-4890-9494-e86d0c2b6732.jpg)

Woah.. Procedures are partially supported..?
I thought they on the rank of "Partially Supported (Almost fully)" like Armor/Biomes  etc. I didn't knew about this.

**Comment by PSGitHubUser1** [comment]
> > @Goldorion
> > 
> > No. Please test it once.. Don't close, its not working as intended.
> 
> I tested hundred of times since I released the version... (without Fabric essentials)

It worked on reinstalling the FB Essentials..
(And enabling it, although I had enabled but was not working)
How in your case it worked without FB Essentials? That's more confusing..

**Comment by Goldorion** [comment]
> Woah.. Procedures are partially supported..?
Not all blocks are supported, most of global triggers were still unsupported (due to Fabric not having them) and global variables were not implemented before the last update. However, this chart is mainly representative. It doesn't mean a lot.
