### ISSUE TITLE
Custom Villager Professions

### ISSUE THREAD

**Issue by Atten007** [Goldorion/MCreatorFabricGenerator#354]
**Describe the feature**
Hi folks!

I want to create some Fabric Mods with new content for one of my friends. He's using a self-hosted Fabric Server and now I want, that villagers can trade these items in a custom, self defined profession that they're obtainable. But unfortunately, the generator doesn't support it yet, so the idea to support it came me. [Here](https://maven.fabricmc.net/docs/fabric-api-0.25.1+build.416-1.16/index.html?net/fabricmc/fabric/api/object/builder/v1/villager/VillagerProfessionBuilder.html) you can find the API for villager trades.

**Describe why you want the feature**
I want it because I'm making a city mod for a friend and he wants to have it in a custom profession.

**Additional context**
None

**Comment by PSGitHubUser1** [comment]
#349 Already created this feature request by me.. few days ago
