### ISSUE TITLE
Glowing record causes build failure

### ISSUE THREAD

**Issue by RegulusSource** [Goldorion/MCreatorFabricGenerator#355]
### Issue description

The build display failed when the disc was enabled with glow

### How to reproduce this issue?

1. Open a record

2. Enable the glow effect

### Operating system

Windows

### Details

![208687483-f5b7d37a-7ba0-4031-b16c-195b13008a1d](https://user-images.githubusercontent.com/90123607/208807174-983396a2-ea4a-43a5-aa86-eef53d072e34.png)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PSGitHubUser1** [comment]
Yes, you're right (I know this bug for long time, but I was trying to ignore it because I do not need of this for now) and you should have typed "music disc" instead of "record".

**Comment by Goldorion** [comment]
> Yes, you're right (I know this bug for long time, but I was trying to ignore it because I do not need of this for now) and you should have typed "music disc" instead of "record".

Its name in MojMaps is Record, so it's fine.

**Comment by NerdyPuzzle** [comment]
this should be a fairly simple fix, seems like a duplicate import thing.
