### ISSUE TITLE
The game crashed while loading two modules built by  FabricGenerator at the same time

### ISSUE THREAD

**Issue by RegulusSource** [Goldorion/MCreatorFabricGenerator#356]
### Issue description

I used FabricGenerator to create two mods that crashed when they were loaded at the same time (can be loaded separately)

### How to reproduce this issue?

Load two modules generated by FabricGenerator simultaneously

### Operating system

Windows

### Details

[crash-2022-12-22_17.04.05.6212-quilt_loader.txt](https://github.com/Goldorion/Fabric-Generator-MCreator/files/10285508/crash-2022-12-22_17.04.05.6212-quilt_loader.txt)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PSGitHubUser1** [comment]
Quilt loader? 
 But Fabric Generator is for Fabric..
 then how even 1 mod is working..? (IDK, I never used Quilt just listened about it)
I guess mixin caused the problem...

**Comment by Goldorion** [comment]
> Quilt loader? But Fabric Generator is for Fabric.. then how even 1 mod is working..? (IDK, I never used Quilt just listened about it) I guess mixin caused the problem...

Quilt is based on Fabric, so for the moment, some types of mods can work. However, I never intended to support Quilt with this Fabric Generator.

**Comment by PSGitHubUser1** [comment]
> > Quilt loader? But Fabric Generator is for Fabric.. then how even 1 mod is working..? (IDK, I never used Quilt just listened about it) I guess mixin caused the problem...
> 
> Quilt is based on Fabric, so for the moment, some types of mods can work. However, I never intended to support Quilt with this Fabric Generator.

Means the mods which are working seperately, it's just coincidence..
