### ISSUE TITLE
I made an entity then it Failed to build

### ISSUE THREAD

**Issue by ghost** [Goldorion/MCreatorFabricGenerator#357]
### Issue description

So i made a Spamton entity right? and then it sorta did a big oof when it tried to compile

### How to reproduce this issue?

Step 1. Make an entity.
Step 2. Click Save.
Step 3. Look in Console.
Step 4. See Error.

### Operating system

Windows

### Details

MCreator 2022.3.48217,
fabric-1.19.2,
Generator: Fabric Generator 1.8.1,
64-bit,
15205 MB,
Windows 10,
JVM 17.0.3
I am Using a Steam Deck if it helps, but i don't think that would cause the issue since i'm running on Windows 10 with all correct Drivers and such.

### Logs

https://pastebin.com/vyPE6rDB

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/84929796/209171104-cf2f84fd-3341-4568-842c-5b7d4ca1b864.png)

Line that is causing issue (according to mcreator) highlighted

**Comment by PSGitHubUser1** [comment]
Try to add "Fabric Essentials" plugin from mcreator.net/plugins 

Download & load the plugin then go to worksapce settings, then click on External APIs and then turn on "Fabric Essentials". And then save and click on "Yes, refactor workspace".

Maybe it solve the problem..?

**Comment by ghost** [comment]
oki i'll try

**Comment by ghost** [comment]
Alright so i did that and it did not work :(

https://pastebin.com/t6K2p5n5

**Comment by PSGitHubUser1** [comment]
Disable GekoLib I guess that's causing the problem.

**Comment by PSGitHubUser1** [comment]
@Foxxy-01, 

@NerdyPuzzle has fixed this problem by saying that "Fix particles import still being in the template". So when he releases the update, you just have to load the plugin (Fabric Generator/Fabric Essentials) and the problem maybe fixed. So wait for sometime until he posts a new update.
