### ISSUE TITLE
GUIs can compile and be loaded on Clients, but not on Servers.

### ISSUE THREAD

**Issue by Micasddsa** [Goldorion/MCreatorFabricGenerator#358]
### Issue description

(Yes, I did reuse the title from the last time.)
Mods with a GUI element can run on Clients but not on Servers. The crash notes are basically the same as from #262 witch is something in "main" not being able to load on server type.

### How to reproduce this issue?

Step 1. Make a GUI (it can be whatever you want)
Step 2. Save and Compile
Step 3. Run Server + Client
Step 4. The Server Crashes but not the Client.

### Operating system

Windows

### Details

MCreator 2022.4.52117 EAP (52117)
fabric-1.19.2

### Logs

```
Executing Gradle task: runClient 
Build info: MCreator 2022.4.52117 EAP (52117), fabric-1.19.2, 64-bit, 16332 MB, Windows 10, JVM 17.0.5, JAVA_HOME: C:\Users\Micasddsa\Downloads\MCreatorEAP20224b52117\jdk, started on: 2022-12-22-20:36:01 
  
> Configure project : 
Fabric Loom: 1.0.16 
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> Task :compileJava UP-TO-DATE 
> Task :processResources UP-TO-DATE 
> Task :classes UP-TO-DATE 
> Task :generateDLIConfig 
> Task :generateLog4jConfig 
> Task :generateRemapClasspath UP-TO-DATE 
> Task :configureLaunch 
> Task :runServer 
20:36.08 [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.19.2 with Fabric Loader 0.14.9 
20:36.08 main/INFO (FabricLoader) Loading 36 mods: 
   - fabric-api 0.67.1+1.19.2 
   - fabric-api-base 0.4.13+0d0f210290 
   - fabric-api-lookup-api-v1 1.6.12+93d8cb8290 
   - fabric-biome-api-v1 9.0.20+0d0f210290 
   - fabric-block-api-v1 1.0.1+12bfe4ea90 
   - fabric-command-api-v2 2.1.9+93d8cb8290 
   - fabric-content-registries-v0 3.4.3+6064db2a90 
   - fabric-convention-tags-v1 1.1.3+93d8cb8290 
   - fabric-crash-report-info-v1 0.2.7+aeb40ebe90 
   - fabric-data-generation-api-v1 5.3.1+ad31814d90 
   - fabric-dimensions-v1 2.1.33+0d0f210290 
   - fabric-entity-events-v1 1.5.2+9244241690 
   - fabric-events-interaction-v0 0.4.30+c6af733c90 
   - fabric-game-rule-api-v1 1.0.23+c6af733c90 
   - fabric-gametest-api-v1 1.1.4+704e47e990 
   - fabric-item-api-v1 1.6.1+fa140d5990 
   - fabric-item-groups-v0 0.3.35+9244241690 
   - fabric-lifecycle-events-v1 2.2.2+9244241690 
   - fabric-loot-api-v2 1.1.9+83a8659290 
   - fabric-message-api-v1 5.0.5+93d8cb8290 
   - fabric-mining-level-api-v1 2.1.20+33fbc73890 
   - fabric-networking-api-v1 1.2.7+9244241690 
   - fabric-object-builder-api-v1 4.1.2+06e0e25190 
   - fabric-particles-v1 1.0.12+79adfe0a90 
   - fabric-registry-sync-v0 0.9.28+9244241690 
   - fabric-rendering-data-attachment-v1 0.3.17+0d0f210290 
   - fabric-rendering-fluids-v1 3.0.9+c6af733c90 
   - fabric-resource-conditions-api-v1 2.1.1+aae9039d90 
   - fabric-resource-loader-v0 0.8.1+0d0f210290 
   - fabric-screen-handler-api-v1 1.3.3+1cc24b1b90 
   - fabric-transfer-api-v1 2.1.3+9d081d6490 
   - fabric-transitive-access-wideners-v1 1.3.2+42d99c3290 
   - fabricloader 0.14.9 
   - guitest 1.0.0 
   - java 17 
   - minecraft 1.19.2 
20:36.09 main/INFO (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C./Users/Micasddsa/.mcreator/gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/c1dc27696aa4006e492c2485c9ccbcb26045a971/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER 
20:36.10 [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper! 
20:36.11 [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_16 
20:36.11 [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_17 
20:36.15 main/WARN (FileUtil) Configuration conflict: there is more than one oshi.properties file on the classpath 
> Configure project : 
Fabric Loom: 1.0.16 
20:36.16 main/WARN (FileUtil) Configuration conflict: there is more than one oshi.architecture.properties file on the classpath 
20:36.27 [main/INFO] (Minecraft) Building unoptimized datafixer 
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> Task :compileJava UP-TO-DATE 
> Task :processResources UP-TO-DATE 
> Task :classes UP-TO-DATE 
> Task :generateDLIConfig 
> Task :generateLog4jConfig 
> Task :generateRemapClasspath UP-TO-DATE 
> Task :configureLaunch 
> Task :downloadAssets UP-TO-DATE 
> Task :configureClientLaunch 
20:36.34 [main/INFO] (GuitestMod) Initializing GuitestMod 
20:36.35 [main/ERROR] (Minecraft) Failed to start the minecraft server 
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'guitest'! 
   at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0([EntrypointUtils.java:51](file:///net.fabricmc.loader.impl.entrypoint.EntrypointUtils:51)) ~[fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions([ExceptionUtil.java:33](file:///net.fabricmc.loader.impl.util.ExceptionUtil:33)) ~[fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0([EntrypointUtils.java:49](file:///net.fabricmc.loader.impl.entrypoint.EntrypointUtils:49)) ~[fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke([EntrypointUtils.java:35](file:///net.fabricmc.loader.impl.entrypoint.EntrypointUtils:35)) ~[fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer([Hooks.java:62](file:///net.fabricmc.loader.impl.game.minecraft.Hooks:62)) ~[fabric-loader-0.14.9.jar:?] 
   at net.minecraft.server.Main.main([Main.java:105](file:///net.minecraft.server.Main:105)) [minecraft-project-@-merged-named.jar:?] 
   at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch([MinecraftGameProvider.java:461](file:///net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider:461)) [fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.launch.knot.Knot.launch([Knot.java:74](file:///net.fabricmc.loader.impl.launch.knot.Knot:74)) [fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.launch.knot.KnotServer.main([KnotServer.java:23](file:///net.fabricmc.loader.impl.launch.knot.KnotServer:23)) [fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.devlaunchinjector.Main.main([Main.java:86](file:///net.fabricmc.devlaunchinjector.Main:86)) [dev-launch-injector-0.2.1+build.8.jar:?] 
Caused by: java.lang.RuntimeException: Cannot load class net.minecraft.client.gui.screens.inventory.AbstractContainerScreen in environment type SERVER 
   at net.fabricmc.loader.impl.transformer.FabricTransformer.transform([FabricTransformer.java:59](file:///net.fabricmc.loader.impl.transformer.FabricTransformer:59)) ~[fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray([KnotClassDelegate.java:454](file:///net.fabricmc.loader.impl.launch.knot.KnotClassDelegate:454)) ~[fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray([KnotClassDelegate.java:407](file:///net.fabricmc.loader.impl.launch.knot.KnotClassDelegate:407)) ~[fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass([KnotClassDelegate.java:323](file:///net.fabricmc.loader.impl.launch.knot.KnotClassDelegate:323)) ~[fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass([KnotClassDelegate.java:218](file:///net.fabricmc.loader.impl.launch.knot.KnotClassDelegate:218)) ~[fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass([KnotClassLoader.java:145](file:///net.fabricmc.loader.impl.launch.knot.KnotClassLoader:145)) ~[fabric-loader-0.14.9.jar:?] 
   at java.lang.ClassLoader.loadClass([ClassLoader.java:520](file:///java.lang.ClassLoader:520)) ~[?:?] 
   at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] 
   at java.lang.ClassLoader.defineClass([ClassLoader.java:1012](file:///java.lang.ClassLoader:1012)) ~[?:?] 
   at java.security.SecureClassLoader.defineClass([SecureClassLoader.java:150](file:///java.security.SecureClassLoader:150)) ~[?:?] 
   at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd([KnotClassLoader.java:186](file:///net.fabricmc.loader.impl.launch.knot.KnotClassLoader:186)) ~[fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass([KnotClassDelegate.java:347](file:///net.fabricmc.loader.impl.launch.knot.KnotClassDelegate:347)) ~[fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass([KnotClassDelegate.java:218](file:///net.fabricmc.loader.impl.launch.knot.KnotClassDelegate:218)) ~[fabric-loader-0.14.9.jar:?] 
   at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass([KnotClassLoader.java:145](file:///net.fabricmc.loader.impl.launch.knot.KnotClassLoader:145)) ~[fabric-loader-0.14.9.jar:?] 
   at java.lang.ClassLoader.loadClass([ClassLoader.java:520](file:///java.lang.ClassLoader:520)) ~[?:?] 
   at net.mcreator.guitest.init.GuitestModMenus.load([GuitestModMenus.java:21](file:///net.mcreator.guitest.init.GuitestModMenus:21)) ~[main/:?] 
   at net.mcreator.guitest.GuitestMod.onInitialize([GuitestMod.java:30](file:///net.mcreator.guitest.GuitestMod:30)) ~[main/:?] 
   at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0([EntrypointUtils.java:47](file:///net.fabricmc.loader.impl.entrypoint.EntrypointUtils:47)) ~[fabric-loader-0.14.9.jar:?] 
   ... 7 more 
  
BUILD SUCCESSFUL in 34s 
6 actionable tasks: 3 executed, 3 up-to-date 
Task completed in 34 seconds
```

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PSGitHubUser1** [comment]
> ### Issue description
> (Yes, I did reuse the title from the last time.) Mods with a GUI element can run on Clients but not on Servers. The crash notes are basically the same as from #262 witch is something in "main" not being able to load on server type.
> 
> ### How to reproduce this issue?
> Step 1. Make a GUI (it can be whatever you want) Step 2. Save and Compile Step 3. Run Server + Client Step 4. The Server Crashes but not the Client.
> 
> ### Operating system
> Windows
> 
> ### Details
> MCreator 2022.4.52117 EAP (52117) fabric-1.19.2
> 
> ### Example workspace
> _No response_
> 
> ### Logs
> ```
> Executing Gradle task: runClient 
> Build info: MCreator 2022.4.52117 EAP (52117), fabric-1.19.2, 64-bit, 16332 MB, Windows 10, JVM 17.0.5, JAVA_HOME: C:\Users\Micasddsa\Downloads\MCreatorEAP20224b52117\jdk, started on: 2022-12-22-20:36:01 
>   
> > Configure project : 
> Fabric Loom: 1.0.16 
> Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> > Task :compileJava UP-TO-DATE 
> > Task :processResources UP-TO-DATE 
> > Task :classes UP-TO-DATE 
> > Task :generateDLIConfig 
> > Task :generateLog4jConfig 
> > Task :generateRemapClasspath UP-TO-DATE 
> > Task :configureLaunch 
> > Task :runServer 
> 20:36.08 [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.19.2 with Fabric Loader 0.14.9 
> 20:36.08 main/INFO (FabricLoader) Loading 36 mods: 
>    - fabric-api 0.67.1+1.19.2 
>    - fabric-api-base 0.4.13+0d0f210290 
>    - fabric-api-lookup-api-v1 1.6.12+93d8cb8290 
>    - fabric-biome-api-v1 9.0.20+0d0f210290 
>    - fabric-block-api-v1 1.0.1+12bfe4ea90 
>    - fabric-command-api-v2 2.1.9+93d8cb8290 
>    - fabric-content-registries-v0 3.4.3+6064db2a90 
>    - fabric-convention-tags-v1 1.1.3+93d8cb8290 
>    - fabric-crash-report-info-v1 0.2.7+aeb40ebe90 
>    - fabric-data-generation-api-v1 5.3.1+ad31814d90 
>    - fabric-dimensions-v1 2.1.33+0d0f210290 
>    - fabric-entity-events-v1 1.5.2+9244241690 
>    - fabric-events-interaction-v0 0.4.30+c6af733c90 
>    - fabric-game-rule-api-v1 1.0.23+c6af733c90 
>    - fabric-gametest-api-v1 1.1.4+704e47e990 
>    - fabric-item-api-v1 1.6.1+fa140d5990 
>    - fabric-item-groups-v0 0.3.35+9244241690 
>    - fabric-lifecycle-events-v1 2.2.2+9244241690 
>    - fabric-loot-api-v2 1.1.9+83a8659290 
>    - fabric-message-api-v1 5.0.5+93d8cb8290 
>    - fabric-mining-level-api-v1 2.1.20+33fbc73890 
>    - fabric-networking-api-v1 1.2.7+9244241690 
>    - fabric-object-builder-api-v1 4.1.2+06e0e25190 
>    - fabric-particles-v1 1.0.12+79adfe0a90 
>    - fabric-registry-sync-v0 0.9.28+9244241690 
>    - fabric-rendering-data-attachment-v1 0.3.17+0d0f210290 
>    - fabric-rendering-fluids-v1 3.0.9+c6af733c90 
>    - fabric-resource-conditions-api-v1 2.1.1+aae9039d90 
>    - fabric-resource-loader-v0 0.8.1+0d0f210290 
>    - fabric-screen-handler-api-v1 1.3.3+1cc24b1b90 
>    - fabric-transfer-api-v1 2.1.3+9d081d6490 
>    - fabric-transitive-access-wideners-v1 1.3.2+42d99c3290 
>    - fabricloader 0.14.9 
>    - guitest 1.0.0 
>    - java 17 
>    - minecraft 1.19.2 
> 20:36.09 main/INFO (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C./Users/Micasddsa/.mcreator/gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/c1dc27696aa4006e492c2485c9ccbcb26045a971/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER 
> 20:36.10 [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper! 
> 20:36.11 [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_16 
> 20:36.11 [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_17 
> 20:36.15 main/WARN (FileUtil) Configuration conflict: there is more than one oshi.properties file on the classpath 
> > Configure project : 
> Fabric Loom: 1.0.16 
> 20:36.16 main/WARN (FileUtil) Configuration conflict: there is more than one oshi.architecture.properties file on the classpath 
> 20:36.27 [main/INFO] (Minecraft) Building unoptimized datafixer 
> Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> > Task :compileJava UP-TO-DATE 
> > Task :processResources UP-TO-DATE 
> > Task :classes UP-TO-DATE 
> > Task :generateDLIConfig 
> > Task :generateLog4jConfig 
> > Task :generateRemapClasspath UP-TO-DATE 
> > Task :configureLaunch 
> > Task :downloadAssets UP-TO-DATE 
> > Task :configureClientLaunch 
> 20:36.34 [main/INFO] (GuitestMod) Initializing GuitestMod 
> 20:36.35 [main/ERROR] (Minecraft) Failed to start the minecraft server 
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'guitest'! 
>    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0([EntrypointUtils.java:51](file:///net.fabricmc.loader.impl.entrypoint.EntrypointUtils:51)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions([ExceptionUtil.java:33](file:///net.fabricmc.loader.impl.util.ExceptionUtil:33)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0([EntrypointUtils.java:49](file:///net.fabricmc.loader.impl.entrypoint.EntrypointUtils:49)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke([EntrypointUtils.java:35](file:///net.fabricmc.loader.impl.entrypoint.EntrypointUtils:35)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer([Hooks.java:62](file:///net.fabricmc.loader.impl.game.minecraft.Hooks:62)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.minecraft.server.Main.main([Main.java:105](file:///net.minecraft.server.Main:105)) [minecraft-project-@-merged-named.jar:?] 
>    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch([MinecraftGameProvider.java:461](file:///net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider:461)) [fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.launch.knot.Knot.launch([Knot.java:74](file:///net.fabricmc.loader.impl.launch.knot.Knot:74)) [fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.launch.knot.KnotServer.main([KnotServer.java:23](file:///net.fabricmc.loader.impl.launch.knot.KnotServer:23)) [fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.devlaunchinjector.Main.main([Main.java:86](file:///net.fabricmc.devlaunchinjector.Main:86)) [dev-launch-injector-0.2.1+build.8.jar:?] 
> Caused by: java.lang.RuntimeException: Cannot load class net.minecraft.client.gui.screens.inventory.AbstractContainerScreen in environment type SERVER 
>    at net.fabricmc.loader.impl.transformer.FabricTransformer.transform([FabricTransformer.java:59](file:///net.fabricmc.loader.impl.transformer.FabricTransformer:59)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray([KnotClassDelegate.java:454](file:///net.fabricmc.loader.impl.launch.knot.KnotClassDelegate:454)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray([KnotClassDelegate.java:407](file:///net.fabricmc.loader.impl.launch.knot.KnotClassDelegate:407)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass([KnotClassDelegate.java:323](file:///net.fabricmc.loader.impl.launch.knot.KnotClassDelegate:323)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass([KnotClassDelegate.java:218](file:///net.fabricmc.loader.impl.launch.knot.KnotClassDelegate:218)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass([KnotClassLoader.java:145](file:///net.fabricmc.loader.impl.launch.knot.KnotClassLoader:145)) ~[fabric-loader-0.14.9.jar:?] 
>    at java.lang.ClassLoader.loadClass([ClassLoader.java:520](file:///java.lang.ClassLoader:520)) ~[?:?] 
>    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] 
>    at java.lang.ClassLoader.defineClass([ClassLoader.java:1012](file:///java.lang.ClassLoader:1012)) ~[?:?] 
>    at java.security.SecureClassLoader.defineClass([SecureClassLoader.java:150](file:///java.security.SecureClassLoader:150)) ~[?:?] 
>    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd([KnotClassLoader.java:186](file:///net.fabricmc.loader.impl.launch.knot.KnotClassLoader:186)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass([KnotClassDelegate.java:347](file:///net.fabricmc.loader.impl.launch.knot.KnotClassDelegate:347)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass([KnotClassDelegate.java:218](file:///net.fabricmc.loader.impl.launch.knot.KnotClassDelegate:218)) ~[fabric-loader-0.14.9.jar:?] 
>    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass([KnotClassLoader.java:145](file:///net.fabricmc.loader.impl.launch.knot.KnotClassLoader:145)) ~[fabric-loader-0.14.9.jar:?] 
>    at java.lang.ClassLoader.loadClass([ClassLoader.java:520](file:///java.lang.ClassLoader:520)) ~[?:?] 
>    at net.mcreator.guitest.init.GuitestModMenus.load([GuitestModMenus.java:21](file:///net.mcreator.guitest.init.GuitestModMenus:21)) ~[main/:?] 
>    at net.mcreator.guitest.GuitestMod.onInitialize([GuitestMod.java:30](file:///net.mcreator.guitest.GuitestMod:30)) ~[main/:?] 
>    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0([EntrypointUtils.java:47](file:///net.fabricmc.loader.impl.entrypoint.EntrypointUtils:47)) ~[fabric-loader-0.14.9.jar:?] 
>    ... 7 more 
>   
> BUILD SUCCESSFUL in 34s 
> 6 actionable tasks: 3 executed, 3 up-to-date 
> Task completed in 34 seconds
> ```
> 
> ### Issue tracker rule checks (please read carefully)
> * [x]  I have checked that my problem [is not already reported](https://github.com/MCreator/MCreator/issues?q=is%3Aissue)
> * [x]  I have checked that my problem is not covered on [Knowledge Base](https://mcreator.net/support/knowledgebase) or on [MCreator's Wiki](https://mcreator.net/wiki)
> * [x]  I have checked that my written content does not violate the [publishing guidelines](https://mcreator.net/wiki/general-publishing-guidelines)

That's why I didn't update my workspace to 2022.4 snapshot.. 

You may have took backup use it. Snapshot are not whole version so they cause errors or maybe Fabric Generator has this bug. IDK, @Goldorion can confirm it. Wait it says *GuiTest* means it was just a test?

**Comment by Micasddsa** [comment]
I always use test workspaces. It guarantees a clean workspace and no other things would cause the issue that I am looking to report.
And no. It is not the new snapshot. I had this problem back in 2022.3, so it is not a 2022.4 snapshot exclusive bug.

**Comment by RFNMC** [comment]
I have the same problem, hope fix.

**Comment by 5ur3z** [comment]
> I always use test workspaces. It guarantees a clean workspace and no other things would cause the issue that I am looking to report. And no. It is not the new snapshot. I had this problem back in 2022.3, so it is not a 2022.4 snapshot exclusive bug.

Yes... I've try it on 2023.1, EAP20224b52117 and 2022.3. All these version have this bug. The client runs normally, but server crashed.

**Comment by 5ur3z** [comment]
Still not fix...
Please, this is very important to my server
