### ISSUE TITLE
Feature mod element does not show under the "add elements" option and the shortcut "f" does not work

### ISSUE THREAD

**Issue by hydrangea72** [Goldorion/MCreatorFabricGenerator#359]
### Issue description

There isn't really anything else to explain here. I tried this using a forge workspace and I can confirm it's not an issue with mcreator itself.

### How to reproduce this issue?

Step 1: Make a fabric workspace.
Step 2: Try to add a feature mod element.

### Operating system

macOS

### Details

MCreator 2022.4 EAP snapshot (the latest one)
latest generator version

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
![image](https://user-images.githubusercontent.com/38427877/209374403-dc437ee8-5796-42d5-b321-5f9e4245a26f.png)

**Comment by hydrangea72** [comment]
Still not there.

**Comment by hydrangea72** [comment]
Oh, my apologies, It seems I forgot to remove the old fabric generator version when installing the new one, and so it was overriding it or smth.
