### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by EpicGamer121** [Goldorion/MCreatorFabricGenerator#362]
When Will 1.19.3 be supported since i use 1.19.3

**Comment by Goldorion** [comment]
When users will understand we don't work full-time on it. It's just a hobby, so expect to have some delays with new MC versions, mainly when they change things.

**Comment by EpicGamer121** [comment]
> When users will understand we don't work full-time on it. It's just a hobby, so expect to have some delays with new MC versions, mainly when they change things.

but what happened to [Goldorion:1.19.3]
