### ISSUE TITLE
is [provided itemstack] of item type [entry] - blank list (2022.4 snapshot/1.8.2 plugin)

### ISSUE THREAD

**Issue by zsvan** [Goldorion/MCreatorFabricGenerator#363]
### Issue description

![image](https://user-images.githubusercontent.com/17712352/209726674-8a5a6a33-d9e5-4a63-8ba5-d2cfa006b1d0.png)

Forge generator properly lists available items, possible issue with this?

![image](https://user-images.githubusercontent.com/17712352/209726771-78630c01-a680-467a-b92f-6f65e0a27674.png)

Cheers

### How to reproduce this issue?

As in description

### Operating system

Windows

### Details

MCreator newest snapshot **2022.4 EAP (52117)**, using **Fabric Gen plugin version 1.8.2**

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PSGitHubUser1** [comment]
You shouldn't have done this, because its a snapshot version of MCreator. It has bugs..
Well, you may have made backup before doing this, use that backup..

**Comment by PSGitHubUser1** [comment]
I guess this is valid issue, also there is no option to summon 'sonic-boom' with right click on item and projectile blocks and its also not available in Forge version?

**Comment by NerdyPuzzle** [comment]
This is not a bug with the snapshot, it is a case of a missing file in the generator. But even if it was, it never would have been fixed if someone didn't report it, and for that to happen people need to use the snapshots.

**Comment by PSGitHubUser1** [comment]
oh ok.

**Comment by Goldorion** [comment]
The Fa1.18.2 Fabric Generator is neither made nor maintained by me. Please, report this bug to the appropriate issue tracker. https://github.com/NerdyPuzzle/MCreator-Fabric-Generator-1.18.2/issues
