### ISSUE TITLE
Potion item/Potion effect causing npe?

### ISSUE THREAD

**Issue by zsvan** [Goldorion/MCreatorFabricGenerator#364]
### Issue description

Trying to run client to test stuff, but I'm getting a crash at initialization.

### How to reproduce this issue?

I've attached my workspace. 

### Operating system

Windows

### Details

MCreator 2022.4 (52117)
Fabric gen 1.19.2 1.8.2
along with Fabric Essentials API

Also workspace uses File Manager 5.5

### Example workspace

[wr_fabric_1192.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/10321237/wr_fabric_1192.zip)

### Logs

https://gist.github.com/suckinsyn/96e3ceee482a8b3eea4619b3f783f488

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PSGitHubUser1** [comment]
I can't even understand the question.. [I am dumb]

**Comment by GalaxyGaming2000** [comment]
i updated still having same issue
