### ISSUE TITLE
Biome element fails to compile

### ISSUE THREAD

**Issue by hydrangea72** [Goldorion/MCreatorFabricGenerator#366]
### Issue description

When saving a biome element, the file does not compile, the error message says that "error: package terrablender.api not found" 
Is it not already installed with the base plugin?

### How to reproduce this issue?

Step 1: Make biome mod element.

### Operating system

macOS

### Details

MCreator 2022.3
Latest plugin version

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Enable the API

**Comment by hydrangea72** [comment]
How?

**Comment by dillpicklee** [comment]
> Enable the API

how does one do that? on windows i mean

**Comment by hydrangea72** [comment]
> Enable the API

how do you do that
