### ISSUE TITLE
Recipes are just overwriting/mixing in each other [READ DESC]

### ISSUE THREAD

**Issue by PSGitHubUser1** [Goldorion/MCreatorFabricGenerator#367]
### Issue description

Sorry but this is the bug which I can't define it properly.
When I build/regenerate code of the workspace after doing changes then randomly 
the recipes just overwrite or `mix with each other (but not all recipes)` 
See: 

![image](https://user-images.githubusercontent.com/90406016/210341317-ad5a462b-5eb7-4b11-9a74-b50b71133f8a.png)
![image](https://user-images.githubusercontent.com/90406016/210341512-667877d0-9a75-45b0-a47b-4b804feb7b20.jpg)
This is the problem!

![test](https://user-images.githubusercontent.com/90406016/210341951-054d2daa-a278-40ac-9db8-ac29fb3eb632.jpg)
It supposed to be this. IDK its the problem of the Generator or problem in the MCreator?

And I have to make the recipes again [many times, it doesn't overwrite but overwrites randomly!?]
Its like set at 25% or 33% to happen this!!?? Very confusing..

### How to reproduce this issue?

Step 1: Make recipes more than 3-4 
Step 2: Compile them 
Step 3: At ramdom chance, it will be overwritten but HOW?

### Operating system

Windows

### Details

MCreator version: 2022.3 _[and yes, this bug is existing before 2022.2. Although, I don't know its from starting or new]_
Fabric Generator version: 1.8.1 [Latest for 2022.3]
Fabric Essentials version: 1.6.3 [Latest]

### Logs

No logs are available to upload.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PSGitHubUser1** [comment]
Here is 1 more example:

![test2](https://user-images.githubusercontent.com/90406016/210347244-f28d2505-56e1-462f-b2c0-65b969e1427b.jpg)

Please fix this.. :|
 @Goldorion @kleiders3010 @NerdyPuzzle

**Comment by Micasddsa** [comment]
🤦
![image](https://user-images.githubusercontent.com/62626876/210401007-6bf05d8a-e960-417d-87b7-f600abeee6b0.png)
(Edit: Yes, this screenshot is from an issue you opened on Fabic Essentials but point stands. They already get notifications from opening this issue, you don't have to ping them to get MORE notifications in their inboxes.)

**Comment by Goldorion** [comment]
> 🤦 (Edit: Yes, this is from the Fabic Essentials and isn't said here but still. Point stands.)

It applies to all repositories and all projects, no matter the project.

**Comment by PSGitHubUser1** [comment]
:|| I guess I have low memory..
btw its a problematic bug. Please fix this ;(

**Comment by Micasddsa** [comment]
Being honest, this might be an MCreator issue.
I remember running into this bug on my fabic mod a long time ago and i worked a lot to resotre everything by deleting all the old recipes and remaking everything.
I don't _exactly_ see how this generator might be causing the issue unless you tested getting to bug with Forge Generators.

**Comment by kleiders3010** [comment]
MCreator "forgetting things" is a common issue, it depends a lot on PC performance. You won't find a solution other than making sure the element name matches the id to avoid any possible future issues (or lock the element after you are done with it, if you don't plan on editing it could avoid breaking it) @PSGitHubUser1

**Comment by PSGitHubUser1** [comment]
> MCreator "forgetting things" is a common issue, it depends a lot on PC performance. You won't find a solution other than making sure the element name matches the id to avoid any possible future issues (or lock the element after you are done with it, if you don't plan on editing it could avoid breaking it) @PSGitHubUser1 

Nope. It doesn't work on locking the elements, it still happen. Ok let me test it out in Forge one... If forge also show this problem then we can't do anything.. W- Wait can't I just make a Datapack of recipes??
With `namespace` of my mod?? it may work.. but no one will SCROLL DOWN and download the Datapack (Its also a problem) 

And should I report this problem to KlemenDev ? [Who made MCreator, he can fix that maybe?]

**Comment by smmmadden** [comment]
I heard that you can create a DataPack of recipes, but I have yet had time to do research on that.  It's very tedious to have to do the recipes over and over for all the huts in all the colonies I build.  I just wish the builders could just build what is asked and not have to worry about teaching all the huts how to do it.  :-)  If you figure it out, let me know.

**Comment by Goldorion** [comment]
The problem you are describing is clearly not a problem I could have introduced with the generator. In no case, this generator can affect how the UI is acting. If you can provide a way to always reproduce it, no matter the computer and the workspace, please open a bug report on the MCreator's repository. https://github.com/MCreator/MCreator/issues

**Comment by PSGitHubUser1** [comment]
Ok 🙂

**Comment by PSGitHubUser1** [comment]
Goldorion, He closed the issue. KlemenDEV is saying that if this happens in forge then, he can do something..
[I just updated to you, I am not saying to you to test it out.. I'll test it.] 😞 😐

I 'have' to confirm in forge, I can't always just delete the recipes and make them again.
