### ISSUE TITLE
Can’t create blocks

### ISSUE THREAD

**Issue by Techno573** [Goldorion/MCreatorFabricGenerator#368]
### Issue description

When creating a new block element on a workspace using the 1.8.2 version of the 1.19.2 fabric generator, along with the first snapshot of mcreator 2022.4, it will give a compiling error related to the block that has been just created after running the build task. This keeps happening even after regenerating the code. There’s not even a need to change any settings of the block for this to happen.

### How to reproduce this issue?

-create a new workspace
-create a new block element (doesn’t matter what attributes or textures you give to it)
-run the build task

### Operating system

Windows

### Details

MCreator EAP 2022.4.52117
Fabric Generator 1.8.2 (Minecraft 1.19.2)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PSGitHubUser1** [comment]
I have to test that.
[UPDATE]: I can't do that maybe.

**Comment by Micasddsa** [comment]
I have encountered this bug. was so annoying. legit switched my mod  to 1.18.2 forge to contineue deveopment.
However, every time i remember to submit a bug report, legit, i'm away from my pc so i can't get error logs 💀
You didn't give logs so i might be able to provide some. I think we are both encountering the same issue, even if i'm using the lastest dev build.

**Comment by Micasddsa** [comment]
Hey. Got the build log. Are you experiencing this? Check your build log.
```
Executing Gradle task: build 
Build info: MCreator 2022.4.52117 EAP (52117), fabric-1.19.3, 64-bit, 16332 MB, Windows 10, JVM 17.0.5, JAVA_HOME: C:\Users\Micasddsa\Documents\Micasddsa's Addons\MCreatorEAP20224b52117\jdk, started on: 2023-01-05-19:04:04 
  
> Configure project : 
Fabric Loom: 1.0.16 
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> Task :compileJava 
[C:\Users\Micasddsa\MCreatorWorkspaces\blocktest\src\main\java\net\mcreator\blocktest\init\BlocktestModBlocks.java:18](file:///C:/Users/Micasddsa/MCreatorWorkspaces/blocktest/src/main/java/net/mcreator/blocktest/init/BlocktestModBlocks.java:18): error: cannot find symbol 
      LOL = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(BlocktestMod.MODID, "lol"), new LolBlock()); 
                                                                                                            ^ 
  symbol:   class LolBlock 
  location: class BlocktestModBlocks 
[C:\Users\Micasddsa\MCreatorWorkspaces\blocktest\src\main\java\net\mcreator\blocktest\init\BlocktestModBlocks.java:22](file:///C:/Users/Micasddsa/MCreatorWorkspaces/blocktest/src/main/java/net/mcreator/blocktest/init/BlocktestModBlocks.java:22): error: cannot find symbol 
      LolBlock.clientInit(); 
      ^ 
  symbol:   variable LolBlock 
  location: class BlocktestModBlocks 
2 errors 
> Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 31s 
1 actionable task: 1 executed
```

**Comment by PSGitHubUser1** [comment]
> Hey. Got the build log. Are you experiencing this? Check your build log.
> 
> ```
> Executing Gradle task: build 
> Build info: MCreator 2022.4.52117 EAP (52117), fabric-1.19.3, 64-bit, 16332 MB, Windows 10, JVM 17.0.5, JAVA_HOME: C:\Users\Micasddsa\Documents\Micasddsa's Addons\MCreatorEAP20224b52117\jdk, started on: 2023-01-05-19:04:04 
>   
> > Configure project : 
> Fabric Loom: 1.0.16 
> Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> > Task :compileJava 
> [C:\Users\Micasddsa\MCreatorWorkspaces\blocktest\src\main\java\net\mcreator\blocktest\init\BlocktestModBlocks.java:18](file:///C:/Users/Micasddsa/MCreatorWorkspaces/blocktest/src/main/java/net/mcreator/blocktest/init/BlocktestModBlocks.java:18): error: cannot find symbol 
>       LOL = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(BlocktestMod.MODID, "lol"), new LolBlock()); 
>                                                                                                             ^ 
>   symbol:   class LolBlock 
>   location: class BlocktestModBlocks 
> [C:\Users\Micasddsa\MCreatorWorkspaces\blocktest\src\main\java\net\mcreator\blocktest\init\BlocktestModBlocks.java:22](file:///C:/Users/Micasddsa/MCreatorWorkspaces/blocktest/src/main/java/net/mcreator/blocktest/init/BlocktestModBlocks.java:22): error: cannot find symbol 
>       LolBlock.clientInit(); 
>       ^ 
>   symbol:   variable LolBlock 
>   location: class BlocktestModBlocks 
> 2 errors 
> > Task :compileJava FAILED 
> FAILURE: Build failed with an exception. 
> * What went wrong: 
> Execution failed for task ':compileJava'. 
> > Compilation failed; see the compiler error output for details. 
> * Try: 
> > Run with --stacktrace option to get the stack trace. 
> > Run with --info or --debug option to get more log output. 
> > Run with --scan to get full insights. 
> * Get more help at https://help.gradle.org 
> BUILD FAILED in 31s 
> 1 actionable task: 1 executed
> ```

Yes, not exactly this... I just cutted mod tab in frustration. So, I don't know it is or it's not.

**Comment by Micasddsa** [comment]
> > Hey. Got the build log. Are you experiencing this? Check your build log.
> > ```
> > Executing Gradle task: build 
> > Build info: MCreator 2022.4.52117 EAP (52117), fabric-1.19.3, 64-bit, 16332 MB, Windows 10, JVM 17.0.5, JAVA_HOME: C:\Users\Micasddsa\Documents\Micasddsa's Addons\MCreatorEAP20224b52117\jdk, started on: 2023-01-05-19:04:04 
> >   
> > > Configure project : 
> > Fabric Loom: 1.0.16 
> > Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> > > Task :compileJava 
> > [C:\Users\Micasddsa\MCreatorWorkspaces\blocktest\src\main\java\net\mcreator\blocktest\init\BlocktestModBlocks.java:18](file:///C:/Users/Micasddsa/MCreatorWorkspaces/blocktest/src/main/java/net/mcreator/blocktest/init/BlocktestModBlocks.java:18): error: cannot find symbol 
> >       LOL = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(BlocktestMod.MODID, "lol"), new LolBlock()); 
> >                                                                                                             ^ 
> >   symbol:   class LolBlock 
> >   location: class BlocktestModBlocks 
> > [C:\Users\Micasddsa\MCreatorWorkspaces\blocktest\src\main\java\net\mcreator\blocktest\init\BlocktestModBlocks.java:22](file:///C:/Users/Micasddsa/MCreatorWorkspaces/blocktest/src/main/java/net/mcreator/blocktest/init/BlocktestModBlocks.java:22): error: cannot find symbol 
> >       LolBlock.clientInit(); 
> >       ^ 
> >   symbol:   variable LolBlock 
> >   location: class BlocktestModBlocks 
> > 2 errors 
> > > Task :compileJava FAILED 
> > FAILURE: Build failed with an exception. 
> > * What went wrong: 
> > Execution failed for task ':compileJava'. 
> > > Compilation failed; see the compiler error output for details. 
> > * Try: 
> > > Run with --stacktrace option to get the stack trace. 
> > > Run with --info or --debug option to get more log output. 
> > > Run with --scan to get full insights. 
> > * Get more help at https://help.gradle.org 
> > BUILD FAILED in 31s 
> > 1 actionable task: 1 executed
> > ```
> 
> Yes, not exactly this... I just cutted mod tab in frustration. So, I don't know it is or it's not.

The message was directed twoards the author. Not you. Sorry if it seemed like it.
