### ISSUE TITLE
Plant element fails to compile

### ISSUE THREAD

**Issue by hydrangea72** [Goldorion/MCreatorFabricGenerator#370]
### Issue description

When creating a plant, regardless of how you make it, it does not compile. The error provided is below.
[https://www.dropbox.com/s/ac361gm2dupobjg/Screen%20Shot%202023-01-10%20at%205.56.55%20PM.png?dl=0](https://www.dropbox.com/s/ac361gm2dupobjg/Screen%20Shot%202023-01-10%20at%205.56.55%20PM.png?dl=0)

### How to reproduce this issue?

Step 1: Make a plant

### Operating system

macOS

### Details

MCreator 2022.4 EAP
Fabric Gen 1.8.3

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
It worked fine for me.

**Comment by hydrangea72** [comment]
Actually wait, I meant 1.8.1 not 1.8.3
and 2022.3

**Comment by CasterMx13** [comment]
I am having this exact same issue, I'm in the latest version of both Mcreator and FabricGen.
No type of plant will generate without those exact two errors. 
Should I open a new issue for it because it's in a later version than this one?
[planterror.txt](https://github.com/Goldorion/Fabric-Generator-MCreator/files/11013445/planterror.txt)
