### ISSUE TITLE
[BUG]:Unable to load!!!

### ISSUE THREAD

**Issue by Aigio1064** [Goldorion/MCreatorFabricGenerator#372]
### Issue description

Unable to load this plugin! Mr! I've tried restarting the software, tried other versions, and I'm sure the 1.19.2-1.8.3 version you compiled won't work! But 1.8.0 can...
If you don't understand, that's Bing's problem, and I use Bing to translate because Google's service is completely unavailable in China.
![image](https://user-images.githubusercontent.com/97342833/213014372-daca67a3-a8ca-4154-a04d-e7915415c33d.png)

### How to reproduce this issue?

So, how should I write?
Open settings?
Import plugins?
Restart the app?
Load failed?

### Operating system

Windows

### Details

Version of Mcreator: ["2022.3", "2022.2"], I only know that these two versions cannot be used because I was forced to upgrade Mcreator.
What the? Got the wrong version of Minecraft? Oh my God, you must be kidding me, right? Well, it's ["1.19.2"].

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I can just say it works, but you don't use the correct MCR version for the plugin version you downloaded.

**Comment by Aigio1064** [comment]
What the? Can't MCR version 2022.3 use this plugin?
