### ISSUE TITLE
Workspace Setup Error

### ISSUE THREAD

**Issue by Yweiwu30** [Goldorion/MCreatorFabricGenerator#373]
### Issue description

When I create a workspace on fabric generator, an error occurs.

This is the console log:

---
Fabric Loom: 1.0.17
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'mod'.
> Failed to notify project evaluation listener.
   > begin 0, end 16, length 12
   > Cannot get MinecraftProvider before it has been setup

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s

### How to reproduce this issue?

Step 1: Open or create a workspace on fabric generator
Step 2: ERROR

### Operating system

Windows

### Details

MCreator version: 2022.3 or 2022.4.52117 (I have tried both versions)
Generator type: fabric - 1.19.2 - 0.67.1

### Logs

https://gist.github.com/Yweiwu30/739a67b376a74ea67519cbdfeed9f86c

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PSGitHubUser1** [comment]
hmmm... which version are you using of Fabric generator?

>1.8.1.. or 1.8.2.. or 1.8.3/4 ....

**Comment by Goldorion** [comment]
Make sure you use the correct plugin version for the MCreator version you use.
