### ISSUE TITLE
A problem occurred after the "feature" element was updated

### ISSUE THREAD

**Issue by RegulusSource** [Goldorion/MCreatorFabricGenerator#375]
### Issue description

Generation problem after update to 2023.1

### How to reproduce this issue?

1.Create any "feature" in 2022.4
2.Update to 2023.1 and generate mods

### Operating system

Windows

### Details

MCreator version: [2022.4 Update to 2023.1]
Generator type: [fabric1.19.2-0.68.0]

### Example workspace

![image](https://user-images.githubusercontent.com/90123607/214617098-9a29cdeb-5766-4261-9e24-0083057cee83.png)

### Logs

D:\MCreatorWorkspaces\thprcL\src\main\java\chitem\indomitable\init\KunMixModFeatures.java:26: 错误: 找不到符号 
      register("zheshitexing", new ZheshitexingFeature(), ZheshitexingFeature.GENERATE_BIOMES, GenerationStep.Decoration.LAKES); 
                                   ^ 
  符号:   类 ZheshitexingFeature 
  位置: 类 KunMixModFeatures 
D:\MCreatorWorkspaces\thprcL\src\main\java\chitem\indomitable\init\KunMixModFeatures.java:26: 错误: 找不到符号 
      register("zheshitexing", new ZheshitexingFeature(), ZheshitexingFeature.GENERATE_BIOMES, GenerationStep.Decoration.LAKES); 
                                                          ^ 
  符号:   变量 ZheshitexingFeature 
  位置: 类 KunMixModFeatures

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Please provide more info like logs and a minimal reproducible workspace.

**Comment by RegulusSource** [comment]
[mcreator完整日志.txt](https://github.com/Goldorion/Fabric-Generator-MCreator/files/10509228/mcreator.txt)
Here's the full log I could find
The workspace file is too big. I can't upload it
