### ISSUE TITLE
How do I enable the terra blender API?

### ISSUE THREAD

**Issue by hydrangea72** [Goldorion/MCreatorFabricGenerator#377]
### Issue description

I reported an issue about biomes causing an erorr, and the response given was "enable the api" when there is no obvious way to do this.

### How to reproduce this issue?

wi

### Operating system

macOS

### Details

MCreator 2022.3
1.8.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Workspace settings -> External APIs

**Comment by hydrangea72** [comment]
It's not there. It does not show up as an option
