### ISSUE TITLE
[1.8.5] Potion Effect Crashes are not fixxed

### ISSUE THREAD

**Issue by GalaxyGaming2000** [Goldorion/MCreatorFabricGenerator#378]
### Issue description

I know that this was already reported but
when 1.8.5 released I downloaded it deleted the old versions
when I went to see if the issue was fixed I still get the same

"java.lang.NullPointerException: Cannot invoke "net.minecraft.world.effect.MobEffect.createFactorData()" because "mobEffect" is null"

its not because my workspace contains old code since I made new one to have the same issue
again I checked the plugin cashes and all that stuff

if its still fixed for you what could be happening for mine to still get the error.

(This error will also happen if you try to call the potion effect in a procedure, and if you manage to launch the game the /effect for your effect will be missing/insta crash game)

### How to reproduce this issue?

Step 1: Make potion effect
Step 2: Make potion effect item
Step 3: Launch the game.

### Operating system

Windows

### Details

MCreator snapshot 2023.1
Generator: Fabric 1.19.2 (latest)

### Issue tracker rule checks (please read carefully)

- [x] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by GalaxyGaming2000** [comment]
i will tinker around with the plugin / mcreator to see if i can fix this in anyway

**Comment by RandomGuy828** [comment]
Same Here

**Comment by Goldorion** [comment]
Make sure you deleted the old plugin version as it might override the newest version. I tested it in the game with the same setup that crashed the game and it worked correctly after the fix I applied.

**Comment by GalaxyGaming2000** [comment]
> Make sure you deleted the old plugin version as it might override the newest version. I tested it in the game with the same setup that crashed the game and it worked correctly after the fix I applied.

where can i check for them i checked plugins and pluginbackups
