### ISSUE TITLE
The process editor shows an error

### ISSUE THREAD

**Issue by RegulusSource** [Goldorion/MCreatorFabricGenerator#385]
### Issue description

![image](https://user-images.githubusercontent.com/90123607/219025821-9e68f028-b1a4-45d6-8047-2950f765ac23.png)
![image](https://user-images.githubusercontent.com/90123607/219025864-386f95e6-2f14-43c4-88ca-a8cd0812425d.png)
Process blocks overlap and cannot be used

### How to reproduce this issue?

Obviously, this is a problem whenever you use a process

### Operating system

Windows

### Details

2023.1EAP
1.19.2-0.68.0

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
This is not a problem with the generator.
