### ISSUE TITLE
Block drops requiring "tool harvest level to break with drop" are not respected on Fabric Generator

### ISSUE THREAD

**Issue by purejosh** [Goldorion/MCreatorFabricGenerator#387]
### Issue description

If I set tool harvest level to break with drop, it is not respected in game. For example, a value of 4 (should be netherite only) will still be breakable, and will drop, with a wooden pickaxe. 
![forge](https://user-images.githubusercontent.com/70633949/221421927-4ef0d759-33ea-42a0-915b-500226086779.gif)
![fabric](https://user-images.githubusercontent.com/70633949/221421928-93fa6e28-be5e-4bae-960f-8799a72da6b5.gif)
![image](https://user-images.githubusercontent.com/70633949/221422294-c95803ee-c9e0-4911-9f44-ad24bbda346a.png)

### How to reproduce this issue?

Create a block similar to my screenshot
Load it in fabric, observe that the tool harvest level requirement is not respected. 
Load it in forge, it'll be fine. 

### Operating system

Windows

### Details

Mcreator 2022.4 EAP 52117
Fabric Generator 1.7 beta 11
Fabric Essentials 1.7

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Please update to the latest version of the plugin. 1.7-beta-11 is very old and is not supported anymore.

**Comment by purejosh** [comment]
I didn't see any change logs mentioning a bug fix for this issue, so I didn't bother to try it.
