### ISSUE TITLE
Not working on 2023.1

### ISSUE THREAD

**Issue by Atten007** [Goldorion/MCreatorFabricGenerator#391]
### Issue description

Hello Goldorion,

Your fabric generator plugin for MCreator is good, but every time, when I start the app, it can't load the plugin with the reason "Incompatible version". I hope, that this can be fixed very soon because I have some mods on Fabric and I can't work on them because the plugin doesn't work!

- Atten007 😊

### How to reproduce this issue?

1. Download the plugin
2. Put it in the MCreator plugin folder
3. Start MCreator 2023.1
4. The plugin will not load

### Operating system

macOS

### Details

MCreator 2023.1 with macOS 13.2.1 on M1 MacBook Air.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I know, the update is coming soon (in the next hours).
