### ISSUE TITLE
[Request] Update the branch to 1.19.3 atleast as 1.19.4 is almost here. 

### ISSUE THREAD

**Issue by PSGitHubUser1** [Goldorion/MCreatorFabricGenerator#392]
`Everything is written in title` It is important to update the plugin as 1.19.4 is almost here. 

_BTW 1.20 is already released (almost) and I am expecting that MCreator 2023.2 will be supporting 1.20 also._

**Comment by 5ur3z** [comment]
Is it possible that the author has said that he does this part-time

**Comment by PSGitHubUser1** [comment]
Yes. I am not forcing him, just reminding him.

**Comment by Goldorion** [comment]
I'll do it when MCreator will update (because features changed quite a lot and it'll be easier and faster to take the work in MCreator than making it myself)
