### ISSUE TITLE
Cannot assign field "builtin" because "plugin" is null

### ISSUE THREAD

**Issue by blood210** [Goldorion/MCreatorFabricGenerator#394]
### Issue description

After I downloaded the fabric generator plugin, I loaded the plugin to MCreator. After I restarted MCreator, it said that the plugin couldn't load because "Cannot assign field "builtin" because "plugin" is null". I'm not java literate, nor code literate, so, I don't know what this means.

### How to reproduce this issue?

Step 1: Download MCreator
Step 2: Download Fabric Generator Plugin
Step 3: Load Fabric Generator Plugin to MCreator

### Operating system

Windows

### Details

MCreator Version 20231
Fabric Generator Plugin 1.19.2 1.8.6

### Logs

![image](https://user-images.githubusercontent.com/127356184/223871169-105ae02e-1dc0-4b6f-9149-aac2b341968d.png)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
The plugin simply doesn't allow the newest patch.

**Comment by blood210** [comment]
oh ok, thank you!
