### ISSUE TITLE
Error with mcreator special information on tools

### ISSUE THREAD

**Issue by 06NinjaKid06** [Goldorion/MCreatorFabricGenerator#395]
### Issue description

I got an error just from making a sword/tool and i dont know why

### How to reproduce this issue?

Make a tool,
Give it special information about the item,
Save it,
And you get an error.

### Operating system

Windows

### Details

Mcreator version: 2022.2
Generator version: fabric 1.19.2

### Logs

https://pastebin.com/BLTMTUhh

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Please update to the newest version as the bug has been fixed.
