### ISSUE TITLE
Game's crashing on using my mod with Sodium/Iris or more..? (MCreator)

### ISSUE THREAD

**Issue by PSGitHubUser1** [Goldorion/MCreatorFabricGenerator#396]
### Issue description

Please Read the `How to reproduce this issue?` and `Details (specially)`. 

I made a mod called 'PortDiscs' using MCreator [Fabric] which is a huge mod.

And its crashing when I put the Sodium/Iris mod, But why it is crashing as it ran easily before.

I have edited the the `fabric.mod.json` and it can run on 1.19-1.19.3 or It was already there? I forgot. 

### How to reproduce this issue?

Step 1: Export a mod/huge mod (?)
Step 2: Place into Mod's folder
Step 3: Run Minecraft 1.19.2 with JDK 17.0.5/6 [Fabric]
Step 4: It will crash and to solve it, just remove the best fabric mod called Sodium and Iris (more maybe, not tested on everyting).

### Operating system

Windows

### Details

MCreator: 2023.1 [Latest, 2023110219/b10219]
Fabric Generator: v1.8.7 (latest)
Fabric Essentials: v1.7 (latest)
Entity Textures Features: v1.1.1 (latest)
TerraBlender API (NerdyPuzzle): v1.3 (latest but last updated 2 months ago, I think this is causing Problem)

===============

Windows 11 Release Preview Build 22621.1344 (latest)
RAM: 8 GB
Processor: Intel i5 8th Gen, 4 Cores and 8 Threads

### Example workspace

_Can't as the workspace is of 40 MB._
_But take this in [MediaFire](https://www.mediafire.com/file/6nz9x4cico0bv4r/PortDiscs-0.4-workspace.zip/file)._ 

### Logs

[Gist Log 1](https://gist.github.com/PSGitHubUser1/510ad366ed598cb2264a9d946000a58c)
[Gist Log 2 (Not useful maybe)](https://gist.github.com/PSGitHubUser1/7181095236c4f0cea3104319ccbde2d1)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PSGitHubUser1** [comment]
What Do I do now? Is there any temp. solution?

**Comment by Goldorion** [comment]
I didn't test yet

**Comment by Goldorion** [comment]
You are trying to use a 1.19.2 mod in 1.19.3, so it will of course cause a problem.
