### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by iFrzdy** [Goldorion/MCreatorFabricGenerator#399]
### Issue description

Hello, I had some errors when uploading my mod to the server and it doesn't work, I don't know if gecko lib had something to do with this due to the render armors error.

### How to reproduce this issue?

create an armor with gecko lib and some mobs

### Operating system

Windows

### Details

mcreator 2023.1 latest version fabric 1.19.2 also latest version

### Example workspace

![mmm1](https://user-images.githubusercontent.com/121781881/224522380-67ebd0cb-f2d4-4ead-aef0-7a8f0928582f.PNG)
mi workspace

### Logs

https://pastebin.com/raw/kpTkZS5b

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [x] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
It seems to be a problem with your custom armor model. It's not on my side.
