### ISSUE TITLE
Do I use 0.3.0 or 0.4.1?

### ISSUE THREAD

**Issue by VexianEmpire** [Goldorion/MCreatorFabricGenerator#4]
0.4.1 doesn't have the 2020.3 only message, but since it came after 0.4.0, it might still be 2020.3 only despite not having the message, but I'm not sure since it doesn't have the message.

**Comment by Goldorion** [comment]
What message are you talking about?

**Comment by VexianEmpire** [comment]
> **Warning: Only works for the new 2020.3 snapshot!**

**Comment by Goldorion** [comment]
Oh ok. I always suggest to use the last version as there is more features, and less bugs with oldest features. The last version has been tested and made for the second snapshot of the 2020.3, but it should also work with the third snapshot (the pre-release). A new version should be available soon anyways (for the third snapshot only).

**Comment by VexianEmpire** [comment]
But I don't have 2020.3 snapshot I only have 2020.2

**Comment by Goldorion** [comment]
So wait the release of the 2020.3. 🤷‍♂️
