### ISSUE TITLE
Entity Gradle Compile Issue

### ISSUE THREAD

**Issue by ghost** [Goldorion/MCreatorFabricGenerator#403]
### Issue description

Whenever I attempt to build my mod, I get a compile issue from my entity's code. I have tried resolving this with geckolib and fabric essentials, though these didn't help.

### How to reproduce this issue?

Step 1. Created entity, with the zombie AI.
Step 2. Ported mod from forge to fabric, with entity.

### Operating system

Windows

### Details

MCreator - 2023.1
Generator type - Fabric 1.19.2

### Example workspace

[example.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/11241162/example.zip)

### Logs

Configure project : 
Fabric Loom: 1.0.18 
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix. 
> Task :compileJava FAILED 
[C:\Users\antho\Downloads\zjc\src\main\java\net\mcreator\zombiejimcarrey\init\ZombieJimCarreyModEntities.java:18](file:///C:/Users/antho/Downloads/zjc/src/main/java/net/mcreator/zombiejimcarrey/init/ZombieJimCarreyModEntities.java:18): error: cannot find symbol 
   public static EntityType<ZombiejimEntity> ZOMBIEJIM; 
                            ^ 
  symbol:   class ZombiejimEntity 
  location: class ZombieJimCarreyModEntities 
1 error 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 2s 
1 actionable task: 1 executed

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
It doesn't seem to cause a problem in 1.20, so I'm closing the issue.
