### ISSUE TITLE
1.19.4?

### ISSUE THREAD

**Issue by GGSkyOne** [Goldorion/MCreatorFabricGenerator#404]
### Feature description

Hey! You have any plans to update this generator to 1.19.4 and 1.20 in a future?

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
After MCreator will support 1.19.4 and when I'll the time to work on it.
