### ISSUE TITLE
Support for 1.19.4 Fabric

### ISSUE THREAD

**Issue by PSGitHubUser1** [Goldorion/MCreatorFabricGenerator#406]
### Feature description

I asked this because MCreator started supporting 1.19.4 slightly by the new snapshot. (2023.2.XX). Goldorion may start working when the MCreator will support 1.19.4 fully. 

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
No need for that. Italready the next thing I'll do

**Comment by PSGitHubUser1** [comment]
Oh ok. Sounds great.
