### ISSUE TITLE
[Feature Request] "Replace Block" procedure

### ISSUE THREAD

**Issue by ultimateimmersion** [Goldorion/MCreatorFabricGenerator#407]
### Feature description

Afaik that one uses NBT wtich is a forge feature hence probably the reason why it wasn't added yet.
Are there any workarounds or plans to make such procedure work?

I tried Fabric Essentials and that does not make it work for me.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
The block is already supported by the generator for a long time...
