### ISSUE TITLE
Key Bindings prevent server from start up

### ISSUE THREAD

**Issue by tiltproof69** [Goldorion/MCreatorFabricGenerator#408]
When I don't have any keybind elements in my workspace, then everything works fine, the server starts up normally. However when I create any keybind, the server won't start up, with an indication that key binding can't be ran in a server environment.

How to recreate:
-create a keybind (no need to attach procedures to it)
-try to start a server
![image](https://user-images.githubusercontent.com/98851333/235719845-c308450e-1b90-4ddb-940a-174c1c8590f8.png)

**Comment by Goldorion** [comment]
Fixed by https://github.com/Goldorion/Fabric-Generator-MCreator/commit/721b70aa574ab3c0582dca0e0bfc9576390a15e5
