### ISSUE TITLE
Player Persistent Variables

### ISSUE THREAD

**Issue by tiltproof69** [Goldorion/MCreatorFabricGenerator#409]
### Feature description

As for now there are available GLOBAL_MAP, GLOBAL_SESSION, and GLOBAL_WORLD variable types. It would be great if PLAYER_PERSISTENT joined that team :)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
It can not be easily added with Vanilla and Fabric API only for the moment, so use Fabric Essentials until the situation changes https://mcreator.net/plugin/92672/fabric-essentials
