### ISSUE TITLE
[BUG] Cannot run the workspace

### ISSUE THREAD

**Issue by ghost** [Goldorion/MCreatorFabricGenerator#41]
**Describe the bug**
When I create a new workplace using Fabric Generator it creates the workplace, but when I try to run the workspace it crashes because of the biome registry (as far as I can understand). It was just a test workspace so there isn't any mod elements. I provided the latest MCreator log, gradle task and the biome registry below.

**Affected version(s)**
MCreator Version: 2020.4.28114
Generator Version: v0.6.1

**To Reproduce**
1. Create a new workplace
2. Run minecraft

**Expected behavior**
Run Minecraft without a problem.

**Additional context**
Latest MCreator Log: https://controlc.com/29a4f808
Gradle Task: https://controlc.com/2c0aa6da
Biome Registry: https://controlc.com/27d68101

**Comment by BoogieMonster1O1** [comment]
Try regenerating all code. Seems to be that a class isn't getting imported. Also, try running the plugin without any others to get a more concise log.

**Comment by ghost** [comment]
I regenarated all code and even created a new test workplace and both of them didn't worked. I also removed all plugins except Fabric Generator and added the latest log to the issue (Latest MCreator Log).

**Comment by Goldorion** [comment]
It's not a generator problem. It is something inside the code of the ModBiomes class.

**Comment by BoogieMonster1O1** [comment]
I'll fix this in a few hours. Thanks for reporting it!
