### ISSUE TITLE
Hardness and harvest level doesn't correspond

### ISSUE THREAD

**Issue by Saturn1B** [Goldorion/MCreatorFabricGenerator#410]
### Issue description

I've tried creating a new block of gold variant, set it's hardness value at 3 and harvest level at 2, the same as gold block, but I can still mine it with a wooden axe and much more quickly than it should be.

### How to reproduce this issue?

1 - Create a project in mcreator 2023.1 with fabric generator for 1.19.2
2 - Create a new block
3 - Set it's hardness value and and harvest level in properties
4 - Save mod element
5 - Run client
6 - Constat

### Operating system

Windows

### Details

Mcreator version 2023.1
Generator for Fabric 1.19.2 - 0.67.1

### Example workspace

https://drive.google.com/file/d/18t65xbcf8V066F08OkYbHYiqc_s1GLod/view?usp=sharing

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Katalijst** [comment]
@Goldorion Does the same for me, I don't see any code generated related to the "Tool harvest level".
Tested on version 1.9.7

**Comment by purejosh** [comment]
This was present in my previous report #387, and it's still present in 1.9.9. Just realized my new mod will be completely pointless to release, since it relies on mining levels to prevent progression jumps.

**Comment by purejosh** [comment]
Additionally, I did sanity check this in Forge, and it operates with no issues. Probably a simple syntax error in the block's java file.

**Comment by Goldorion** [comment]
> This was present in my previous report #387, and it's still present in 1.9.9. Just realized my new mod will be completely pointless to release, since it relies on mining levels to prevent progression jumps.

If you have the fix, you're welcome to open a PR (even if I have an idea to improve a little bit the system I think)

**Comment by purejosh** [comment]
If I have some free time this weekend, I'll take a look at it. 👍

**Comment by purejosh** [comment]
Mining levels in Fabric are controlled via tags. 
https://fabricmc.net/wiki/tutorial:mining_levels

**Comment by Goldorion** [comment]
And this is how it's done in the generator too.

**Comment by purejosh** [comment]
I was able to fix it. The tag folder you're putting the .json into is incorrect. 

If you're using `needs_diamond_tool.json`, it goes in `\src\main\resources\data\minecraft\tags\blocks`.
If you're using `needs_tool_level_N.json`, it goes in `\src\main\resources\data\fabric\tags\blocks`.

The `needs_tool_level_N` tag needs to be in `blocks`, not in `mineable`. Moving the files from `\src\main\resources\data\fabric\tags\blocks\mineable` up one directory to `\src\main\resources\data\fabric\tags\blocks` and reloading the game fixed the issue. 

I submitted a PR to update the yaml, to get the right directory for the tag. 🙂

![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/70633949/0205d85f-7ec0-4239-9c28-5ead2a152a17)
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/70633949/6a05353d-04d1-4027-aab6-a6ebc7c6b558)

**Comment by purejosh** [comment]
In `block.definition.yaml`:

```
  - template: block/mineable_level_tag.json.ftl
    writer: json
    variables: level=0
    name: "@RESROOT/data/fabric/tags/blocks/needs_tool_level_0.json"
  - template: block/mineable_level_tag.json.ftl
    writer: json
    variables: level=1
    name: "@RESROOT/data/fabric/tags/blocks/needs_tool_level_1.json"
  - template: block/mineable_level_tag.json.ftl
    writer: json
    variables: level=2
    name: "@RESROOT/data/fabric/tags/blocks/needs_tool_level_2.json"
  - template: block/mineable_level_tag.json.ftl
    writer: json
    variables: level=3
    name: "@RESROOT/data/fabric/tags/blocks/needs_tool_level_3.json"
  - template: block/mineable_level_tag.json.ftl
    writer: json
    variables: level=4
    name: "@RESROOT/data/fabric/tags/blocks/needs_tool_level_4.json"
  - template: block/mineable_level_tag.json.ftl
    writer: json
    variables: level=5
    name: "@RESROOT/data/fabric/tags/blocks/needs_tool_level_5.json"
  - template: block/mineable_level_tag.json.ftl
    writer: json
    variables: level=6
    name: "@RESROOT/data/fabric/tags/blocks/needs_tool_level_6.json"
  - template: block/mineable_level_tag.json.ftl
    writer: json
    variables: level=7
    name: "@RESROOT/data/fabric/tags/blocks/needs_tool_level_7.json"
```

**Comment by bombaatomowa123456** [comment]
does it happen on 1.19.2 please tell me
