### ISSUE TITLE
[Request] Fabric Loader Update

### ISSUE THREAD

**Issue by Kuschelcraft** [Goldorion/MCreatorFabricGenerator#411]
### Feature description

Is it possible to update the fabric loader to 0.14.19, so you can implement mods like create fabric in the mod.
i'm currently trying to make a mod which adds new recipes for the create crusher.
(sorry for bad spelling, i'm from germany and by english is bad)
Kuschelcraft.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Micasddsa** [comment]
This generator is for creating new fabric mods and isn't geared to make addons to other mods. If you want support for Create, either ask someone else to make a MCreator plugin that has scripts and procedures for Create or make it yourself.

Goldorion might update the fabric loader but defintely won't and add support to any mods.

**Comment by Goldorion** [comment]
The generator already uses Fabric Loader 0.14.9 
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/38427877/14527364-6b84-4de0-976f-c8f24cbb6c40)

**Comment by Micasddsa** [comment]
wait, that says 0.14.9 but the version they are talking about is 0.14.19.

i checked the fabric loader version list and 0.14.19 is a real version.

**Comment by Kuschelcraft** [comment]
> This generator is for creating new fabric mods and isn't geared to make addons to other mods. If you want support for Create, either ask someone else to make a MCreator plugin that has scripts and procedures for Create or make it yourself.
> 
> Goldorion might update the fabric loader but defintely won't and add support to any mods.

No, the implementation for create works, but create only runs on fabric loader 0.14.10+

**Comment by Kuschelcraft** [comment]
> wait, that says 0.14.9 but the version they are talking about is 0.14.19.
> 
> i checked the fabric loader version list and 0.14.19 is a real version.

Thanks

**Comment by Goldorion** [comment]
> wait, that says 0.14.9 but the version they are talking about is 0.14.19.
> 
> i checked the fabric loader version list and 0.14.19 is a real version.

... wait... I'm so blind 🤣🤣 this is why it told me I wasn't with 0.14.19 yesterday in 1.19.4 😅😆 Sorry for that! I'll update it!

**Comment by Kuschelcraft** [comment]
Thanks

**Comment by Goldorion** [comment]
Fixed with https://github.com/Goldorion/Fabric-Generator-MCreator/commit/f7e2080c4c8ceb1d9b0ba725f67596c71d7c7173
