### ISSUE TITLE
Legacy Fabric support

### ISSUE THREAD

**Issue by vico93** [Goldorion/MCreatorFabricGenerator#415]
### Feature description

Legacy Fabric ([Website](https://legacyfabric.net/) / [Github](https://github.com/Legacy-Fabric/)) is a project based on the Fabric Project. Its two main priorities are to keep parity with upstream and to support as many legacy versions as possible. It currently support versions: 1.3 to 1.13.2

Being able to make LF mods on Mcreator would open up wide possibilities for that loader, specially for ports of MCreator mods for Forge to LF.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
But it won't happen with me or with anyone else because it's not possible with used Java version.

Even if it was possible, I won't make it. It's old, outdated, unsupported and useless with new Minecraft versions.

**Comment by vico93** [comment]
I disagree with the second part because there's a lot of people on 1.12 due to be the last pre-flattening update (and for performance reasons).

But well, cest la vie... 🤷🏻

**Comment by Goldorion** [comment]
1.12.2 is old, it's fact. It has been released in 2017.
1.12.2 is unsupported. Mojang, Microsoft don't support it. Even Forge doesn't support it anymore.
1.12.2 is useless with newest versions because everything 1.12.2 has, newest versions also have it with even more features, systems and possibilities. You can have a 1.12.2 generator if you want and if you're able to make it work, but you'll have 30% of current MCreator features 🤷‍♀️

I'm talking about facts. If you're not happy with this, you can still make your own generator. Nobody is telling you to not make it yourself or to ask another person to make it for you. I'm just saying that as it's my generator, I support versions I want to support and version(s) I want to support is/are the the newest ones. That's all. I'm making it (almost) alone and for free, so I take the decisions regarding the supported versions.

**Comment by vico93** [comment]
> 1.12.2 is old, it's fact. It has been released in 2017. 1.12.2 is unsupported. Mojang, Microsoft don't support it. Even Forge doesn't support it anymore. 1.12.2 is useless with newest versions because everything 1.12.2 has, newest versions also have it with even more features, systems and possibilities. You can have a 1.12.2 generator if you want and if you're able to make it work, but you'll have 30% of current MCreator features 🤷‍♀️
> 
> I'm talking about facts. If you're not happy with this, you can still make your own generator. Nobody is telling you to not make it yourself or to ask another person to make it for you. I'm just saying that as it's my generator, I support versions I want to support and version(s) I want to support is/are the the newest ones. That's all. I'm making it (almost) alone and for free, so I take the decisions regarding the supported versions.

No need to be rude. I just stated that although i disagree with the part that 1.12 is useless, but accepted your choice.
Alas, about the versioning aspect, Minecraft is totally different from other games and softwares. While its norm to other softwares that each update surpasses the older versions, in Minecraft there is the artistic decisions the game is taking (specially after the Microsoft purchase) not only artistic but also technical. The datapack system is totally confusing for newbies while similar solutions for pre-1.12 versions are far more intuitive than what Mojang/Microsoft added in vanilla. The Deep Dark

Plus, when you insinuate that it's a "waste of time" to develop for old versions, you disrespect the work of those who chose to go with an old version, like the Legacy Fabric team. I don't think it's fine the way you teased them. As I said, it's totally valid whether or not you accept a suggestion, but to demean the work of other modders who are also doing it for free is ridiculous. How would you feel if someone said that creating plugins for MCreator (or using MCreator at all) is a waste of time and something that "poison" the Minecraft modding scene (since many others says that Mcreator outputs bad code that is hard to maintain and is prone to break compatibility to other mods)?

So, just saying "1.12 iS oLd AnD uSeLeSs" isnt a real argument against older Minecraft versions. Of course, you isn't forced to add support for any specific version (and it wasn't what i meant creating this issue, i was just probing if there was interest on your part), just like i suppose you weren't held at point blank to be forced to create the project at all, so if you are doing it for free or not, its your choice, I have nothing to do with it.

**Comment by Goldorion** [comment]
> Plus, when you insinuate that it's a "waste of time" to develop for old versions, you disrespect the work of those who chose to go with an old version, like the Legacy Fabric team. I don't think it's fine the way you teased them.

My objective is not to disrespect people still working on old versions. I only wanted to say that in my opinion, there's no point on working on old versions. It's even more important when I'm currently the only Fabric generator for MCreator (working on it almost alone). So, I have to take the decision of making it as the official generators, so most users can simply port their mods to it or stay on an old version used by a few users only.

> How would you feel if someone said that creating plugins for MCreator (or using MCreator at all) is a waste of time and something that "poison" the Minecraft modding scene

We hear this all the time, so in all honestly, I don't care. I'm having fun with what I'm doing.


Anyways, my point wasn't to be rude to someone. I simply wanted to make things clear and my point of view (and a POV shared by most, if not all, (main) MCreator contributors) about the topic. So for the answer to the feature request. No, I won't do it. It's old with no features compared to new versions, it won't work with MCreator and it's way too hard with all the (very) bad systems Mojang had before.
