### ISSUE TITLE
[INFO NEEDED] Build File Location

### ISSUE THREAD

**Issue by darkwolfie37** [Goldorion/MCreatorFabricGenerator#416]
Hey!

I want to make a custom action for building and uploading a built mod file from MCreator. I already know how Forge Generators work because I've had to help a Friend.

So I am stuck on where the file is at because I cant seem to find one. 

Please let me know ASAP! <3

**Comment by Goldorion** [comment]
"build/libs/modid-1.0.0.jar"

**Comment by darkwolfie37** [comment]
Thank you!

**Comment by Goldorion** [comment]
However, pressing the button to export the mod will literally give you this file.

**Comment by darkwolfie37** [comment]
@Goldorion, I do know that, but Building it on GitHub is alot faster then my actual garbage pc. Hence why I asked.
