### ISSUE TITLE
Support for Cave Biomes

### ISSUE THREAD

**Issue by mateus3c** [Goldorion/MCreatorFabricGenerator#417]
### Feature description

'Generate biome in overworld caves?' were added on MCreator 2023.1 but the fabric generator doesnt support this. It would be amazing to create new cave biomes for the newer versions of Minecraft! 
Thank you.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by NerdyPuzzle** [comment]
#520
