### ISSUE TITLE
Fabric Generator 1.19.4 fails to load

### ISSUE THREAD

**Issue by Atten007** [Goldorion/MCreatorFabricGenerator#418]
### Issue description

Hello!

I want to have my Pokémon mod on Forge 1.19.4 and on Fabric 1.19.4, so I downloaded the plug-in here from the GitHub repo. But unfortunately, the gradle wrapper in this plugin fails to load because "Can assign field builtin because plugin is null". Can you fix this, so I can make a Fabric version of my mod?

Greetings,
Atten

### How to reproduce this issue?

1. Download the plugin from the 1.19.4 branch
2. Put it into the plugins folder of MCreator
3. It won't load and show the above error.

### Operating system

macOS

### Details

MCreator 2023.2.20712, Java 17.0.6 and Fabric 1.19.4

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
...
