### ISSUE TITLE
1.19.2 fabric server will not start with mod

### ISSUE THREAD

**Issue by caffiendly** [Goldorion/MCreatorFabricGenerator#419]
### Issue description

i dragged and dropped 1.19.2 fabric api and my mod (sacrificesmp) into the server host mod folder after having successfully launched it in single player and received this error message. 

being that i use mcreator i   obviously dont know how to actually read or comprehend what any of this means and it would be greatly appreciated if you could help me.

02.06 11:15:52 [PebbleHost Loader] -----------------------------------
02.06 11:15:52 [Server] [INFO] Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
02.06 11:15:53 [Server] main/[INFO] Loading Minecraft 1.19.2 with Fabric Loader 0.14.21
02.06 11:15:53 [Server] main/[INFO] Loading 42 mods:
02.06 11:15:53 [Server] [INFO] - fabric-api 0.76.0+1.19.2
02.06 11:15:53 [Server] [INFO] |-- fabric-api-base 0.4.15+8f4e8eb390
02.06 11:15:53 [Server] [INFO] |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
02.06 11:15:53 [Server] [INFO] |-- fabric-biome-api-v1 9.1.1+16f1e31390
02.06 11:15:53 [Server] [INFO] |-- fabric-block-api-v1 1.0.2+e415d50e90
02.06 11:15:53 [Server] [INFO] |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
02.06 11:15:53 [Server] [INFO] |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
02.06 11:15:53 [Server] [INFO] |-- fabric-command-api-v1 1.2.16+f71b366f90
02.06 11:15:53 [Server] [INFO] |-- fabric-command-api-v2 2.2.1+413cbbc790
02.06 11:15:53 [Server] [INFO] |-- fabric-commands-v0 0.2.33+df3654b390
02.06 11:15:53 [Server] [INFO] |-- fabric-containers-v0 0.1.41+df3654b390
02.06 11:15:53 [Server] [INFO] |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
02.06 11:15:53 [Server] [INFO] |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
02.06 11:15:53 [Server] [INFO] |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
02.06 11:15:53 [Server] [INFO] |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
02.06 11:15:53 [Server] [INFO] |-- fabric-dimensions-v1 2.1.35+0d0f210290
02.06 11:15:53 [Server] [INFO] |-- fabric-entity-events-v1 1.5.4+9244241690
02.06 11:15:53 [Server] [INFO] |-- fabric-events-interaction-v0 0.4.34+562bff6e90
02.06 11:15:53 [Server] [INFO] |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
02.06 11:15:53 [Server] [INFO] |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
02.06 11:15:53 [Server] [INFO] |-- fabric-item-api-v1 1.6.6+b7d1888890
02.06 11:15:53 [Server] [INFO] |-- fabric-item-groups-v0 0.3.39+9244241690
02.06 11:15:53 [Server] [INFO] |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
02.06 11:15:53 [Server] [INFO] |-- fabric-keybindings-v0 0.2.23+df3654b390
02.06 11:15:53 [Server] [INFO] |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
02.06 11:15:53 [Server] [INFO] |-- fabric-loot-api-v2 1.1.13+83a8659290
02.06 11:15:53 [Server] [INFO] |-- fabric-loot-tables-v1 1.1.16+9e7660c690
02.06 11:15:53 [Server] [INFO] |-- fabric-message-api-v1 5.0.7+93d8cb8290
02.06 11:15:53 [Server] [INFO] |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
02.06 11:15:53 [Server] [INFO] |-- fabric-models-v0 0.3.21+c6af733c90
02.06 11:15:53 [Server] [INFO] |-- fabric-networking-api-v1 1.2.11+10eb22f490
02.06 11:15:53 [Server] [INFO] |-- fabric-networking-v0 0.3.28+df3654b390
02.06 11:15:53 [Server] [INFO] |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
02.06 11:15:53 [Server] [INFO] |-- fabric-particles-v1 1.0.14+4d0d570390
02.06 11:15:53 [Server] [INFO] |-- fabric-recipe-api-v1 1.0.1+413cbbc790
02.06 11:15:53 [Server] [INFO] |-- fabric-registry-sync-v0 0.9.32+9244241690
02.06 11:15:53 [Server] [INFO] |-- fabric-renderer-api-v1 1.2.1+1adbf27790
02.06 11:15:53 [Server] [INFO] |-- fabric-renderer-indigo 0.8.0+1adbf27790
02.06 11:15:53 [Server] [INFO] |-- fabric-renderer-registries-v1 3.2.24+df3654b390
02.06 11:15:53 [Server] [INFO] |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
02.06 11:15:54 [Server] [INFO] |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
02.06 11:15:54 [Server] [INFO] |-- fabric-rendering-v0 1.1.27+df3654b390
02.06 11:15:54 [Server] [INFO] |-- fabric-rendering-v1 1.12.1+d8ef690890
02.06 11:15:54 [Server] [INFO] |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
02.06 11:15:54 [Server] [INFO] |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
02.06 11:15:54 [Server] [INFO] |-- fabric-screen-api-v1 1.0.32+4d0d570390
02.06 11:15:54 [Server] [INFO] |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
02.06 11:15:54 [Server] [INFO] |-- fabric-sound-api-v1 1.0.2+c4f28df590
02.06 11:15:54 [Server] [INFO] |-- fabric-textures-v0 1.0.24+aeb40ebe90
02.06 11:15:54 [Server] [INFO] |-- fabric-transfer-api-v1 2.1.6+413cbbc790
02.06 11:15:54 [Server] [INFO] \\-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
02.06 11:15:54 [Server] [INFO] - fabricloader 0.14.21
02.06 11:15:54 [Server] [INFO] - java 17
02.06 11:15:54 [Server] [INFO] - minecraft 1.19.2
02.06 11:15:54 [Server] [INFO] - sacrificesmp 1.0.0
02.06 11:15:54 [Server] main/[INFO] SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
02.06 11:15:54 [Server] main/[INFO] Compatibility level set to JAVA_16
02.06 11:15:54 [Server] main/[INFO] Compatibility level set to JAVA_17
02.06 11:15:58 [Server] main/[INFO] Building unoptimized datafixer
02.06 11:16:00 [Server] main/[INFO] Initializing SacrificesmpMod
02.06 11:16:00 [Server] main/[ERROR] Failed to start the minecraft server
02.06 11:16:00 [Server] [INFO] java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'sacrificesmp'!
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_465
02.06 11:16:00 [Server] [INFO] at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
02.06 11:16:00 [Server] [INFO] at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
02.06 11:16:00 [Server] [INFO] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
02.06 11:16:00 [Server] [INFO] at net.sacrificesmp.init.SacrificesmpModMenus.load(SacrificesmpModMenus.java:31) ~[SacrificeSMP.jar:?]
02.06 11:16:00 [Server] [INFO] at net.sacrificesmp.SacrificesmpMod.onInitialize(SacrificesmpMod.java:42) ~[SacrificeSMP.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] ... 7 more
02.06 11:16:00 [Server] [INFO] Caused by: java.lang.ClassNotFoundException: net.minecraft.class_465
02.06 11:16:00 [Server] [INFO] at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
02.06 11:16:00 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
02.06 11:16:00 [Server] [INFO] at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
02.06 11:16:00 [Server] [INFO] at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
02.06 11:16:00 [Server] [INFO] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
02.06 11:16:00 [Server] [INFO] at net.sacrificesmp.init.SacrificesmpModMenus.load(SacrificesmpModMenus.java:31) ~[SacrificeSMP.jar:?]
02.06 11:16:00 [Server] [INFO] at net.sacrificesmp.SacrificesmpMod.onInitialize(SacrificesmpMod.java:42) ~[SacrificeSMP.jar:?]
02.06 11:16:00 [Server] [INFO] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
02.06 11:16:00 [Server] [INFO] ... 7 more
02.06 11:16:00 [PebbleHost Loader] Server Stopped
02.06 11:16:00 [PebbleHost Loader] PebbleHost Server Loader Stopping...
02.06 11:16:00 [PebbleHost Loader] Server loader version: v3.0.5 (using configuration version v1.3.8)
02.06 11:16:00 [PebbleHost Loader] PebbleHost Server Loader Stopped.
02.06 11:16:00 [PebbleHost] Server shut down (running)
02.06 11:16:00 [PebbleHost] Server stopped

### How to reproduce this issue?

Downloaded my mod and latest fabric release

Launched server with those files

### Operating system

Windows

### Details

MCreator 2023.1

Fabric 1.19.2 generator

### Logs

https://gist.github.com/caffiendly/9c65a1950b80d76355d1b71b233e2394

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Caused by https://github.com/Goldorion/Fabric-Generator-MCreator/issues/408 and #358
