### ISSUE TITLE
Fabric loader 0.14.21 update

### ISSUE THREAD

**Issue by Atten007** [Goldorion/MCreatorFabricGenerator#420]
### Feature description

Hello @Goldorion,

I wanted to let you know that another fabric loader update 0.14.21 has been released. I wanted to ask you: Can you please update to this version? This may be very nice!

Greetings,
Atten 😊

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Why should I update? I have no good reason to do it as nothing I need is included.
