### ISSUE TITLE
Structures are just cutting off on loading chunks

### ISSUE THREAD

**Issue by PSGitHubUser1** [Goldorion/MCreatorFabricGenerator#423]
### Issue description

![2023-06-14_20 37 27](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/90406016/351cf4bc-dff8-4341-a4dd-1d0fe631226e)
![2023-06-14_20 37 34](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/90406016/02435877-0a08-4d64-8245-1dd3b8737b2f)
![2023-06-14_20 37 41](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/90406016/0eabae82-1595-4dc4-b07e-0925a8f17b62)
![2023-06-14_20 37 45](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/90406016/72398496-2410-4490-90cc-3e5ec18cd156)
![2023-06-14_20 39 02](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/90406016/2cab2eea-203c-4ed5-b8c5-df292fd137a4)
![2023-06-14_20 39 22](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/90406016/4374ffda-aed0-4840-bac6-7144630899c0)

I added this structure using MCreator and it does this. I don't know why this is happening as I don't think that I did any mistake in using structure block. Even I wasted 3 hours on it instead of doing my homework.

Please tell me I am doing something wrong.. I did this in MCreator...

![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/90406016/b9a3691f-4729-4cf9-9600-0095988c29e7)

======
If I am doing something wrong pls pls tell me. Or I will stuck. I have increased the render chunks to 12, then 14, then 8 but nothing works. Maybe its happening 'cuz I set Simulation Distance to 5 chunks? Or else pls tell.

### How to reproduce this issue?

1. Make a Structure
2. Set it like I did
3. Export mod and put to mods folder
4. See what's happening

### Operating system

Windows

### Details

MCreator: 2023.2

Fabric Generator: 1.8.9 (1.19.2, latest)
Fabric Essentials: 1.7.1 (latest)

### Example workspace

Workspace (.zip):
```zip
https://www.mediafire.com/file/62t21myno6wcvoa/volumesalpha_v0.1_1.19.2_workspace.zip/file
```

### Logs

_No workspace provided._

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
This is not something I can fix for the moment, due to how we make structures in MCreator currently (as they are technically not structures). Forge generators have the same problem.

**Comment by PSGitHubUser1** [comment]
Means I have to report to the KlemenDEV ? 

(If forge has the same issue like this)

**Comment by Goldorion** [comment]
Nah, we are already aware of this problem and we can't do something about it, except changing how our structure mod element is made to create real structures (we are using a feature currently that places a NBT file). This is already in the plans to be made by SomeoneElse.

**Comment by PSGitHubUser1** [comment]
Oh. That's a big issue.. wait 

Exporting the structure gives nbt file. I don't think there is any alternative of this except changing the code of game files or using the WorldEdit or Litematica as a library of MCreator.


I think we can use Litematica (or else but related to this) as library for MCreator. And it proqduces the schematic file (.schem) instead of nbt file.
