### ISSUE TITLE
Custom music discs cannot be played back

### ISSUE THREAD

**Issue by jaezudev** [Goldorion/MCreatorFabricGenerator#426]
### Issue description

As stated in the title.

### How to reproduce this issue?

Step 1: Create custom music discs
Step 2: Launch game
Step 3: Join world and get music disc, and try to play it back

### Operating system

Windows

### Details

MCreator version: 2023.2
Fabric Generator version: 1.9.3

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by quentinepitechdigital** [comment]
I can confirm, custom music discs can't be played.
