### ISSUE TITLE
Increase the number of supported global triggers in the 1.20.1 generator

### ISSUE THREAD

**Issue by GGSkyOne** [Goldorion/MCreatorFabricGenerator#427]
### Feature description

Compared to 1.19.2 generator, the number of supported global triggers is much lower (from 55.22% to 25.37%). Now many global triggers are not supported, will their support be implemented?

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Do you have other plugins adding new global triggers? I didn't remove a single global trigger.

**Comment by GGSkyOne** [comment]
I do not use other plugins that add global triggers, first of all in the generator selection menu says that it supports fewer global triggers (screenshot 1 and 2).

![Screenshot_241](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/97788417/19627217-69cc-453b-953c-a94463735c48)
![Screenshot_242](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/97788417/0e3f2515-1cb0-4280-b97e-a9fd235c27f3)

Secondly, I tested some of the global triggers on the generator 1.19.2 and 1.20.1 and they just did not work, I am sure that such triggers are more, I just did not check everything, compare the following screenshots.

1.19.2 generator

![Screenshot_243](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/97788417/9dbf7f4f-429e-4cae-b7db-3425bf6c0b4f)
![Screenshot_244](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/97788417/2243ef9f-5459-489b-b8fe-4760c9c69223)
![Screenshot_245](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/97788417/edcad345-a0ec-4ade-85d7-d7cbea4294e3)

1.20.1 generator

![Screenshot_246](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/97788417/3282f3cd-9dd3-41d6-8774-534c63f68eb1)
![Screenshot_247](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/97788417/079bc870-d6ef-434e-bc13-725b207d540b)
![Screenshot_248](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/97788417/a3a9e1e8-ed09-4d9c-bdfb-388f7945548c)

**Comment by GGSkyOne** [comment]
I accidentally pressed the close button lol sorry

**Comment by Goldorion** [comment]
I just checked and both Fabric versions (1.19.2 and 1.20.1) support the same global triggers. They have the same percentage, meaning you installed a plugin adding new global triggers.
