### ISSUE TITLE
stairs connecting with each other at certain angles causes missing textures

### ISSUE THREAD

**Issue by xSLUMA** [Goldorion/MCreatorFabricGenerator#428]
### Issue description

I have created many custom blocks and made stairs variants, when placed for the most parts the textures all work fine, but when placed and connecting at certain angles the textures go missing like this 

![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/64809021/5b65fb5c-bde4-45cc-b9a0-235677497905)

### How to reproduce this issue?

create a block using the stairs model and place them upside down connecting at a inner right angle should create a missing texture on the block or right side up connecting at an inner right angle

![2023-06-24_16 50 41](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/64809021/0f607048-00b6-4adb-b6ae-9cb0dfe904cb)

![2023-06-24_16 51 44](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/64809021/e0282e2d-e788-45d4-90fc-1af220610641)

### Operating system

Windows

### Details

Mcreator version 2023.2.24119 on window 10 using the fabric generator for 1.19.2 version 1.8.9 by Goldorion 

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Does it also happen on the Forge generators? (I use the same files for the JSON models, so if I have it, there's a high chance Forge gens have it too. If this is the case, it should be reported on MCreator's issue tracker)

**Comment by xSLUMA** [comment]
works fine with forge

**Comment by xSLUMA** [comment]
I don't think this is fixed, 1.19.2 this still happens
