### ISSUE TITLE
Fabric generator doesn't register Terrablender blocks

### ISSUE THREAD

**Issue by AAAAAAAAAAAAAAAAAAAAAAAAAAAe** [Goldorion/MCreatorFabricGenerator#429]
### Issue description

The fabric generator does not register/support code blocks from the Terrablender addon, thus failing to set up regions and rendering the program unable to properly compile the addon

### How to reproduce this issue?

Step 1: Install the terrablender addon for MCreator
Step 2: Make a custom biome
Step 3: Follow the tutorial on the terrablender addon page

There should be errors on the bottom of the code editor saying that those blocks aren't supported and will be skipped

### Operating system

Windows

### Details

MCreator version: 2023.2
Generator version: Fabric generator 1.19.2

### Logs

Executing Gradle task: build
Build info: MCreator 2023.2.24119, fabric-1.19.2, 64-bit, 8094 MB, Windows 10, JVM 17.0.5, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2023-06-24-19:44:23

BUILD FAILED
Task completed in 45 seconds

> Configure project :
Fabric Loom: 1.0.18
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix.
> Task :compileJava FAILED
C:\Users\Matijo\MCreatorWorkspaces\lucaro_mod\src\main\java\net\mcreator\lucaromod\init\LucaroModModBiomes.java:21: error: cannot find symbol  SmwBiomeBiome.createBiome();
 ^
symbol: variable SmwBiomeBiome
location: class LucaroModModBiomes
C:\Users\Matijo\MCreatorWorkspaces\lucaro_mod\src\main\java\net\mcreator\lucaromod\init\LucaroModModBiomes.java:25: error: cannot find symbol  Regions.register(new SmwBiomeRegion(new ResourceLocation(LucaroModMod.MODID, "smw_biome")));
   ^
symbol: class SmwBiomeRegion
location: class LucaroModModBiomes
2 errors
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
BUILD FAILED in 4s
1 actionable task: 1 executed

BUILD FAILED
Task completed in 6 seconds

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
The Terrablender external plugin is not mine, so this is not to me to support it. In addition to that, the Fabric Generator plugin already has its own TerraBlender implementation.
