### ISSUE TITLE
Using the procedure block 'get level of enchantment <enchantment> of <level>' causes a build error

### ISSUE THREAD

**Issue by Someone68** [Goldorion/MCreatorFabricGenerator#431]
### Issue description

It's as simple as the title says. Using that block causes a build error. I made sure I had all of the required dependencies, it's still giving me the error. This is very annoying since this block is used a lot when making enchantments!

### How to reproduce this issue?

1. Simply create a procedure with the block "get level of enchantment <enchantment> of <level>"
2. Save your mod element
3. Boom. Compilation error.

### Operating system

Windows

### Details

MCreator version: 2023.2
Generator Type: 1.20.1 Fabric Generator

### Logs

Executing Gradle task: build 
Build info: MCreator 2023.2.24119, fabric-1.20.1, 64-bit, 12053 MB, Windows 11, JVM 17.0.5, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2023-06-30-17:57:09 
  
> Configure project : 
Fabric Loom: 1.2.7 
> Task :compileJava 
[C:\Users\someone68\MCreatorWorkspaces\prism\src\main\java\net\mcreator\mymod\procedures\GeProcedure.java:48](file:///C:/Users/someone68/MCreatorWorkspaces/prism/src/main/java/net/mcreator/mymod/procedures/GeProcedure.java:48): error: cannot find symbol 
         _player.displayClientMessage(Component.literal(("Test: " + ((sourceentity instanceof LivingEntity _livEnt ? _livEnt.getMainHandItem() : ItemStack.EMPTY).getEnchantmentLevel(Enchantments.FLAMING_ARROWS)))), false); 
                                                                                                                                                                 ^ 
  symbol:   method getEnchantmentLevel(Enchantment) 
  location: class ItemStack 
1 error 
> Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 8s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 13 seconds

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by smasher0699** [comment]
I have the same issue
