### ISSUE TITLE
Get copy item of get nearest entity at coordinates with a variable

### ISSUE THREAD

**Issue by mairangh** [Goldorion/MCreatorFabricGenerator#435]
### Issue description

If you use the get entity at coordinates with a variable command in the procedure, it gives an error

### How to reproduce this issue?

1. Create procedure
2. Add variables
3. Add commands: send to chat to all platers, create text with, get copy item from slot 0 of, get nearest entity at x y z of type item display. 
4. I save it - I don't get any errors
5. I change "X" to "x+ variable"
6. I save it - I get error

### Operating system

Windows

### Details

MCreator 2023.2
Fabric 1.9.5

### Example workspace

Procedure "BBFPlace" have error
https://drive.google.com/file/d/13f9ZUMdOEakMUdN3TYtP1Rh5X14cupjq/view?usp=sharing

### Logs

[log.txt](https://github.com/Goldorion/Fabric-Generator-MCreator/files/11970113/log.txt)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by firyy** [comment]
I'm having the same error with local number variables (it registers as **double**) and slot id number, even if I try to round or make it a random integer, the procedure "get a copy of item from slot x of entity if it has inventory" is not working with a variable...
