### ISSUE TITLE
Unable to generate correct code when crafting remote items (decompileJava Failed)

### ISSUE THREAD

**Issue by gameak2334498769** [Goldorion/MCreatorFabricGenerator#437]
### Issue description

Unable to generate correct code when crafting remote items (decompileJava Failed)

### How to reproduce this issue?

Craft remote items in MCreator
Then build 

### Operating system

Windows

### Details

MCreator2023.2
Fabric 1.20.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
What do you kean by remote items?
Also, no logs nor workspace = no help
