### ISSUE TITLE
Add The Generator for Minecraft 1.19.4 

### ISSUE THREAD

**Issue by DEMnetwork** [Goldorion/MCreatorFabricGenerator#439]
### Feature description

Add A Generator Fabric Mod For Minecraft 1.19.4

Because I Checked And There Isn't A Fabric Mod Generator For Minecraft 1.19.4

And I Use Minecraft 1.19.4 And Wanna Create A Mod For Minecraft 1.19.4

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by DEMnetwork** [comment]
**Okay...**

**Comment by Micasddsa** [comment]
_taken from https://github.com/Goldorion/Fabric-Generator-MCreator/issues/312#issuecomment-1331488369_

> ...I won't downgrade until I have a team to support and help me. It would require way too much time to maintain 2 generators.

Honestly, just use an older version of the generator. Granted It will take a bit to find but if you really need to develop for an older version, dosen't hurt to just use a older version.

_then again... the same could be said about developing for 1.19.4. if you don't really have any mods and stuff you want to use with your own mod then it dosen't really hurt to just upgrade to 1.20.1_
