### ISSUE TITLE
[BUG] Cant seem to add 1.0.0 Alpha 1 as a plugin doesnt do anything

### ISSUE THREAD

**Issue by Dragon20C** [Goldorion/MCreatorFabricGenerator#44]

**Comment by Goldorion** [comment]
Can you explain your problem and give details please? if you are talkinng about the errors with almost everything, we are currently working on them.

**Comment by Dragon20C** [comment]
@Goldorion Its as simple as the title suggests I open up mcreator latest version and go into perfences - plugins - select the zip file from your release area and nothing happens doesnt add it as a plug in or anything tring the old 1.15 version works but 1.16 doesnt

**Comment by Goldorion** [comment]
With the version I'm working on, the plugin loads perfectly. I will release a patch soon because nothing works.

**Comment by BoogieMonster1O1** [comment]
You’ll need the latest mcreator snapshot. The 1.15 version targets 2020.3, and the 1.16 version targets 2020.4 snapshots
