### ISSUE TITLE
Music Discs / Sounds broken on Fabric 1.20.1

### ISSUE THREAD

**Issue by Rebel459** [Goldorion/MCreatorFabricGenerator#440]
### Issue description

I'm fairly sure it isn't me, tried everything and done exactly as you're meant to according to multiple written and video guides, but my music disc won't work, nor will the /playsound command.

All OGG files, the tested one was even mono, all set up correctly. Not sure what's going on, but it could be related to a generator issue I suppose, so thought I'd report this here just in case.

### How to reproduce this issue?

Create a custom sound (music disc optional) - try playing disc and try the /playsound command

### Operating system

Windows

### Details

MCreator 2023.2
Fabric Generator 1.20.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Did you try on the 1.19.2 version or a Forge generator?

**Comment by Rebel459** [comment]
Yep, works fine on 1.19 @Goldorion

**Comment by Rebel459** [comment]
Can confirm this is definitely a 1.20 Fabric Generator issue. Thankfully it's super easy to reproduce if anyone needs to test for themselves

**Comment by Rebel459** [comment]
While the /playsound command doesn't work, even setting the music disc to use vanilla music (eg overworld.lush_caves) doesn't work.

**Comment by Rebel459** [comment]
Nvm, it seems my Fabric Generator was outdated lol. My bad, sorry
