### ISSUE TITLE
Terrablender Can't be added as External API

### ISSUE THREAD

**Issue by Rebel459** [Goldorion/MCreatorFabricGenerator#441]
### Issue description

Title. When you go to External APIs, Terrablender is not listed and cannot be added, breaking biome support

### How to reproduce this issue?

See description

### Operating system

Windows

### Details

2023.2 MCreator + 1.20.1 Fabric Generator (latest version, ends in a 5)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Rebel459** [comment]
Biomes don't work due to this bug, which is annoying

**Comment by Goldorion** [comment]
Please provode logs (of mcreator, not the console) wheb the bug occurs. `Users/yourUser/.mcreator/logs/mcreator.log)`

**Comment by Goldorion** [comment]
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/38427877/48e23749-88af-49c4-a48c-5388489356f1)

You did something wrong because the API appears

**Comment by Rebel459** [comment]
Strange, maybe I should look at reinstalling MCreator or something. Sorry I hadn’t got back to you, been quite busy and ended up forgetting
