### ISSUE TITLE
Trigger "Player completes advancement" is no longer working

### ISSUE THREAD

**Issue by purejosh** [Goldorion/MCreatorFabricGenerator#442]
### Issue description

In 1.19.2, a global trigger "Player completes advancement" was available, and very very useful for many of my mods. In 1.20.1, this global trigger is resulting in a build error. 

### How to reproduce this issue?

Use "Player completes advancement" global trigger in a procedure
Observe that build fails 

### Operating system

Windows

### Details

Mcreator 2023.2 Release
Fabric Generator 1.20.1 - 1.9.5 (2023.2)	

### Logs

> Configure project : 
Fabric Loom: 1.2.7 
> Task :compileJava FAILED 
[C:\Users\purejosh\MCreatorWorkspaces\Projects\ancientvessels\fabric-1.20.1\src\main\java\net\purejosh\ancientvessels\procedures\AdvancementUnlockVesselProcedure.java:17](file:///C:/Users/purejosh/MCreatorWorkspaces/Projects/ancientvessels/fabric-1.20.1/src/main/java/net/purejosh/ancientvessels/procedures/AdvancementUnlockVesselProcedure.java:17): error: package AdvancementCallback does not exist 
      AdvancementCallback.EVENT.register((player, advancement) -> { 
                         ^ 
1 error 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 1s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 4 seconds

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by purejosh** [comment]
This appears to be due to the lack of Portinglib. I'm unsure if mcreator used to come with portinglib, or if the fabric generator had portinglib as an included library. I know that there are a few beta builds of 1.20.1 portinglib, but I'm not smart enough to figure out how to install them into my project.

**Comment by Goldorion** [comment]
PortingLIB is a part of the Fabric Essebtials plugin which is not one of mine.

**Comment by purejosh** [comment]
Ah, okay. I forgot about that. Would be nice to see it included in the fabric generator though, it was a life saver. Advancements are great for tracking progression and I use them heavily.
