### ISSUE TITLE
Error when creating biomes

### ISSUE THREAD

**Issue by BryceIsBryce** [Goldorion/MCreatorFabricGenerator#443]
### Issue description

Whenever I save a biome, I get this error:
(file:///C:/Users/.../init/BlocksModBiomes.java:21): error: cannot find symbol 
      MyceluemeadowsBiome.createBiome(); 
      ^ 
  symbol:   variable MyceluemeadowsBiome 
  location: class BlocksModBiomes (file:///C:/Users/.../init/BlocksModBiomes.java:25): error: cannot find symbol 
      Regions.register(new MyceluemeadowsRegion(new ResourceLocation(BlocksMod.MODID, "myceluemeadows"))); 
                           ^ 
  symbol:   class MyceluemeadowsRegion 
  location: class BlocksModBiomes 
2 errors

### How to reproduce this issue?

1. I create a new biome called "Mycelue Meadows".
2. I press the save button for the biome
3. It tells me that an error occurred as the workspace was saving

### Operating system

Windows

### Details

MCreator 2023.2, Fabric 1.19.2 - 0.67.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Ypu need to enable the provoded Terrablender API
