### ISSUE TITLE
Error: Code Too Large

### ISSUE THREAD

**Issue by iPanic-Dev** [Goldorion/MCreatorFabricGenerator#449]
### Issue description

After removing all of the stairs (#448) to see if that was the root issue, I ran into another error due to the sheet number of items we have in our mod (I'm sorry, I know it's a lot lol). 

Removing about ~300 or so gets it to compile again. 

### How to reproduce this issue?

Have an instance with over ~1100 items, and try to run/compile. 

### Operating system

Windows

### Details

Mcreator v2023.2 // Fabric Generator v1.9.6

### Logs

Executing Gradle task: build 
Build info: MCreator 2023.2.24119, fabric-1.20.1, 64-bit, 32509 MB, Windows 11, JVM 17.0.5, JAVA_HOME: C:\Users\cmare\Documents\Mcreator 120\jdk, started on: 2023-08-09-19:40:50 
  
> Configure project : 
Fabric Loom: 1.2.7 
> Task :compileJava 
[C:\Users\cmare\Documents\Mcreator 120\tc fabric take 2\mcreatorworkspace\src\main\java\net\mcreator\trekcraft\init\TrekcraftModItems.java:1451](file:///C:/Users/cmare/Documents/Mcreator%20120/tc%20fabric%20take%202/mcreatorworkspace/src/main/java/net/mcreator/trekcraft/init/TrekcraftModItems.java:1451): error: code too large 
   public static void load() { 
                      ^ 
1 error 
> Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 7s 
1 actionable task: 1 executed

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I don't think I can fix this problem

**Comment by iPanic-Dev** [comment]
> I don't think I can fix this problem

Do you have an idea of where it might be coming from? I can try taking it over to the Loom repo, or wherever I might need to check in. 

This compiles fine with Forge so I'm assuming it's a limitation imposed within the Fabric ecosystem somewhere maybe?

**Comment by Goldorion** [comment]
It's not a limitation imposed by Fabric, but more with Java. Forge handles things differently, so the limit is just higher, but it still exists.

**Comment by iPanic-Dev** [comment]
Got it - I can try and pull as many assets out as I can. There are a lot we haven't used/ don't get any use anymore. But it will still be over the current limit. 

Any chance of even a slightly increased amount? I don't mind splitting into a new mod going forward, I just can't risk data loss from 1/3 of the mod being gone.

**Comment by Goldorion** [comment]
I'll see what I can do in the future, but I don't promise to get something. However, will it be possible to have the workspace? It would help me with my tests.

**Comment by iPanic-Dev** [comment]
> I'll see what I can do in the future, but I don't promise to get something. However, will it be possible to have the workspace? It would help me with my tests.

For sure, I totally understand! I sent you an add on Discord. I can drop the workspace there. Would rather it not be public, I'm sure you understand 😀

**Comment by Goldorion** [comment]
Can you re-send it again, please? (and write a message, so I just know it's not someone just wanting to be friend with me)

**Comment by iPanic-Dev** [comment]
> Can you re-send it again, please? (and write a message, so I just know it's not someone just wanting to be friend with me)

Done & Done, `@ipanic` on there - Cheers

**Comment by Goldorion** [comment]
Ok, I tested a bit and I found the real cause of the problem. It's not due to a limitation of Fabric, but from Java methods that can't exceed 64KB of bytecode... yours has way too many items 😅
https://stackoverflow.com/questions/2407912/code-too-large-compilation-error-in-java

I can increase the number of possible items (and other mod elements in their respective method) by removing duplicated code, but the way I register things for the moment doesn't allow dozens of thousands of mod elements.

The real fix for this would be to get rid of the methods, but I didn't find a working way yet.

**Comment by Goldorion** [comment]
Good news: My first optimisation works enough to increase the limits and makes your workspace builds fine.

Bad news: I have no idea what is the limit (it also depends on other things that change depending on each mod element (e.g. registry name)

Good news 2: I can still squish more mod elements if needed by doing another optimization.

Bad news 2: This will come at the cost of lower performances (especially for big workspaces), so I won't implement it except if this is REALLY needed. Another thing: it can only be done for items. All the other mod elements will be at full capacity,

I hope it'll help you a bit (and sorry for the very long delay 🙇)
