### ISSUE TITLE
Custom sound build error

### ISSUE THREAD

**Issue by benl4b** [Goldorion/MCreatorFabricGenerator#450]
### Issue description

Hey! I don't know if this is a bug, but it doesn't happen normally:
I've added new .ogg sounds and keep getting the same error messages about the desktop not being compiled correctly. Since there was apparently an error in the code, I tried to fix it, but it doesn't save it and then shows the same thing over and over again:

This also happens when you try to add loottables and use them like you would in Forge. Also, some other fabric plugins (for procedures) say that the generator doesn't support them, but that's not important.

### How to reproduce this issue?

I added a new .ogg Sound
I added an Entity
I assigned this sound to the entity
I tried to start client side

### Operating system

Windows

### Details

Mcreator 2023.2
Generator: Fabric 1.20.1

### Logs

https://pastebin.com/YTQCPPzL

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I was not able to reproduce the issue. Make sure you are using the latest version.
