### ISSUE TITLE
Plugin Load Error

### ISSUE THREAD

**Issue by Zenith613** [Goldorion/MCreatorFabricGenerator#458]
### Issue description

Whenever i install the plugin it gives me a notification highlighting that fabric gen for 1.20.1 failed to load.

### How to reproduce this issue?

1. load plugin
2. reboot mcreator

### Operating system

Windows

### Details

MCreator 2023.3
Loader version 1.20.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Yes, this is normal. I didn't update it to MCreator 2023.3 yet. (I'll try to port it in the next days)

**Comment by aurorarissime** [comment]
Any update on this?
