### ISSUE TITLE
"Cannot find symbol" When making slabs

### ISSUE THREAD

**Issue by masonsnyder001** [Goldorion/MCreatorFabricGenerator#46]
I apologize if this is basic user error, I'm very much new to mod creation, but whenever I try to make slabs--no matter the properties--I'm always met with an ambiguous "error: cannot find symbol". Not trying anything complex, just some new blocks without any wacky custom properties, and they all work except slabs. I'm just using the built-in block base system so I dunno if I should be doing something else. I tried all the stuff on MCreator's FAQ but it didn't help. I've made multiple workspaces after I reinstalled MCreator, the fabric generator, and gradle, and I've tried multiple versions of both MCreator and the generator and have gotten the same results. You'll find the current workspace down below.

Log:
https://hastebin.com/gicapakimo.bash

Workspace:
https://drive.google.com/file/d/1oh5aCaYSd0vkM5-H8oYHo7OGmIxbnetC/view?usp=sharing

**Comment by BoogieMonster1O1** [comment]
Thanks for reporting it! I'll see if I can fix it soon

**Comment by BoogieMonster1O1** [comment]
Unfortunately, as of now, we actually don't have proper support for slabs yet. I'll keep this issue open until we add slabs

**Comment by CStafford-14** [comment]
I'm getting the same error whenever I add _any_ block.
[symbol error.log](https://github.com/ClothCreators/MCreatorFabricGenerator/files/5208721/symbol.error.log)
`/home/christophers/MCreatorWorkspaces/addons/src/main/java/gq/cesium/addons/ClientInit.java:25: error: cannot find symbol 
      BlockRenderLayerMap.INSTANCE.putBlock(AddonsMod.block_BLOCK, RenderLayer.getCutoutMipped()); 
                                                     ^ 
  symbol:   variable block_BLOCK 
  location: class AddonsMod 
1 error `

**Comment by silentnyte** [comment]
@CStafford-14 see my comment here. This is an issue with how the ClientInit.java is being generated.

https://github.com/ClothCreators/MCreatorFabricGenerator/issues/74#issuecomment-697808378

**Comment by BoogieMonster1O1** [comment]
Fixed. I'll release a new version in a few hours.
