### ISSUE TITLE
Add end generation

### ISSUE THREAD

**Issue by PI0NEERING** [Goldorion/MCreatorFabricGenerator#460]
### Feature description

I want to add end biomes as part of the mod I'm making, I know its possible because mods like BetterEnd. It also seems like a good feature to add, please consider adding it.

### Issue tracker rule checks (please read carefully)

- [x] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
It has already been added. They are located inside the Default features parameter.
