### ISSUE TITLE
Add a variable player scope

### ISSUE THREAD

**Issue by Budgixous** [Goldorion/MCreatorFabricGenerator#461]
### Feature description

I would like to have the ability to make variables player-scoped, instead of global.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I just noticed it's a duplicated of #433
