### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by ghost** [Goldorion/MCreatorFabricGenerator#462]
### Issue description

![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/65037385/e4642974-6658-484a-879f-ab123db68b03)

### How to reproduce this issue?

.

### Operating system

Windows

### Details

.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by smmmadden** [comment]
the developer will not be able to track this down since you provided absolutely no information for him to do so.

**Comment by Goldorion** [comment]
Search.

**Comment by PI0NEERING** [comment]
tbh i just changed the max version in the files
