### ISSUE TITLE
Error when specifying biome for entity

### ISSUE THREAD

**Issue by Faris90** [Goldorion/MCreatorFabricGenerator#466]
### Issue description

This error
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/24720470/a24da613-9eaa-447b-940c-835e58df1bdc)

### How to reproduce this issue?

Step1: create an entity
Step2: Specify the biome where the entity spawns

### Operating system

Windows

### Details

MCreator 2023.3

### Logs

above

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Faris90** [comment]
bump

**Comment by Goldorion** [comment]
I'm not able to reproduce the issue on master, so I consider this issue has resolved.
