### ISSUE TITLE
Some BlockPos usages in procedure blocks cause problems in some cases

### ISSUE THREAD

**Issue by thunderemmet** [Goldorion/MCreatorFabricGenerator#468]
### Issue description

I was working on a reverse crafting table that uncrafts things and I ran into some compile errors with the procedure for the custom crafting. I tried everything i could to fix it but it still wouldn't work. Can anyone help me?

### How to reproduce this issue?

idk I literally just tried to save the procedure and it gave me a compile error. Although I did fidget with it a bit, it still didn't work so I wen t back to the original and that is what you see in the attached file.

### Operating system

Windows

### Details

MCreator version: 2023.2

Generator: Fabric for 1.20.1 - 0.83.1

### Example workspace

the workspace zip file was too big to transfer so here is just the procedure file.
[bugged procedure.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/12775384/bugged.procedure.zip)

### Logs

Executing Gradle task: runClient
Build info: MCreator 2023.2.24119, fabric-1.20.1, 64-bit, 8067 MB, Windows 10, JVM 17.0.5, JAVA_HOME: C:\Users\Emmet\Desktop\MCreator.2023.2.Windows.64bit\MCreator20232\jdk, started on: 2023-09-30-16:26:05
 
> Configure project :
Fabric Loom: 1.2.7
> Task :compileJava
C:\Users\Emmet\MCreatorWorkspaces\thunderemmes_mod_fabric_port\src\main\java\net\mcreator\thunderemmesmodfabricport\procedures\AnticraftingrecipesProcedure.java:60: error: incompatible types: possible lossy conversion from double to int  BlockEntity _ent2 = world.getBlockEntity(new BlockPos(x, y, z));
         ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
> Task :compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 33s
1 actionable task: 1 executed
 
BUILD FAILED
Task completed in 40 seconds

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [x] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by thunderemmet** [comment]
Bruh. Ig no one care's about my problems.

**Comment by Goldorion** [comment]
My classes and my private life are much more important, so excuse me if I am busy instead of working on plugins for free in my free time.

**Comment by thunderemmet** [comment]
oh ok thats totally understandable and i can relate.
