### ISSUE TITLE
Custom biomes generating outwith parameters

### ISSUE THREAD

**Issue by LucidLuminary** [Goldorion/MCreatorFabricGenerator#472]
### Issue description

When creating a custom biome and adjusting the generation parameters (temperature, continentalness, etc) running the game and starting a new world reveals that the biome will generate outside of the ranges that were set. For instance, setting continentalness to 0.6 - 1.0 in order to spawn the biome only in far inland areas will still result in the biome being placed in areas of deep ocean and everywhere in between.

### How to reproduce this issue?

1. Open a new workspace and enable Terrablender API
2. Create a new biome and adjust its generation parameters so that it would generate only in certain areas
3. Build and run, create a new world
4. Fly around a bit, use /locate to find your new biome
5. Open the F3 menu to see the generation parameters of your current block, and see that the new biome will often generate outside the values that you set earlier

### Operating system

Windows

### Details

MCreator version: [2023.3]
Generator type: [fabric-1.20.1 / 0.83.1]

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Concerning this part, I'm using the same code as inside the Forge generator, so either it is a problem with this code (and I don't know how to fix it) or it is a bug with TerraBlender (and I can't fix it)

**Comment by LucidLuminary** [comment]
Ah, so I suppose it must be TerraBlender in that case, since I don't get this issue using the Forge generator.
