### ISSUE TITLE
Procedure / Trigger causing Build Errors

### ISSUE THREAD

**Issue by pringlethegoat** [Goldorion/MCreatorFabricGenerator#473]
### Issue description

Not sure what I'm doing wrong, whenever there is a procedure or a Trigger involved it appears to keep crashing.
I have tried using Fabric Essentials aswell to no avail.
I have tried numerous of the FAQ Fixes stated on MCreators Website to also no avail.
Any help is appreciated, below is the Build Log:

_Entity entityToSpawn = new PickleRickEntity(BenchedEntitiesModEntities.PICKLE_RICK.get(), _level); 
                                                                                           ^ 
  symbol:   method get() 
  location: variable PICKLE_RICK of type EntityType<PickleRickEntity> 
1 error 
Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
What went wrong: 
Execution failed for task ':compileJava'. 
Compilation failed; see the compiler error output for details. 
Try: 
Run with --stacktrace option to get the stack trace. 
Run with --info or --debug option to get more log output. 
Run with --scan to get full insights. 
Get more help at https://help.gradle.org 
BUILD FAILED in 4s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 13 seconds_ 
 

### How to reproduce this issue?

Step 1: Create a Procedure
Step 2: Regardless of if there is any Code or not, the Log as above prints and states there's an Error.

### Operating system

Windows

### Details

MCreator Version: 2023.3
Fabric Generator: 1.20.1_0

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Coosanta17** [comment]
replace all `spawn entity` blocks with this:
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/85379921/f93ce7fa-8dab-45c0-b607-911b2f73a117)
