### ISSUE TITLE
Compile Java Failed - Referencing Sounds that no longer exist.

### ISSUE THREAD

**Issue by pringlethegoat** [Goldorion/MCreatorFabricGenerator#474]
### Issue description

I recently added some sounds to a Project just to test them, after swapping them out for different ones and then removing them all-together the Console still seems to think those sounds exist in some form of Index but they do not and are no longer referenced in any Procedures, Triggers etc and have been completely wiped, yet the Console seems to think otherwise.
Below is the readout of the Console (Pastebin Link)

(I have tried the most common solution, resetting my cache, deleting the entire folder etc to no avail.)

https://pastebin.com/HLWVpH22

### How to reproduce this issue?

Step 1: Add Sounds to Project via the Designated button on the Top Bar.
Step 2: Reference Sounds in a Procedure / Trigger event.
Step 3: Remove all Instances of the Sound including the File & References in Procedure & Trigger.

### Operating system

Windows

### Details

MCreator Version: 2023.3
Fabric Generator: 1.20.1_0

### Logs

https://pastebin.com/HLWVpH22

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
This bug is a bug related to MCreator's code. I can not change this as it is surely due to how MCreator caches elements.
