### ISSUE TITLE
Support for few external global triggers

### ISSUE THREAD

**Issue by PSGitHubUser1** [Goldorion/MCreatorFabricGenerator#477]
### Feature description

Can we have support for 'A block is placed' and a few more like um, 'Player tick'.

I was making an entity which can be summoned like Wither... But it needs support for 'A block is placed'. In my case, 'Player right clicks block' doesn't work. 

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by PSGitHubUser1** [comment]
#469

You can see the images.
This feature was supported by Fabric Essentials but it is stuck on 1.19.2/3, I guess?

**Comment by Goldorion** [comment]
Fabric Essentials uses external APIs, which is not something I want to do when it is not necessary. Fabric will eventually have them.

**Comment by PSGitHubUser1** [comment]
Did Fabric got those features now..? 

I hope so.
