### ISSUE TITLE
Bug: Entities fail to compile

### ISSUE THREAD

**Issue by Atten007** [Goldorion/MCreatorFabricGenerator#479]
### Issue description

Hello,

I'm currently working on an Animal Crossing mod for Minecraft: Java Edition. I want to have this mod for Forge & Fabric. The Forge version doesn't have any compiler errors but the Fabric version is showing the error "Can't find symbol". I hope that this can be fixed very soon!

Greetings,
Atten007 😊

### How to reproduce this issue?

1. Open MCreator
2. Open an existing MCreator Fabric workspace or create a new one
3. Click on the +, select "Entity" and create one
4. It will show a compiler error

### Operating system

macOS

### Details

I'm using MCreator 2023.4.44716 EAP, macOS Sonoma 14.0, Java 17.0.9 and Fabric MCreator Generator 1.9.9 for 1.20.1.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
It has already been fixed in master and will be fixed in the next patch (it should come soon if I have enough time).
