### ISSUE TITLE
[Bug] Trying to get custom potion effect - Cannot find symbol. 

### ISSUE THREAD

**Issue by TheCrafters001** [Goldorion/MCreatorFabricGenerator#481]
### Issue description

When I create a function that tries to get a custom effect from the current workspace, it fails compile for "symbol not found."

### How to reproduce this issue?

1. Create new effect
2. Add Any Procedure
3. Try to call a custom effect (give, has, remove, etc.)
4. Save and wait for compile
5. Fails to compile.

![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/46639269/89828166-dc36-49a0-a7d0-4bf892d644a4)

### Operating system

Linux

### Details

MCreator: 2023.3
Generator: fabric-1.20.1 (version 1.9.9 and 1.9.10)

### Example workspace

[Link to zipped workspace](https://drive.proton.me/urls/P4TDXMKHX0#u0KwPKzjL5Bf)

### Logs

https://gist.github.com/TheCrafters001/79e58816a429e4dcf9c0161f8a70e511

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I'm not able to reproduce the problem.

**Comment by Goldorion** [comment]
The bug is not present when I test on my test workspace.
