### ISSUE TITLE
*Most Players Global Triggers won't work

### ISSUE THREAD

**Issue by NeededResty** [Goldorion/MCreatorFabricGenerator#486]
### Issue description

I've been making a mod with the newest version (1.9.10), and so far, I've had many problems compiling my procedure. The build log points towards the trigger. I've made about three other procedures involving entities and players, and all three wouldn't compile.

Procedure:
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/63218795/a424d63b-14bb-4bed-81db-68ac95039316)
 
Error:
`
> Configure project :
Fabric Loom: 1.4.4
> Task :compileJava
C:\Users\redst\MCreatorWorkspaces\blades_and_blood\src\main\java\mr\rsguy\bladesandblood\procedures\BloodBottlingProcedure.java:18: error: lambda body is neither value nor void compatible  UseItemCallback.EVENT.register((player, level, hand) -> {
         ^
C:\Users\redst\MCreatorWorkspaces\blades_and_blood\src\main\java\mr\rsguy\bladesandblood\procedures\BloodBottlingProcedure.java:18: error: incompatible types: bad return type in lambda expression  UseItemCallback.EVENT.register((player, level, hand) -> {
      ^
 missing return value
C:\Users\redst\MCreatorWorkspaces\blades_and_blood\src\main\java\mr\rsguy\bladesandblood\procedures\BloodBottlingProcedure.java:20: error: incompatible types: bad return type in lambda expression   return;
  ^
 missing return value
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 errors
> Task :compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.
BUILD FAILED in 13s
1 actionable task: 1 executed
 
BUILD FAILED
Task completed in 18 seconds`

Apologies if I made a stupid mistake.

### How to reproduce this issue?

1. Make a procedure.
2. Put in a global trigger, mostly involving an entity or player
3. Build

### Operating system

Windows

### Details

MCreator 2023.3.36712, 
fabric-1.20.1
64-bit, 14252 MB, Windows 10, JVM 17.0.7
JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk
Plugin Version: 1.9.10

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
what version of the plugin do you use?

**Comment by NeededResty** [comment]
> I've been making a mod with the newest version (1.9.10), and so far, I've had many problems compiling my procedure. The build log points towards the trigger. I've made about three other procedures involving entities and players, and all three wouldn't compile.

1.9.10. Sorry for being too obscure!

**Comment by NeededResty** [comment]
Sorry! Entities were my fault but player-involved global triggers are malfunctioning!

**Comment by Goldorion** [comment]
I found some problems with the player triggers and they are now fixed. However, please keep in mind not all triggers are supported (even if MCreator says they are, it's due to something I do with the plugin) https://github.com/Goldorion/Fabric-Generator-MCreator/blob/1.20.1/Supported%20Global%20triggers.md
