### ISSUE TITLE
Re-Add End Biomes Support

### ISSUE THREAD

**Issue by ErzeKawek** [Goldorion/MCreatorFabricGenerator#487]
### Feature description

As seen here 
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/130212655/6c936b22-6cd6-4906-a799-f25dbc9964f4)
I Saw that you removed the **end biomes support** on 1.7-beta-11, i was thinking maybe you could re-add that feature so i can make an end biome mod.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
They are already re-supported.

**Comment by ErzeKawek** [comment]
no, it bugs when i try to use it, it says it cant load terrablender when i add the End Highlands Biome to the Features list, and disabled generate in Nether And Overworld

**Comment by ErzeKawek** [comment]
> They are already re-supported.
no, it bugs when i try to use it, it says it cant load terrablender when i add the End Highlands Biome to the Features list, and disabled generate in Nether And Overworld
