### ISSUE TITLE
End Biomes Error (Again)

### ISSUE THREAD

**Issue by ErzeKawek** [Goldorion/MCreatorFabricGenerator#488]
### Issue description

The mod fails to compile when i use the End Highlands Biome in the features list of my end biome

### How to reproduce this issue?

Step 1 : Make a biome
Step 2 : Add End Highlands Biome to the biome feature list

### Operating system

Windows

### Details

MCreator Version : 2023.3
Generator : fabric-generator-1.20.1-1.9.10

### Example workspace

[example.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/13324193/example.zip)

### Logs

> Configure project : 
Fabric Loom: 1.4.4 
> Task :compileJava FAILED 
[D:\darkened_lands\src\main\java\net\erzekawek\netherenditions\init\NetherenditionsModBiomes.java:27](file:///D:/darkened_lands/src/main/java/net/erzekawek/netherenditions/init/NetherenditionsModBiomes.java:27): error: cannot find symbol 
      Regions.register(new EnderWarpedForestRegion(new ResourceLocation(NetherenditionsMod.MODID, "ender_warped_forest"))); 
                           ^ 
  symbol:   class EnderWarpedForestRegion 
  location: class NetherenditionsModBiomes 
1 error 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --info option to get more log output. 
> Run with --scan to get full insights. 
BUILD FAILED in 3s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 7 seconds

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by ErzeKawek** [comment]
i disabled the Option To Generate In The Overworld and Nether

**Comment by Goldorion** [comment]
You did not enable the TerraBlender API, which is required to generate biomes.

**Comment by ErzeKawek** [comment]
ive enabled terrablender api
@Goldorion

**Comment by Goldorion** [comment]
End biomes had problems that are already fixed in the new update. Just download it and your problem will be fixed.
