### ISSUE TITLE
Potions cause errors during build task.

### ISSUE THREAD

**Issue by palmmc** [Goldorion/MCreatorFabricGenerator#489]
### Issue description

If I create a custom potion, and try to build with the fabric generator on the latest version, it causes an error.
```
[C:\Users\..\MCreatorWorkspaces\just_haste\src\main\java\net\palm\hastepaste\init\HastePasteModBrewingRecipes.java:12](file:///C:/Users/../MCreatorWorkspaces/just_haste/src/main/java/net/palm/hastepaste/init/HastePasteModBrewingRecipes.java:12): error: cannot find symbol 
      PotionBrewing.addMix(Potions.AWKWARD, Items.HONEYCOMB, HastePasteModPotions.HASTEE.get()); 
                                                                                        ^ 
  symbol:   method get() 
  location: variable HASTEE of type Potion
```

### How to reproduce this issue?

Step 1: Create a potion item in MCreator.
Step 2: Build with the fabric generator.

### Operating system

Windows

### Details

MCreator Version: [2023.3]
Generator Type: [fabric-1.20.1]

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Read the tooltip
