### ISSUE TITLE
Missing line in procedure's generated code resulting in [cannot find symbol] error

### ISSUE THREAD

**Issue by subparfauxpas** [Goldorion/MCreatorFabricGenerator#490]
### Issue description

Code generated from procedure relating to a blocks' position (BlockPos) does not declare "pos" symbol before "pos" symbol is used, resulting in "error: cannot find symbol" when attempting to compile.
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/121001043/d24f85f9-524b-43da-b3be-11a80c4f9fde)
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/121001043/8a6ed72f-b2b0-420c-b0b4-767d7fb77476)

**My solution:** 
1. Lock element.
2. Edit code.
3. Paste new line containing: `BlockPos pos = hitResult.getBlockPos();` above the underlined line shown in 2nd attached image.

### How to reproduce this issue?

1. Create procedure with `Player right clicks block` trigger.
2. Add procedure template "Strip custom Log with any Axe"
3. Try to compile mod.

### Operating system

Windows

### Details

MCreator: 2023.3.36712
Fabric Generator: 1.20.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by purejosh** [comment]
`Fabric Generator: 1.20.1` is not a version of the Fabric Generator. What *version* are you using?

**Comment by Goldorion** [comment]
Same as #496 (already fixed)
