### ISSUE TITLE
Procedure doesnt compile

### ISSUE THREAD

**Issue by G-Utopia** [Goldorion/MCreatorFabricGenerator#491]
### Issue description

When I try to make a potion effect based procedure, when I save it it says that it cant compile it.

### How to reproduce this issue?

Create a procedure like this: 
![grafik](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/79647561/b9ecfc87-298f-4f38-82e3-66c79a11c758)

### Operating system

Windows

### Details

(First line in the logs stands everything)

### Logs

![grafik](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/79647561/583378ad-fe5d-419d-97f5-ac91f4e96699)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by purejosh** [comment]
Is this an armor set bonus? If so, don't use "on player tick update". That's a very large waste of resources. Add this exact procedure to the chestplate's tick procedure. The chestplate is the least likely to be worn, and usually the most expensive to make. 

If you add it to the chestplate tick procedure, it'll tick only when wearing the chestplate. This should work, as I'm using that same setup.

**Comment by Goldorion** [comment]
The "On Player tick update" trigger is not supported by the generator (even if it's marked as if). Please refer to the following file for all supported triggers. https://github.com/Goldorion/Fabric-Generator-MCreator/blob/1.20.1/Supported%20Global%20triggers.md
