### ISSUE TITLE
Its been a while....

### ISSUE THREAD

**Issue by PSGitHubUser1** [Goldorion/MCreatorFabricGenerator#497]
Gold, can want to know that what happened to you? 
Why are you not updating FBGen.., your exams are going on? or you're busy?

Plus 2023.4 has been released also..

**Comment by Goldorion** [comment]
I was busy with my university studies and taking a break from MCreator. I feel unmotivated from working on both the core and my plugins. Plus, I don't enjoy them as much as I did before working on them. I still like MCreator, but always working on it for multiple years on something can give you burnout, and I think I reached this point. MCreator 2023.4 was a big update to work on with the rest of the team and a ton of big features were merged, so even outside of the work waiting for me with the FB Generator, I just need to take a few weeks/months for me and doing something else. I've been in the community for more than 7 years now and I didn't stop being involved (with my mods, then plugins and now contributing and maintaining my plugins), so even if this is my non-returning point (surely not as I am still like working on new features, but it's still a possibility), I'm quite sure I can say I contributed more than enough to this project 😅

This is also why I tried to get some people to help me with the generator, so I'm not alone anymore in working on it and maintaining it, but I still didn't find the people, so I have to take on myself and continue doing all the work on my side. I'm not complaining. I wanted to make this plugin and I knew (maybe not enough though...) it was a big project, but I liked/like it and want to offer this possibility to the community.

Anyway, I know many of you are counting on me to have a Fabric Generator and I also know its current state needs more fixes, but I have to take a break. If I continue, that'll end with me leaving for good the community. Be more patient and I'll try to work on the update as soon as possible :)

I'm sorry for the delay 🙇

P-S: I also have another project (unrelated to MCreator, but related to development) and hobbies that I'm currently enjoying more, so they are also taking my time and motivation.

**Comment by PSGitHubUser1** [comment]
> I was busy with my university studies and taking a break from MCreator. I feel unmotivated from working on both the core and my plugins. Plus, I don't enjoy them as much as I did before working on them. I still like MCreator, but always working on it for multiple years on something can give you burnout, and I think I reached this point. MCreator 2023.4 was a big update to work on with the rest of the team and a ton of big features were merged, so even outside of the work waiting for me with the FB Generator, I just need to take a few weeks/months for me and doing something else. I've been in the community for more than 7 years now and I didn't stop being involved (with my mods, then plugins and now contributing and maintaining my plugins), so even if this is my non-returning point (surely not as I am still like working on new features, but it's still a possibility), I'm quite sure I can say I contributed more than enough to this project 😅
> 
> This is also why I tried to get some people to help me with the generator, so I'm not alone anymore in working on it and maintaining it, but I still didn't find the people, so I have to take on myself and continue doing all the work on my side. I'm not complaining. I wanted to make this plugin and I knew (maybe not enough though...) it was a big project, but I liked/like it and want to offer this possibility to the community.
> 
> Anyway, I know many of you are counting on me to have a Fabric Generator and I also know its current state needs more fixes, but I have to take a break. If I continue, that'll end with me leaving for good the community. Be more patient and I'll try to work on the update as soon as possible :)
> 
> I'm sorry for the delay 🙇
> 
> P-S: I also have another project (unrelated to MCreator, but related to development) and hobbies that I'm currently enjoying more, so they are also taking my time and motivation.

Dont feel alone or sad...
You are really a good guy.. I also feel that sometimes, like I made 4-7 mods and none of them got downloads more than 1K.. but I try my best.. 

(I also took a break and made some badges for devin's repo. Search "Devin's Badges" on github and check the issues tab.)

I am with you bro.. (all are with you becuase of this, FBGen)

**Comment by PSGitHubUser1** [comment]
Are you puzzled like I haven't any commits in FBGen from 1.5 week..


(just asking, casually.. Don't feel like I am pressurizing you... Asking cuz its 2 months soo...)
