### ISSUE TITLE
[BUG] Food doesn't compile properly

### ISSUE THREAD

**Issue by Jarfeh** [Goldorion/MCreatorFabricGenerator#50]
e: formatting

**Describe the bug**
When attempting to set a max stack size, mcreator will throw the error:
"**Your workspace contains mod elements that don't compile properly**"

The console will also display an error, in my case this one:
`C:\Users\HyperPotato\MCreatorWorkspaces\soda_mod\src\main\java\net\shinyy\sodamod\item\PepsiSyrupItem.java:21: error: cannot find symbol 
      super(new Item.Settings().group(ItemGroup.FOOD).maxStackSize(16)
`

**Log**
https://hastebin.com/afozicaroj.sql

**Affected version(s)** Pre-Release 1.16.2-1.0.0-alpha3

**To Reproduce**
1. Create an object that supports stacking
2. Set max stack size to anything other than 64 **(Seems to fail to compile even when set to 64..)**
3. Save mod element

**Expected behavior**
The max stack size will be set properly without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/58902941/89958590-112c3d00-dbef-11ea-8609-ece163fa922f.png)
![image](https://user-images.githubusercontent.com/58902941/89958533-e80bac80-dbee-11ea-860b-0c48b3437674.png)
![image](https://user-images.githubusercontent.com/58902941/89958556-f5c13200-dbee-11ea-8030-7081f374b6fd.png)

**Additional context**
Procedures seem to be unable to compile as well, though that will probably need another bug report.

**Comment by Jarfeh** [comment]
After some more quick testing, I've found that it just outright does not compile, even when set to a max stack size of 64..

**Comment by Goldorion** [comment]
Can you try to regenerate the code because it seems it uses .maxStackSize instead of .maxCount, so it's normal you get an error.

**Comment by Jarfeh** [comment]
~~I can manually change maxStackSize in the code to maxCount, and it will successfully build. When I regenerated the code, it reset it back to maxStackSize, and failed to compile again.~~
I just saw what you changed in the commit

**Comment by BoogieMonster1O1** [comment]
Seems to be fixed

**Comment by Goldorion** [comment]
The food element still doesn't compile properly.
