### ISSUE TITLE
Convert registry name to item still references Forge

### ISSUE THREAD

**Issue by hyperdotbat** [Goldorion/MCreatorFabricGenerator#500]
### Issue description

Yeah its impossible to use item tags, and I wanted to make like a config file that allows you to modify drops
https://imgur.com/a/CpdGF3T
![img1](https://imgur.com/WL7R3Zl.png)
![img2](https://imgur.com/vzg0WRE.png)
![img3](https://imgur.com/4u1zKFO.png)

I tried playing around with checking other imports like if Minecraft's tags work or if Fabric has any imports, but I see that not really, is the plugin or MCreator limitting the classes available for import or what?

### How to reproduce this issue?

- Create a procedure for anything
- Add a Spawn item/gem block or anything using the Convert registry name or Random item from tag blocks

### Operating system

Windows

### Details

Fabric Generator 1.9.10 for Minecraft 1.20.1 on MCreator 2023.3

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by hyperdotbat** [comment]
It literally only needs to change the registry to BuiltInRegistries, youre already registering the items there (I do not know if that is the standard for Fabric)
But after trying that with a custom code snippet ` Set item to (custom code snippet:) BuiltInRegistries.ITEM.get(new ResourceLocation(tag)) `
I have made a small plugin adding these procedure blocks in:
https://mega.nz/file/kGdnVLgI#U3nsoNAexKV0ZqG3ZJMia766f-7bjxvX7eM_QWU2hJo

**Comment by hyperdotbat** [comment]
Um why marked "works as intended", it literally references ForgeRegistries which are not available in Fabric hello?

**Comment by Goldorion** [comment]
(Works as designed because it works as it should be, meaning I didn't add support for it on purpose (I don't know how and I didn't want to search for it yet). That's my (own weird) way of thinking)

**Comment by hyperdotbat** [comment]
(Ive noticed, its veery weird, and annoying. Works as intended ≠ i dont know how to implement that, its better to say you dont know how instead of doing this song and dance)
But regardless, Ive literally shown you how to fix it lol, atleast just use BuiltInRegistries

(Also please accept my pull requests regarding other stuff in the Fabric Generator and File Manager)
