### ISSUE TITLE
Use BCLib For End Biomes And Better Custom Dimensions Support

### ISSUE THREAD

**Issue by ErzeKawek** [Goldorion/MCreatorFabricGenerator#502]
### Feature description

This is a request to use [BCLib](https://modrinth.com/mod/bclib) instead of Fabric Biomes API For The End Biomes for Better Compatibility of the BetterX mods and Working Surface And Underground Builder.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I try to avoid as much as possible external libraries for the generator. I only made an exception for TerraBlender as I didn't have a choice and it's quite a known/used lib, but that's all.

**Comment by ErzeKawek** [comment]
Well I'll just fork this no matter what
