### ISSUE TITLE
End Biome Option Doesn't Generate Surface Builder Ground block

### ISSUE THREAD

**Issue by ErzeKawek** [Goldorion/MCreatorFabricGenerator#504]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

When i make an end biome with a custom block for a surface block, it generates end stone only for some reason.

### How to reproduce this issue?

Step 1 : Make an End Biome
Step 2 : Add a Surface Builder Ground block
Step 3 : RunClient
Step 4 : Go To The End Outer Islands
Step 5 : Locate Biome
Step 6 : See Theres Nothing but end stone

### Operating system

Windows

### Details

MCreator Version : 2023.4
Generator Version : 1.9.12

**Comment by Goldorion** [comment]
I noticed it and I can not change it. It seems to be something from the End generator itself. Modifying it is out of the scope of the generator.
