### ISSUE TITLE
Workspace won't start

### ISSUE THREAD

**Issue by MaximeriX** [Goldorion/MCreatorFabricGenerator#505]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

The new workspace does not start and generates an error.
[log.txt](https://github.com/Goldorion/Fabric-Generator-MCreator/files/14164927/log.txt)

### How to reproduce this issue?

1. Open MCreator
2. Create a new workplace with fabric
3. Select Fabric 1.20.1

### Operating system

Windows

### Details

MCreator version: [2023.4.52316]
Plugin version: [1.9.12]
Generator type: [fabric-1.20.1]

### Example workspace

I can't export the archive because the project doesn't even start

### Logs

[log.txt](https://github.com/Goldorion/Fabric-Generator-MCreator/files/14164942/log.txt)

**Comment by purejosh** [comment]
This is weird. I have no issues creating a new workspace in 2023.4. I've also opened existing workspaces created in 2023.3, using 2023.4, with no issues. 

https://gist.github.com/purejosh/ec1df6c120f84fed4f5505817e4daae5

Are you using the .zip MCreator 2023.4, or the installed 2023.4?

**Comment by Goldorion** [comment]
This happens sometimes with the task that gave you the error. I have no idea why this happens. The only thing I know that can help is to try again when it fails and it always (99%) worked. Once you're able to get your workspace created one time, it doesn't happen again with the same Minecraft version (and it doesn't seem to cause problems on all MC versions for some reasons)

**Comment by voided-ptr** [comment]
similar to mine  [#482](https://github.com/Goldorion/Fabric-Generator-MCreator/issues/482)
