### ISSUE TITLE
[BUG] Can't launch the game

### ISSUE THREAD

**Issue by Goldorion** [Goldorion/MCreatorFabricGenerator#51]
**Describe the bug**
When we try to run the environment test, we get several errors. https://pastebin.com/jRTDBFYX

**Log**
The mcreator.log doesn't provide something useful to solve the bug.

**Affected version(s)** 
1.16.1-1.0.0-alpha3 and 1.16.2-1.0.0-alpha4

**To Reproduce**
1. Click on run client or run a server
2. Wait few seconds

**Expected behaviour**
Be able to play to Minecraft

**Additional context**

**Comment by OriCat101** [comment]
I have the same bug in the version: 1.16.3-1.0-pre6
It happens when I try to run the client or the server.

here is the log: https://pastebin.com/rvRwQAug

Sorry if my English isn't perfect.
