### ISSUE TITLE
[BUG] Attempting to apply the "glowing effect" to any item/tool returns a compilation fail.

### ISSUE THREAD

**Issue by Micasddsa** [Goldorion/MCreatorFabricGenerator#510]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

Trying to apply the "glowing effect" to any item/tool prevents the mod from being compiled. Searching around, this is a unique error. Instead of any error related to `@Environment(EnvType.CLIENT)`, it's now a error related to `@OnlyIn(Dist.CLIENT)`. Which is something I haven't seen before.

### How to reproduce this issue?

Step 1: Create a new workspace with the newest Fabric generator
Step 2: Create a item/tool
Step 3: Save and Compile

### Operating system

Windows

### Details

MCreator version: 2023.4
Generator Version: fabric-1.20.1

### Logs

```
Executing Gradle task: build 
Build info: MCreator 2023.4.52316, fabric-1.20.1, 64-bit, 32633 MB, Windows 10, JVM 17.0.9, JAVA_HOME: E:\MCreator.2023.4.Windows.64bit\MCreator20234\jdk, started on: 2024-02-26-19:50:31 
  
> Configure project : 
Fabric Loom: 1.4.6 
> Task :compileJava FAILED 
C:\Users\Micasddsa\MCreatorWorkspaces\test\src\main\java\net\mcreator\test\item\test.java:34: error: cannot find symbol 
   @OnlyIn(Dist.CLIENT) 
    ^ 
  symbol:   class OnlyIn 
  location: class SuperEnchantedGoldenAppleItem 
C:\Users\Micasddsa\MCreatorWorkspaces\test\src\main\java\net\mcreator\test\item\test.java:34: error: cannot find symbol 
   @OnlyIn(Dist.CLIENT) 
           ^ 
  symbol:   variable Dist 
  location: class SuperEnchantedGoldenAppleItem 
2 errors 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --info option to get more log output. 
> Run with --scan to get full insights. 
BUILD FAILED in 3s 
1 actionable task: 1 executed 
```

**Comment by Vismaypikachu** [comment]
I have the exact same issue. I learned about MCreator today and downloaded it and attempted to use it without following a tutorial. I checked the glow effect and it caused my custom items to always fail to compile. Took me a while to figure out why.

**Comment by Goldorion** [comment]
> Took me a while to figure out why.

Yeah... sorry about that 😅 As I'm alone to make and maintain it, I often tend to do minimal tests and let users find the bugs for me and instead make a lot of patches. This takes much less time for me as I also need to maintain my other plugins in addition to my contributions to MCreator's core + not get a real burnout and leave the community forever + still have a life (having my university classes and doing other hobbies).

**Comment by Vismaypikachu** [comment]
No problem my man. I would offer help, but I have no clue how any of this lol.
