### ISSUE TITLE
The Puglin causes Java plantage

### ISSUE THREAD

**Issue by VulpesDev59** [Goldorion/MCreatorFabricGenerator#514]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

hello !
I'm having a problem. Since I downloaded the Fabric Plugin for Mcreator, a Java crash [-11] occurs systematically when I start Minecraft modded or my mcreator mod.
Help me please!

### How to reproduce this issue?

Step 1: I added the Fabric Puglin at Mcreator
Step 2: at startup java crash [-11] occurs without recourse

### Operating system

Windows

### Details

Mcreator 2023.4, Forge 1.19.2

### Logs

[log.txt](https://github.com/Goldorion/Fabric-Generator-MCreator/files/14539167/log.txt)

**Comment by Goldorion** [comment]
Uuh.. so I checked your log file and I noticed that it seems it's a native code problem (C++ problem, the language in which the JVM is made) and honestly, I have no idea. I asked some help on the private MCreator Team Discord as Klemen may know something, but until then, I can't help you much. Sorry about that

**Comment by Goldorion** [comment]
> This is incompatibility between dev Minecrafts and certain AMD drivers
> https://www.minecraftforum.net/forums/support/java-edition-support/3178072-solved-exception_access_violation-crash-atio6axx
> Klemen
