### ISSUE TITLE
[Bug] Adding any procedure trigger to an entity causes a compilation error.

### ISSUE THREAD

**Issue by arcade-smasher** [Goldorion/MCreatorFabricGenerator#515]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

I was trying to add a procedure to one of my mob's triggers, when it gave me a build error.

### How to reproduce this issue?

1. Make an entity.
2. Make a procedure.
3. Go to the triggers tab in the entity from step 1.
4. Add the procedure to any one of the triggers.
5. Save the workspace.
6. You will get a compilation error.

Here is an example of the trigger giving a build error.

https://github.com/Goldorion/Fabric-Generator-MCreator/assets/83091369/8189540d-34a5-4fc2-b9ff-5cfde5111e4a

### Operating system

Windows

### Details

MCreator version 2023.4
Genorator type: fabric 1.20.1

**Comment by Goldorion** [comment]
Please provide a minimal reproducible workspace.

**Comment by smmmadden** [comment]
@arcade-smasher - nice that you added the MOV file to show it, but you didn't provide the procedure details that is causing the compilation error.
