### ISSUE TITLE
Ability to Check if an entity is on the screen of a player

### ISSUE THREAD

**Issue by leobaker202** [Goldorion/MCreatorFabricGenerator#517]
### Prerequisites

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Feature description

a block that when used, will trigger if an entity (using Event/target entity, or Entity iterator) is on the screen of a player at all

**Comment by Goldorion** [comment]
Uh... this is not the purpose of the generator...
