### ISSUE TITLE
Synced Data TRYS to add an inventory WHEN IT IS NOT suppose to

### ISSUE THREAD

**Issue by leobaker202** [Goldorion/MCreatorFabricGenerator#518]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

Appearntly you needed more info on What it actually was

i wasn't ASKING for somethin to be added, its a bug that keeps happenin and its irritating me considerin i don't want my entity to have an inventory but synced data for some freakin reason keeps tryin to add one when it shouldn't

### How to reproduce this issue?

Create an entity - use synced data - done

### Operating system

Windows

### Details

1.9.13

**Comment by Goldorion** [comment]
You literally did the same thing ass before. If you don't respect what I ask you to provide, I won't care about your bug report. I have other things to do than trying to figure out exactly what;'s the exact problem by myself.

**Comment by leobaker202** [comment]
Are you this much of a freaking idiot?


I Litterally explained what the problem is in the post, and HOW TO FREAKING REPRODUCE IT

**Comment by ErzeKawek** [comment]
Then disable the inventory
