### ISSUE TITLE
Error when making empty new item

### ISSUE THREAD

**Issue by WillowTheWhimsical** [Goldorion/MCreatorFabricGenerator#521]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

In a completely new workspace, adding an item with absolutely nothing changed (other than the texture) results in an error. Here's the console output:
```
Executing Gradle task: build
Build info: MCreator 2023.4.52316, fabric-1.20.1, 64-bit, 32631 MB, Windows 10, JVM 17.0.9, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2024-03-16-23:50:13
 
> Configure project :
Fabric Loom: 1.4.6
> Task :compileJava
C:\Users\username\MCreatorWorkspaces\test\src\main\java\net\mcreator\test\init\TestModItems.java:31: error: incompatible types: ItemPropertyFunction cannot be converted to ClampedItemPropertyFunction  ItemProperties.register(item, new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
             ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
> Task :compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.
BUILD FAILED in 6s
1 actionable task: 1 executed
 
BUILD FAILED
Task completed in 8 seconds
```

### How to reproduce this issue?

Step 1: Add new item
Step 2: Add a texture
Step 3: Save and let it compile

### Operating system

Windows

### Details

MCreator Version: 2023.4
Fabric Generator Version: 1.9.14

**Comment by Sir-Crazynut** [comment]
same happens for me. I tried making it into a simple food and the error still pops up

**Comment by Ulysse2211** [comment]
Same here, I also tried with a tool but other elements worked. 
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/106011457/ba2a0f42-bc52-4eb1-843f-6cd7df8cb215)
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/106011457/3ce392f8-32ba-4463-8c97-fc90acae6601)

Error log:
`Executing Gradle task: build 
Build info: MCreator 2023.4.52316, fabric-1.20.1, 64-bit, 24443 MB, Windows 11, JVM 17.0.9, JAVA_HOME: E:\MCreator20234\jdk, started on: 2024-03-19-17:29:30 
  
> Configure project : 
Fabric Loom: 1.4.6 
> Task :compileJava FAILED 
[C:\Users\Ulyss\MCreatorWorkspaces\hetonia\src\main\java\fr\hetoniastudios\hetonia\init\HetoniaModItems.java:31](file:///C:/Users/Ulyss/MCreatorWorkspaces/hetonia/src/main/java/fr/hetoniastudios/hetonia/init/HetoniaModItems.java:31): error: incompatible types: ItemPropertyFunction cannot be converted to ClampedItemPropertyFunction 
      ItemProperties.register(item, new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking"))); 
                                                                                                ^ 
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output 
1 error 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --info option to get more log output. 
> Run with --scan to get full insights. 
BUILD FAILED in 1s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 6 seconds`

**Comment by Ulysse2211** [comment]
I tired to use an older version with an older version of mcreator and it worked. It may be a temorary fix for thoes who don't need new features now.
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/106011457/51974357-0e7d-4fe5-8c82-c83af88d69ca)

**Comment by Goldorion** [comment]
I know where and what is the cause. I just don't have the time currently (busy with university)

**Comment by PanPanda1** [comment]
> I tired to use an older version with an older version of mcreator and it worked. It may be a temporary fix for those who don't need new features now.

for anyone finding this, you can just downgrade to the previous version of Fabric Generator (1.9.13) and stay on the latest version of MCreator, and it should all compile fine, likely the best solution until gold has time to implement the fix^
