### ISSUE TITLE
I can't create a workspace

### ISSUE THREAD

**Issue by KubeLex** [Goldorion/MCreatorFabricGenerator#522]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

I get an error when I try to create a workspace. 

### How to reproduce this issue?

1) Install the plugin
2) Try to create a workspace 
3) Get an error

### Operating system

Windows

### Details

MCreator 2023.4 Fabric 1.20.1

### Example workspace

Not possible

### Logs

https://pastebin.com/AFCF7ajz

**Comment by KubeLex** [comment]
I saw similar but not exact questions, but there were no answers anywhere.

**Comment by Goldorion** [comment]
Don't paste logs directly in the bug report. Use either a txt file or a gist or  Pastebin.

Also, which version of the plugin do you use?

**Comment by KubeLex** [comment]
> Не вставляйте журналы непосредственно в отчет об ошибке. Используйте текстовый файл, gist или Pastebin.
> 
> И еще, какую версию плагина вы используете?

Sorry, I've now added a link to the logs. 
Plugin version : 1.10

**Comment by KubeLex** [comment]
> Don't paste logs directly in the bug report. Use either a txt file or a gist or Pastebin.
> 
> Also, which version of the plugin do you use?

Pls help
