### ISSUE TITLE
Fabric Generator Preview for MCreator Snapshots

### ISSUE THREAD

**Issue by ModxVoldHunter** [Goldorion/MCreatorFabricGenerator#523]
### Prerequisites

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Feature description

a preview version of fabric so you can experiment with the generator to see what works and what doesn't for snapshot versions of mcreator

**Comment by Goldorion** [comment]
I was doing this in the past (porting to each new snapshot). However, this is a much bigger time investment which I'm no longer able to offer due to my university classes (and partially my motivation too)
