### ISSUE TITLE
When I updated my generator version my biomes had bugs

### ISSUE THREAD

**Issue by Realbizzy** [Goldorion/MCreatorFabricGenerator#528]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

So I updated from a version that required Terrablender to one that didn't need Terrablender and i started to get errors in my console, I have no idea what they mean but I tried deleting the files they lead to but the Terrablender file kept giving me an error and when i deleted that i just kept getting errors
![image](https://github.com/Goldorion/Fabric-Generator-MCreator/assets/164163096/d42ec281-e933-4dc1-ad66-417e5cde208c)

### How to reproduce this issue?

Update from a version that requires terrablender to one that doesnt

### Operating system

Windows

### Details

MCreator 2023.4
Fabric 1.10

### Logs

Executing Gradle task: runClient 
Build info: MCreator 2023.4.52316, fabric-1.20.1, 64-bit, 16088 MB, Windows 11, JVM 17.0.9, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2024-04-06-18:49:29 
  
> Configure project : 
Fabric Loom: 1.4.6 
> Task :compileJava FAILED 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\Cursedbiome2Region.java:4](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/Cursedbiome2Region.java:4): error: package terrablender.api does not exist 
import terrablender.api.RegionType; 
                       ^ 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\Cursedbiome2Region.java:5](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/Cursedbiome2Region.java:5): error: package terrablender.api does not exist 
import terrablender.api.Region; 
                       ^ 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\Cursedbiome2Region.java:19](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/Cursedbiome2Region.java:19): error: cannot find symbol 
public class Cursedbiome2Region extends Region { 
                                        ^ 
  symbol: class Region 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\CypressForest2Region.java:4](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/CypressForest2Region.java:4): error: package terrablender.api does not exist 
import terrablender.api.RegionType; 
                       ^ 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\CypressForest2Region.java:5](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/CypressForest2Region.java:5): error: package terrablender.api does not exist 
import terrablender.api.Region; 
                       ^ 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\CypressForest2Region.java:19](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/CypressForest2Region.java:19): error: cannot find symbol 
public class CypressForest2Region extends Region { 
                                          ^ 
  symbol: class Region 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\NetherForestRegion.java:4](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/NetherForestRegion.java:4): error: package terrablender.api does not exist 
import terrablender.api.RegionType; 
                       ^ 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\NetherForestRegion.java:5](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/NetherForestRegion.java:5): error: package terrablender.api does not exist 
import terrablender.api.Region; 
                       ^ 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\NetherForestRegion.java:19](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/NetherForestRegion.java:19): error: cannot find symbol 
public class NetherForestRegion extends Region { 
                                        ^ 
  symbol: class Region 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\Softwoodforest2Region.java:4](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/Softwoodforest2Region.java:4): error: package terrablender.api does not exist 
import terrablender.api.RegionType; 
                       ^ 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\Softwoodforest2Region.java:5](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/Softwoodforest2Region.java:5): error: package terrablender.api does not exist 
import terrablender.api.Region; 
                       ^ 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\Softwoodforest2Region.java:19](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/Softwoodforest2Region.java:19): error: cannot find symbol 
public class Softwoodforest2Region extends Region { 
                                           ^ 
  symbol: class Region 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\SoftwoodforestRegion.java:4](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/SoftwoodforestRegion.java:4): error: package terrablender.api does not exist 
import terrablender.api.RegionType; 
                       ^ 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\SoftwoodforestRegion.java:5](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/SoftwoodforestRegion.java:5): error: package terrablender.api does not exist 
import terrablender.api.Region; 
                       ^ 
[C:\Users\mhdta\MCreatorWorkspaces\bizzys_tooltopia\src\main\java\net\mcreator\bizzystooltopia\world\biome\regions\SoftwoodforestRegion.java:19](file:///C:/Users/mhdta/MCreatorWorkspaces/bizzys_tooltopia/src/main/java/net/mcreator/bizzystooltopia/world/biome/regions/SoftwoodforestRegion.java:19): error: cannot find symbol 
public class SoftwoodforestRegion extends Region { 
                                          ^ 
  symbol: class Region 
15 errors 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --info option to get more log output. 
> Run with --scan to get full insights. 
BUILD FAILED in 4s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 4 seconds

**Comment by Goldorion** [comment]
Those lines are for TerraBlender code, so regenerate the code.

**Comment by Realbizzy** [comment]
That didnt work though, I got the same thing in the console, i also tried deleting some of the files which it was leading to (again) but it didnt work so i put the files back

**Comment by Realbizzy** [comment]
i still have this problem

**Comment by Goldorion** [comment]
Where did you see I updated the plugin?

**Comment by Realbizzy** [comment]
well i updated i think 1.8 or 1.7 to 1.10

**Comment by Goldorion** [comment]
I wasn't speaking of this. You message said it was still not working yet... while I never updated the generator since you published your issue. Your previous message was completely useless and just annoying for me as you don't help and you just had more useless pressure.

**Comment by smmmadden** [comment]
@Realbizzy the error message is saying that the terrablender api is missing.  Your first post mentioned you removed it, have you tried to add it back in?  The last message makes no sense as @Goldorion stated.  What does updated 1.8 or 1.7 to 1.10 mean.
Make sure you are using the correct terrablender api version, fabric api version that matches the minecraft version you're trying to use.  A quick google search shows that the developer of terrablender is busy and a version to support 1.20.1 may not be available yet.

**Comment by Goldorion** [comment]
Another quick search will inform you that I no longer use TerraBlender for the Fabric Generator. Please try again.

**Comment by Realbizzy** [comment]
nonono this is what happened, i updated my fabric to 1.10 then it wasnt working so i downgraded it to the version i was using before 1.10, for some reason my terrablender files didnt get deleted so i couldnt test the mod, meaning it was most likely not gonna work with anything else, regenerating the gradle didnt work either so yeah....

**Comment by Realbizzy** [comment]
also im tryna remove terrablender cuz i only had it in due to older versions of the fabric generator havin it

**Comment by Realbizzy** [comment]
oh and @smmmadden when i said i removed it i mean i removed the files it was talking about, not terrablender, i tried removing terrablender too but i still got errors

**Comment by Realbizzy** [comment]
can someone help its just so annoying how i cant update fabric launcher

**Comment by Realbizzy** [comment]
oh yeah when i said i updated 1.8 or 1.7 to 1.10 i meant the fabric generator version, an as for the thing where you had not updated when i made this post i know, i just saw the update a bit late, i skipped alot of versions, sorry for the confusion!

**Comment by Realbizzy** [comment]
This was solved (i think) by upadting to the version before 1.10, i was a lot of versions behind, but now i got another problem, so ill just make another issue about that
