### ISSUE TITLE
potion effects cause a build error

### ISSUE THREAD

**Issue by VoidWasThere** [Goldorion/MCreatorFabricGenerator#530]
### Issue tracker rule checks (please read carefully)

- [x] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

a workspace with a potion effect will fail to build

### How to reproduce this issue?

step 1. open any workspace with fabric generator 1.20.1 - 0.83.1
step 2. add a potion effect

### Operating system

Windows

### Details

MCreator version: 2023.4
Generator: fabric-1.20.1 - 0.83.1

### Example workspace

[mcreator_potion_effects_crash_bug_workspace.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/14951540/mcreator_potion_effects_crash_bug_workspace.zip)

### Logs

https://gist.github.com/VoidWasThere/1f4e3eadf5dc76bdd4de60aa1fda1d3b

**Comment by SLDTyp0** [comment]
Also an issue on macos
