### ISSUE TITLE
Mod can't Load and says not specify supportedversions

### ISSUE THREAD

**Issue by 510208** [Goldorion/MCreatorFabricGenerator#531]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

I installed Fabric-Generator, and installed Minecraft 1.20.1 Version with fabric 0.15.10
But MCreator said `[Plugin Loader] Plugin generator-fabric-1.20.1 does not specify supportedversions.`

### How to reproduce this issue?

I just install the latest version MCreator Fabric Generator, install Minecraft 1.20.1 and latest Fabric loader and Fabric API...

### Operating system

Windows

### Details

- MCreator: 2024.1
- Fabric Generator: [This version](https://github.com/Goldorion/Fabric-Generator-MCreator/releases/tag/1.20.1-1.10)

- Minecraft: 1.20.1
- Fabric: 0.15.10
- Fabric API: 0.92.1

### Logs

https://gist.github.com/510208/8e0b4717e650e10987e4c71e95cc9177

**Comment by Goldorion** [comment]
I never said the Fabric Generator was updated to MCreator 2024.1.

**Comment by 510208** [comment]
Sorry, Where can I download `MCreator 2023.2.22518`
And when will Fabric Generator support Minecraft 1.20.2
