### ISSUE TITLE
Are you planning to add liquids?

### ISSUE THREAD

**Issue by prufme** [Goldorion/MCreatorFabricGenerator#536]
### Prerequisites

- [ ] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Feature description

Are you planning to add liquids?

**Comment by Goldorion** [comment]
I don't like lies. You said it wasn't already asled and it was. https://github.com/Goldorion/Fabric-Generator-MCreator/issues/334

**Comment by prufme** [comment]
> I don't like lies. You said it wasn't already asled and it was. #334

LMAO nice dodge the question
