### ISSUE TITLE
1.19.2 support

### ISSUE THREAD

**Issue by DarkRaider12** [Goldorion/MCreatorFabricGenerator#543]
### Prerequisites

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Feature description

is it possible if you could make a 1.19.2 genarator?
please

**Comment by Goldorion** [comment]
https://github.com/Goldorion/Fabric-Generator-MCreator/releases/tag/1.19.2-1.8.9
