### ISSUE TITLE
plugin isn't working

### ISSUE THREAD

**Issue by akk112233** [Goldorion/MCreatorFabricGenerator#547]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

"IO error:Cannot assign field "bulitin" because "plugin" is null"

### How to reproduce this issue?

put "fabric generator Mcreater 1.20.1"in plugin then launched mcreater.(sorry,my English isn't so good)

### Operating system

Windows

### Details

mcreater version:2023.4
generation version:fabric 1.20.1

**Comment by Goldorion** [comment]
https://mcreator.net/forum/107531/final-chapter-my-journey
