### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by bhxp** [Goldorion/MCreatorFabricGenerator#549]
### Prerequisites

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Feature description

since the developer has quit, is there anyway to get the latest fabric generator, and get it to work with 1.21 without coding?

**Comment by DizzyWhaleX** [comment]
It's called switch to forge. MCreator also does not appear to have 1.21 support either.

**Comment by bhxp** [comment]
> It's called switch to forge. MCreator also does not appear to have 1.21 support either.
@DizzyWhaleX 

forge sucks lwk, there aint no way im switching to that slow modding platform

**Comment by smmmadden** [comment]
NeoForge is much better than Forge and the direction where MCreator is moving towards.

**Comment by Goldorion** [comment]
https://mcreator.net/forum/107531/final-chapter-my-journey
