### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by watarod** [Goldorion/MCreatorFabricGenerator#553]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

Hi,
MC creator says that this plugin failed to load :C.
It says that plugin is missing supportedversions.

### How to reproduce this issue?

Step 1: Load the plugin zip (generator-fabric-1.20.1.zip)
Step 2: Close and open up mcreator again
Step 3: You get an error message "reason: plugin is missing supportedversions"

### Operating system

Windows

### Details

MCcreator 2024.3
Windows 10

**Comment by TimiksOMG** [comment]
use the mcreator version 2023.4 ONLY
