### ISSUE TITLE
moditems.java is not being generated in 2024.3

### ISSUE THREAD

**Issue by Tenchu98** [Goldorion/MCreatorFabricGenerator#554]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Issue description

I added a new item to my workspace and mcreator stopped generating the moditems.java when regenerating the code. I have cleared the gradle cache and even reimported the workspace and it is not corrected.

### How to reproduce this issue?

I simply added a new projectile and item, but I am not sure what caused it.

### Operating system

Windows

### Details

Build info: MCreator 2024.3.42716, neoforge-1.21.1, 64-bit, 31941 MB, Windows 11, JVM 21.0.4, JAVA_HOME: D:\mcreator\MCreator20243\jdk, started on: 2024-10-28-00:08:29

### Logs

https://pastebin.com/LncnzgMx

**Comment by Goldorion** [comment]
2024.3 is not supported by the last version of the plugin I published. Also, I stopped working on my plugins and I stopped being active in the community.
