### ISSUE TITLE
21.1 update!

### ISSUE THREAD

**Issue by NILEG2mc** [Goldorion/MCreatorFabricGenerator#555]
### Prerequisites

- [X] I have checked that this feature [is not already asked](https://github.com/Goldorion/Fabric-Generator-MCreator/issues).
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

### Feature description

pls!!

**Comment by Goldorion** [comment]
https://mcreator.net/forum/107531/final-chapter-my-journey
(And btw, how's the future of humanity when Minecraft 21.0 exists? 👀)
