### ISSUE TITLE
[Minor Issue] .project file inside generator Zip

### ISSUE THREAD

**Issue by BoogieMonster1O1** [Goldorion/MCreatorFabricGenerator#6]
I found a .project file inside release 0.5.0
It isn't supposed to be there, right? Because there certainly isn't one in the repository.

![Screen Shot 2020-06-12 at 3 32 41 PM](https://user-images.githubusercontent.com/62552372/84491598-6799ff80-acc2-11ea-88ee-1c8f19c0525f.png)

**Comment by Goldorion** [comment]
Thanks you for the report. I don't why it's here. I updated the file.
