### ISSUE TITLE
[Request] Add custom GUIs (+ inventories)

### ISSUE THREAD

**Issue by ghost** [Goldorion/MCreatorFabricGenerator#64]
Please make it so that I can create GUIs

**Comment by TheCoolestPaul** [comment]
Is this in the works?

**Comment by BoogieMonster1O1** [comment]
> Is this in the works?

I’ll let you know once I start working on it.

**Comment by shadichy** [comment]
[CottonMC/Cotton](https://github.com/CottonMC/Cotton) add this

**Comment by Goldorion** [comment]
If I need it, I will otherwise, I won't.

**Comment by shadichy** [comment]
the soucecode may helps
