### ISSUE TITLE
[Request] Add Block Update tick Trigger

### ISSUE THREAD

**Issue by katsumi143** [Goldorion/MCreatorFabricGenerator#67]
Title should be enough information, thanks!

**Comment by BoogieMonster1O1** [comment]
could you explain what you mean by an 'Update tick'?
I'm not sure if I understood you correctly

**Comment by CrispyChips6660** [comment]
A update tick trigger for what mod element/ what kind of update tick global trigger?

**Comment by katsumi143** [comment]
The trigger for blocks.
Edit: The trigger seems to exist but it's not functional, this is the same for most other triggers.
