### ISSUE TITLE
[Bug] compare_mcblocks, compare_mcitems, entity_checkgamemode, entity_remove_item, entity_add_potion, itemstack_get_count, world_play_bonemeal_event procedures cause build to fail.

### ISSUE THREAD

**Issue by ApemanMC** [Goldorion/MCreatorFabricGenerator#71]
**Describe the bug**
The procedures: compare_mcblocks, compare_mcitems, entity_checkgamemode, entity_remove_item, entity_add_potion, itemstack_get_count, world_play_bonemeal_event (from SomeoneElse's Miscellaneous plugin) cause the build to fail.

**Log**
https://hastebin.com/fodezahupe.coffeescript

**Affected version(s)** v1.0.0+pre.2

**To Reproduce**
Attempt to use any of the above procedures.

**Comment by CrispyChips6660** [comment]
Because they aren't designed for use with
 fabric...

**Comment by ApemanMC** [comment]
> Because they aren't designed for use with
> fabric...

Will there be procedure blocks made to replace these that are designed for use with fabric? There doesn’t appear to be an alternative to any of these at the moment.

**Comment by Goldorion** [comment]
https://github.com/ClothCreators/MCreatorFabricGenerator/wiki/List-of-procedure-blocks-in-1.0.0

**Comment by ApemanMC** [comment]
> https://github.com/ClothCreators/MCreatorFabricGenerator/wiki/List-of-procedure-blocks-in-1.0.0

So every procedure that is not on that list will never be able to work or be replaced on fabric?

I understand this is a prelease and more stuff will work in the future, Im just curious about the procedures.
