### ISSUE TITLE
(Not exactly a bug, but I don't know where else to post) Repeatedly getting error messages when making custom blocks

### ISSUE THREAD

**Issue by PrestoPesto** [Goldorion/MCreatorFabricGenerator#74]
So, I'm trying out the Fabric generator, seeing what I can do with it (it seems awesome, by the way). I tried making a simple block as a test, giving it a texture, setting hardness/resistance, etc. However, I kept on getting error messages, even when I would do nothing but set a texture, leaving everything else at the default.

**Log**
https://pastebin.com/rAEBdrKV

**Affected version(s)** Honestly, not sure. The file is called "generator-fabric-1.16.3_0" if that helps.

**Comment by BoogieMonster1O1** [comment]
Can you send your workspace.zip?
I’ll test it out and see if I can find the problem of why it’s not compiling properly

**Comment by PrestoPesto** [comment]
[Here](http://www.mediafire.com/file/l4vdbyj9dzvlsee/brokenworkspace.zip/file) (I think I exported it correctly).

**Comment by silentnyte** [comment]
I am having the same issue. Not sure if this from your addon or a MCreator issue. The auto generated ClientInit.java file is generating with the incorrect instance name. block_BLOCK should be the new block name. I locked the model and manually changes this and everything compiles correctly. This occurs with both ClothCommons 1.0 and 1.1.0

public class ClientInit implements ClientModInitializer {
	@Override
	public void onInitializeClient() {
		BlockRenderLayerMap.INSTANCE.putBlock(MyMod.**block_BLOCK**, RenderLayer.getCutoutMipped());
		HudRenderCallback.EVENT.register((matrices, tickDelta) -> {
		});
		ClientTickEvents.END_CLIENT_TICK.register((client) -> {
		});
	}
}

**Comment by BoogieMonster1O1** [comment]
Fixed. I'll release a new version in a few hours.

**Comment by heyimspook** [comment]
Have an ETA on the new release with the bugfix? Not to sound impatient but I'd love to finish my mod for 1.16.3 and this plugin's been a lifesaver so far! :)
