### ISSUE TITLE
Can't make custom armor

### ISSUE THREAD

**Issue by MikiPro3** [Goldorion/MCreatorFabricGenerator#76]
I'm trying to make a custom Fabric 1.16.2 mod, that has a lot of new items, specifically ore packs, but whenever I try to make custom armor, I get an error saying that it couldn't compile properly. I tryied changing the settings, but nothing helps, so I exported the workspace as a zipped folder, and I would really appreciate if someone could help me...
Configuring compiler arguments for Java

Task :compileJava FAILED
C:\Users\Admin\MCreatorWorkspaces\too_much_new_items_\src\main\java\net\mcreator\toomuchnewitems\item\RubyArmorArmorMaterial.java:20: error: expected
SoundEvents.,
^
1 error
FAILURE: Build failed with an exception.

What went wrong:

Execution failed for task ':compileJava'.
Compilation failed; see the compiler error output for details.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Get more help at https://help.gradle.org
BUILD FAILED in 1s
That is the error code I get...

[cantmakearmor (1).zip](https://github.com/ClothCreators/MCreatorFabricGenerator/files/5297846/cantmakearmor.1.zip)

**Comment by ghost** [comment]
Armors must have a equip sound, give it a equip sound, it should compile properly
