### ISSUE TITLE
[Bug] Several error when building the mod after saves

### ISSUE THREAD

**Issue by ghost** [Goldorion/MCreatorFabricGenerator#78]
**Describe the bug**
The console shows several errors in the code. One of them is simply a typo.

**Log**
https://hastebin.com/xocuyifemu.coffeescript

**Affected version(s)** 
2020.4

**To Reproduce**
Simply create an item or block and save

**Expected behaviour**
The build will fail with similar errors

**Comment by BoogieMonster1O1** [comment]
Should be fixed in the latest release. Let me know if there's any problems

**Comment by ghost** [comment]
@BoogieMonster1O1 do you mean the pre6 release? Because the typo is still there.
