### ISSUE TITLE
[Request] Global Variables

### ISSUE THREAD

**Issue by ghost** [Goldorion/MCreatorFabricGenerator#79]
**Describe the feature**
A way of adding global variables in the workspace like the forge generator allows.

**Describe why you want the feature**
Would be very useful when creating mods

**Comment by windows10win7posreadywoeskio** [comment]
can we make this closed ig

**Comment by mcwoodcraft** [comment]
Trying to port one of my mods to fabric but I use Variables basically everywhere so these errors are all over the place, So Variables would be pretty useful.
![image](https://user-images.githubusercontent.com/94686352/165304597-150fa5b9-6161-4c24-9a93-0c3f7f38d191.png)

**Comment by MagicalAlexey** [comment]
a lot of functions are missing here in principle

**Comment by TheRidiculousR** [comment]
> 

for player persistent you might be able to use NBT data?
idk if adding NBT to the player stays between deaths or not

**Comment by PossibleReference** [comment]
I would personally love this as you could make a mob summon structure like the iron golem and the wither have.

**Comment by MajAlva** [comment]
You can use scoreboard objectives.
