### ISSUE TITLE
[Suggestion] Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by BoogieMonster1O1** [Goldorion/MCreatorFabricGenerator#8]
It's very helpful to know stuff like this :
* Make commits for minor changes or merge them into larger changes
* Use newline curly braces in function and class definition
* Use the `this` keyword all the time for instance variables

and the list goes on

Consider creating one as it helps contributors use the preferred code style.
There's also a list of some useful files to add at Insights -> Community

**Comment by CrispyChips6660** [comment]
We will consider this.

**Comment by CrispyChips6660** [comment]
Merged #11 so marking this as fixed.
