### ISSUE TITLE
[Bug] Blocks Break Thread Three

### ISSUE THREAD

**Issue by WolfSteelpaw** [Goldorion/MCreatorFabricGenerator#80]
When I try to make any kind of block, it says "can't find symbol"

**Log**
https://pastebin.com/Vsp3gCxe

**Affected version(s)** Release/Snapshot 2020.4

**To Reproduce**
1. Go to 'elements'
2. Click on 'add element'
3. Click on 'block'
4. Make a block
5. Click "save" or "save and keep open"
4. C:\Users\USER\MCreatorWorkspaces\flat_vanilla_colors\src\main\java\net\mcreator\flatvanillacolors\ClientInit.java:25: error: cannot find symbol

A block would be created with no errors

![image](https://user-images.githubusercontent.com/69872319/95020496-3195d800-0631-11eb-8152-09af52db53a4.png)

[Evidence blocks break thread 3.zip](https://github.com/MCreator/MCreator/files/5323534/Evidence.blocks.break.thread.3.zip)

**Comment by BoogieMonster1O1** [comment]
I've fixed it. I'll release a new version in a few hours.

**Comment by WolfSteelpaw** [comment]
Thanks!

**Comment by WolfSteelpaw** [comment]
Can you send the file to me, please? I really want to make a mod that adds blocks, stairs, and slabs.
