### ISSUE TITLE
[Bug] Test Client can't boot on 1.0.0-pre6

### ISSUE THREAD

**Issue by Psora1** [Goldorion/MCreatorFabricGenerator#81]
**Bug Description**
When in a Fabric 1.16.3 workspace, regardless of what elements may be created in the workspace itself, the test client won't run and crashes upon any attempt to launch it.

**Log**
https://pastebin.com/7hAcpnS1

**Affected version(s)** v1.0.0-pre6

**To Reproduce**
1. Open a new workspace.
2. Allow workspace to build itself.
3. Client green arrow to run test client.
4. Wait until assets are downloaded and the test client will crash before even booting.

**Screenshot**
![crash_screenshot](https://user-images.githubusercontent.com/72408024/95631456-5c28cc00-0a49-11eb-9fc6-5345e2d516ad.png)

**Comment by ManuFlosoYT** [comment]
The same is happening to me.

**Comment by BluePlays21** [comment]
I started a fully fresh workspace, redownloaded mcreator, and the plugin and cloth commons, and I get the same error, trying with any other version works though, except for pre5, causing the block creation error that pre6 fixed.

**Comment by Anders-1** [comment]
Same problem here.

**Comment by Goldorion** [comment]
I tested and everything works fine now.

**Comment by Td-Flyy** [comment]
I'm on 2023.4 and I have the same issue, is there a way to fix this? I can't find any way to fix the problem. Just can't launch the client/server
