### ISSUE TITLE
Add Living entity support

### ISSUE THREAD

**Issue by Faris90** [Goldorion/MCreatorFabricGenerator#83]
How do I make a mob?

**Comment by BoogieMonster1O1** [comment]
We dont support making entities yet. Ill leave this issue open until we do so

**Comment by Don16ell** [comment]
Can u atleast make a copy and make the plugin 1.16.4 with the Living Entity Support?

**Comment by Goldorion** [comment]
A copy of what? The Forge generator? It does not work like that. I updated two weeks ago and it is the last plugin i updated, so I will work on my other plugins before re updating it. I am alone to develop about 4-5 plugins + contribute to MCreator, so it can take time.

**Comment by Don16ell** [comment]
I am talking about fabric generator. I actually wanted living entity support for Fabric 1.16.4. I could wait
