### ISSUE TITLE
[Bug] Error Running Client With Fabric 

### ISSUE THREAD

**Issue by Anders-1** [Goldorion/MCreatorFabricGenerator#85]
Hi,

I am using the Fabric Generator Plugin but whenever I try to launch the client I get an error. I am on version 1.16.3 Log: https://pastebin.com/CCEkDp4S

Thanks!

**Comment by BoogieMonster1O1** [comment]
Fixed in the 1.17 branch

For 1.16, a quick fix would be to edit the fabric.mod.json inside src/main/resources and remove the
```
"mixins": [
  "modid.mixins.json"
]
```
part
and if there's a comma before `"mixins"`, remove that too

i will be pushing a fix to the 1.16 branch soon
