### ISSUE TITLE
Mod refuses to build

### ISSUE THREAD

**Issue by TheMaskedMan00** [Goldorion/MCreatorFabricGenerator#87]
Describe the bug

Whenever I try to Export the Jar it says that one of the mod elements cannot compile, This is incorrect because I have removed everything and added just a single block and it still refuses to work, The console does not say anything that could help me figure out what is causing this. So I'm stuck.

Steps To Reproduce

When possible, attach your MCreator workspace (preferably a minimal example workspace required to reproduce the bug; use File -> Export workspace to a shareable ZIP...).

Please specify which mod elements to check in your workspace too, if applicable.

Screenshots
https://cdn.discordapp.com/attachments/780876349422043156/782654190257963048/Screen_Shot_2020-11-29_at_12.07.39_PM.png

Details

MCreator version: 2020.5
Generator type: Fabric -1.16.3
OS: OSX
Minimal reproducible example workspace

Dont think it has anything to do with the workspace
Logs

Executing Gradle task: build
Build info: MCreator 2020.5.47520, fabric-1.16.3, 64-bit, 32768 MB, Mac OS X, JVM 1.8.0_265, JAVA_HOME: /Applications/MCreator.app/Contents/MacOS/jdk/Contents/Home/jre

Configure project :
Fabric Loom: 0.4.33 Build(jenkins #33)
:setting up loom dependencies
:setting up mappings (yarn 1.16.3+build.1)
Configuring compiler arguments for Java
Task :compileJava UP-TO-DATE
Task :processResources UP-TO-DATE
Task :classes UP-TO-DATE
Task :jar UP-TO-DATE
Task :remapJar UP-TO-DATE
Task :assemble UP-TO-DATE
Task :compileTestJava NO-SOURCE
Task :processTestResources NO-SOURCE
Task :testClasses UP-TO-DATE
Task :test NO-SOURCE
Task :check UP-TO-DATE
Task :sourcesJar
Task :remapSourcesJar
:remapping sources
:loading named -> intermediary source mappings
Task :build
BUILD SUCCESSFUL in 1s
6 actionable tasks: 2 executed, 4 up-to-date
Task completed in 1552 milliseconds

Additional context

Could It be that I need to have a fresh Fabric 1.16.3 somewhere? I have it but its in MultiMC. Not sure if thats whats causing the problem.

**Comment by NameLord** [comment]
I get the same error.. if you know how to fix it or try to fix it dm me on discord
N_George#0733
