### ISSUE TITLE
Fabric 1.17 build gardle doesn't work

### ISSUE THREAD

**Issue by Byllfighter** [Goldorion/MCreatorFabricGenerator#90]
Fabric 1.17 build gardle doesn't work

 
 
<code>Executing Gradle task: runClient 
Build info: MCreator 2020.6.52319 EAP (52319), fabric-1.17, 64-bit, 7966 MB, Windows 8.1, JVM 1.8.0_275, JAVA_HOME: E:\Pylo\MCreatorEAP20206b52319\jdk 
> Configure project : 
Fabric Loom: 0.4.33 Build(jenkins #33) 
:setting up loom dependencies 
:setting up mappings (yarn 20w46a+build.23) 
Configuring compiler arguments for Java 
> Task :downloadAssets 
:downloading assets... 
> Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Could not create service of type DefaultGeneralCompileCaches using GradleScopeCompileServices.createGeneralCompileCaches(). 
   > Cannot lock Java compile cache (E:\Pylo\Workspaces\1.17\tst117\.gradle\6.5\javaCompile) as it has already been locked by this process. 
* Try: 
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 5s 
2 actionable tasks: 2 executed 
BUILD FAILED 
</code>Task completed in 5 seconds 

I want try run clien but it doesnt words

![image](https://user-images.githubusercontent.com/60580992/104319339-64c9ec00-54e9-11eb-8bb5-892d97e4ef60.png)

**Comment by BoogieMonster1O1** [comment]
restart your computer and try again

**Comment by Byllfighter** [comment]
It works!
