### ISSUE TITLE
[Bug] Your workspace contains mod elements that don't compile and could not be exported.

### ISSUE THREAD

**Issue by socksmoment** [Goldorion/MCreatorFabricGenerator#91]
No matter what I have in the workspace, a simple block, an item, whatever. I get the error "Your workspace contains mod elements that don't compile and could not be exported. No mod file was generated."

the version is Fabric Generator 1.16.3-1.0.0-pre.6.

https://pastebin.com/7A7Dr32f

1. Make a project using this generator.
2. Make anything, item, tool, whatever.
3. Try to export.
4. You will get the error.

I expected the generator to actually export the mod.

![image](https://user-images.githubusercontent.com/78066107/105945934-da76a180-602b-11eb-9f00-5a39dada0d71.png)

I know this hasn't been updated in months but please fix this. It makes the entire plugin unusable.

**Comment by Goldorion** [comment]
The bug seems to have been fixed. I'm closing the ticket.
