### ISSUE TITLE
[Bug] Cannot load plugin

### ISSUE THREAD

**Issue by shadichy** [Goldorion/MCreatorFabricGenerator#94]
**Describe the bug**
Idk why but the plugin doesn't load even tried anyway, pre6 worked perfectly but the latest release cannot be loaded, idk java code so please fix

**Log**
Nothing here

**Affected version(s)** Release/Snapshot X.X.X+foo
Release 1.0
**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem

**Additional context**

**Comment by Goldorion** [comment]
You don't give a lot of info, but you have to use the latest snapshot.

**Comment by shadichy** [comment]
The plugin doesnt load and idk why, it doesnt show up in plugin menu even
be reloaded several times

Vào Th 7, 20 thg 3, 2021 vào lúc 21:30 Goldorion ***@***.***>
đã viết:
