### ISSUE TITLE
[Request] GUI support

### ISSUE THREAD

**Issue by shadichy** [Goldorion/MCreatorFabricGenerator#95]
**Describe the feature**
everyone need this. a wonderful feature. forge have too. check out https://github.com/CottonMC/LibGui and if u guys can add this feature to the next update

**Describe why you want the feature**
everyone need this. a wonderful feature. forge have too

**Additional context**
https://github.com/CottonMC/LibGui

**Comment by Goldorion** [comment]
Duplicated of #64 
Thank you for the reference.
