### ISSUE TITLE
[Bug] error: cannot find symbol

### ISSUE THREAD

**Issue by Fisheiyy** [Goldorion/MCreatorFabricGenerator#99]
**Describe the bug**
I am trying to regenerate the code of my mod and it says it cannot find a symbol and points to a period

**Log**
Share mcreator.log in a paste website such as [Hastebin](https://hastebin.com/).
https://pastebin.com/PaR2aNVT
**Affected version(s)** Release/Snapshot X.X.X+foo
Mcreator 2021.1 EAP 12313 - Fabric Generator 1.0.1
**To Reproduce**
1. Go to workspace
2. Click on Build & Run
3. Scroll down to Regenerate Code and Build
4. See error in console

**Expected behavior**
Be able to compile the mod without having errors

**Screenshots**
If applicable, add screenshots to help explain your problem
![image_2021-03-28_181730](https://user-images.githubusercontent.com/54205282/112771507-dc3fef80-8ff1-11eb-886d-8a9dcf39cdf0.png)
**Additional context**

**Comment by Goldorion** [comment]
Can you give me your workspace, please?

**Comment by Fisheiyy** [comment]
> Can you give me your workspace, please?

sure

**Comment by Goldorion** [comment]
Fixed in 3e87487

**Comment by Fisheiyy** [comment]
ok im back, atleast im bug finding for you so you can fix any problems but it also generates more work for you
![image](https://user-images.githubusercontent.com/54205282/113374236-41694d00-9332-11eb-8042-84cbf6fef00c.png)
i know you also might want the workspace

**Comment by Goldorion** [comment]
Can you not report bug on another ticker?

**Comment by Fisheiyy** [comment]
> Can you not report bug on another ticker?

well it fits under this ticket technically since it cannot find symbol, i thought it might be a little excessive to create a whole 'nother ticket

**Comment by Goldorion** [comment]
**1 bug/issue**

**Comment by Fisheiyy** [comment]
so you want me to make another ticket? okay
